CREATE TABLE `location` (
 `id` varchar(36) NOT NULL, `tenant_id` varchar(36) NOT NULL, `name` varchar(150) NOT NULL, `normalized_name` varchar(150) NOT NULL, `code` varchar(30) NOT NULL, `normalized_code` varchar(30) NOT NULL, `type` enum('site','building','floor','room','outdoor','other') NOT NULL, `capacity` int, `description` text, `parent_id` varchar(36), `archived` boolean NOT NULL DEFAULT false, `archived_at` timestamp(3), `archive_reason` varchar(1000), `version` int NOT NULL DEFAULT 1, `created_at` timestamp(3) NOT NULL, `updated_at` timestamp(3) NOT NULL,
 CONSTRAINT `location_id` PRIMARY KEY(`id`), CONSTRAINT `location_tenant_id_id_unique` UNIQUE(`tenant_id`,`id`), CONSTRAINT `location_tenant_code_unique` UNIQUE(`tenant_id`,`normalized_code`), CONSTRAINT `location_capacity_check` CHECK (`capacity` IS NULL OR (`capacity` BETWEEN 1 AND 100000)), CONSTRAINT `location_version_check` CHECK (`version` > 0), CONSTRAINT `location_not_self_parent_check` CHECK (`parent_id` IS NULL OR `parent_id` <> `id`), CONSTRAINT `location_tenant_fkey` FOREIGN KEY (`tenant_id`) REFERENCES `tenant`(`id`), CONSTRAINT `location_tenant_parent_fkey` FOREIGN KEY (`tenant_id`,`parent_id`) REFERENCES `location`(`tenant_id`,`id`)
);
CREATE INDEX `location_tenant_archive_name_idx` ON `location` (`tenant_id`,`archived`,`normalized_name`);
CREATE TABLE `location_history` (`id` varchar(36) NOT NULL PRIMARY KEY,`tenant_id` varchar(36) NOT NULL,`location_id` varchar(36) NOT NULL,`actor_user_id` varchar(36) NOT NULL,`operation` varchar(50) NOT NULL,`from_version` int NOT NULL,`to_version` int NOT NULL,`reason` varchar(1000) NOT NULL,`occurred_at` timestamp(3) NOT NULL,CONSTRAINT `location_history_tenant_location_fkey` FOREIGN KEY (`tenant_id`,`location_id`) REFERENCES `location`(`tenant_id`,`id`),CONSTRAINT `location_history_tenant_actor_fkey` FOREIGN KEY (`tenant_id`,`actor_user_id`) REFERENCES `user`(`tenant_id`,`id`),CONSTRAINT `location_history_version_check` CHECK (`from_version` >= 0 AND `to_version` = `from_version` + 1));
CREATE INDEX `location_history_tenant_location_idx` ON `location_history` (`tenant_id`,`location_id`,`occurred_at`);
CREATE TABLE `location_reference` (`id` varchar(36) NOT NULL PRIMARY KEY,`tenant_id` varchar(36) NOT NULL,`location_id` varchar(36) NOT NULL,`label` varchar(255) NOT NULL,`active` boolean NOT NULL DEFAULT true,CONSTRAINT `location_reference_tenant_location_fkey` FOREIGN KEY (`tenant_id`,`location_id`) REFERENCES `location`(`tenant_id`,`id`));
CREATE INDEX `location_reference_tenant_active_idx` ON `location_reference` (`tenant_id`,`location_id`,`active`);
ALTER TABLE `class_group` ADD CONSTRAINT `class_group_tenant_location_fkey` FOREIGN KEY (`tenant_id`,`primary_location_id`) REFERENCES `location`(`tenant_id`,`id`);
