import { createClassGroupAction, editClassGroupAction, manageClassGroupAction, manageClassRelationshipAction } from "@/app/(tenant)/[domain]/(authenticated)/master/rombel/actions";
import { MasterDataFormDialog } from "@/components/master-data/master-data-form-dialog";
import { MasterDataWorkspace } from "@/components/master-data/master-data-workspace";
import { CLASS_GROUP_EDUCATION_LEVELS, createClassGroupService, type ClassGroup, type ClassGroupReferenceData } from "@/lib/class-group";
import { classGroupStore } from "@/lib/class-group-data";
import { createClassMembershipService, type ClassMembership, type HomeroomAssignment, type RelationshipReferenceData } from "@/lib/class-membership";
import { classMembershipStore } from "@/lib/class-membership-data";
import { queryClassGroups } from "@/lib/class-group-query";
import type { MasterDataSearchParams } from "@/lib/master-data-workspace";
import { enforceMasterDataAccess } from "@/lib/tenant-master-data-route-access";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select as UISelect, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from "@/components/ui/collapsible";
const labels = { draft: "Draft", active: "Aktif", closed: "Ditutup", cancelled: "Dibatalkan" } as const;
const messages: Record<string, string> = { saved: "Perubahan Rombongan Belajar tersimpan.", conflict: "Data berubah sejak dibuka.", "active-membership-exists": "Siswa sudah memiliki Keanggotaan Rombongan Belajar aktif.", "planned-membership-exists": "Siswa sudah memiliki rencana keanggotaan Tahun Ajaran Draft.", "teacher-year-conflict": "Guru sudah menjadi Wali Kelas Rombel lain pada Tahun Ajaran ini.", "relationship-blocked": "Archive diblokir relationship aktif." };
export default async function RombelPage({ params, searchParams }: { params: Promise<{ domain: string }>; searchParams: Promise<MasterDataSearchParams & { result?: string }> }) {
  const [{ domain }, raw] = await Promise.all([params, searchParams]), principal = await enforceMasterDataAccess(domain, "read"), groups = createClassGroupService({ store: classGroupStore }), relationships = createClassMembershipService({ store: classMembershipStore });
  const [records, references, memberships, homerooms, relationshipReferences] = await Promise.all([groups.list(principal), groups.references(principal), relationships.listMemberships(principal), relationships.listHomerooms(principal), relationships.references(principal)]), result = queryClassGroups(records, raw), selected = records.find((x) => x.id === result.query.selected), basePath = `/${domain}/master/rombel`, code = typeof raw.result === "string" ? raw.result : undefined;
  return <div className="space-y-6 p-4 md:p-6">{code ? <p role={code === "saved" ? "status" : "alert"} className="rounded-lg border p-3">{messages[code] ?? `Perubahan ditolak: ${code}.`}</p> : null}<MasterDataWorkspace title="Rombongan Belajar" description="Kelola Rombel, Keanggotaan Rombongan Belajar, dan Wali Kelas dengan riwayat effective-dated." basePath={basePath} query={result.query} total={result.total} items={result.items.map((x) => ({ id: x.id, title: `${x.grade} ${x.groupName}`, description: `${references.academicYears.find((y) => y.id === x.academicYearId)?.label ?? "—"} · ${x.educationLevel}`, lifecycle: labels[x.lifecycle], archived: x.archived }))} detail={selected ? <Detail domain={domain} record={selected} references={references} relationshipReferences={relationshipReferences} memberships={memberships} homerooms={homerooms} writable={principal.capabilities.write} /> : undefined} filters={[{ name: "lifecycle", label: "Lifecycle", options: Object.entries(labels).map(([value, label]) => ({ value, label })) }]} sortOptions={[{ value: "name-asc", label: "Nama A–Z" }, { value: "name-desc", label: "Nama Z–A" }]}>{principal.capabilities.write ? <MasterDataFormDialog title="Buat Rombongan Belajar"><GroupForm domain={domain} references={references} /></MasterDataFormDialog> : <p>Workspace hanya-baca.</p>}</MasterDataWorkspace></div>;
}
function Detail({ domain, record, references, relationshipReferences, memberships, homerooms, writable }: { domain: string; record: ClassGroup; references: ClassGroupReferenceData; relationshipReferences: RelationshipReferenceData; memberships: readonly ClassMembership[]; homerooms: readonly HomeroomAssignment[]; writable: boolean }) {
  const memberHistory = memberships.filter((x) => x.classGroupId === record.id), homeroomHistory = homerooms.filter((x) => x.classGroupId === record.id), activeMembers = memberHistory.filter((x) => x.endedAt === null), currentHomeroom = homeroomHistory.find((x) => x.endedAt === null);
  return <div className="space-y-5"><span className="sr-only">Reactivation tidak memulihkan relationship lama; konteks akademik dikunci setelah Rombel aktif.</span><dl className="grid gap-3 sm:grid-cols-2"><Item label="Tahun Ajaran" value={references.academicYears.find((x) => x.id === record.academicYearId)?.label ?? "—"} /><Item label="Jenjang dan tingkat" value={`${record.educationLevel} · ${record.grade}`} /><Item label="Nama kelompok" value={record.groupName} /><Item label="Lifecycle" value={labels[record.lifecycle]} /><Item label="Status arsip" value={record.archived ? "Diarsipkan" : "Aktif"} /></dl><History title="Riwayat Keanggotaan Rombongan Belajar" rows={memberHistory.map((x) => `${relationshipReferences.students.find((s) => s.id === x.studentId)?.name ?? "Siswa"} · ${x.startedAt}–${x.endedAt ?? (x.planned ? "direncanakan" : "sekarang")} · ${x.reason}`)} /><History title="Riwayat Wali Kelas" rows={homeroomHistory.map((x) => `${relationshipReferences.teachers.find((t) => t.id === x.teacherId)?.name ?? "Guru"} · ${x.startedAt}–${x.endedAt ?? "sekarang"} · ${x.reason}`)} />{writable && !record.archived ? <><RelationshipForm domain={domain} operation="membership" record={record} references={relationshipReferences} /><RelationshipForm domain={domain} operation="transfer" record={record} references={relationshipReferences} memberships={activeMembers} /><RelationshipForm domain={domain} operation="homeroom" record={record} references={relationshipReferences} currentHomeroom={currentHomeroom} /><Collapsible className="rounded-lg border p-4"><CollapsibleTrigger className="font-semibold cursor-pointer">Edit Rombongan Belajar</CollapsibleTrigger><CollapsibleContent><GroupForm domain={domain} references={references} record={record} /></CollapsibleContent></Collapsible>{record.lifecycle === "draft" ? <><GroupAction domain={domain} record={record} operation="activate" label="Aktifkan Rombel" /><GroupAction domain={domain} record={record} operation="cancel" label="Batalkan Rombel" /></> : record.lifecycle === "active" ? <GroupAction domain={domain} record={record} operation="close" label="Tutup Rombel" /> : <GroupAction domain={domain} record={record} operation="archive" label="Arsipkan Rombel" />}</> : null}</div>;
}
function RelationshipForm({ domain, operation, record, references, memberships = [], currentHomeroom }: { domain: string; operation: "membership" | "transfer" | "homeroom"; record: ClassGroup; references: RelationshipReferenceData; memberships?: readonly ClassMembership[]; currentHomeroom?: HomeroomAssignment }) { const title = operation === "membership" ? "Tambah Siswa" : operation === "transfer" ? "Transfer Siswa ke Rombel ini" : currentHomeroom ? "Ganti Wali Kelas" : "Tetapkan Wali Kelas"; return <Collapsible className="rounded-lg border p-4"><CollapsibleTrigger className="font-semibold cursor-pointer">{title}</CollapsibleTrigger><CollapsibleContent><form action={manageClassRelationshipAction.bind(null, domain)} className="mt-3 space-y-3"><input type="hidden" name="operation" value={operation} /><input type="hidden" name={operation === "transfer" ? "toClassGroupId" : "classGroupId"} value={record.id} />{operation === "homeroom" ? <Select name="teacherId" label="Guru aktif" options={references.teachers.filter((x) => x.active && !x.archived).map((x) => ({ value: x.id, label: x.name }))} /> : <Select name="studentId" label="Siswa aktif" options={(operation === "transfer" ? memberships.map((x) => references.students.find((s) => s.id === x.studentId)).filter(Boolean) : references.students.filter((x) => x.active && !x.archived)).map((x) => ({ value: x!.id, label: x!.name }))} />}<Field name="effectiveDate" label="Tanggal efektif" type="date" /><Label className="block flex flex-col gap-1.5"><span className="text-sm font-medium">Alasan</span><Textarea required name="reason" className="min-h-20" /></Label><Button variant="outline" className="rounded-full px-4">{title}</Button></form></CollapsibleContent></Collapsible>; }
function History({ title, rows }: { title: string; rows: string[] }) { return <section><h3 className="font-semibold">{title}</h3>{rows.length ? <ol className="mt-2 space-y-2">{rows.map((x, i) => <li key={`${i}-${x}`} className="rounded border p-2 text-sm">{x}</li>)}</ol> : <p className="text-sm text-muted-foreground">Belum ada riwayat.</p>}</section>; }
function GroupForm({ domain, references, record }: { domain: string; references: ClassGroupReferenceData; record?: ClassGroup }) { const locked = record && record.lifecycle !== "draft"; return <form action={(record ? editClassGroupAction : createClassGroupAction).bind(null, domain)} className="mt-3 grid gap-3 sm:grid-cols-2">{record ? <><input type="hidden" name="id" value={record.id} /><input type="hidden" name="expectedVersion" value={record.version} /></> : null}<Select name="academicYearId" label="Tahun Ajaran" value={record?.academicYearId} disabled={locked} options={references.academicYears.filter((x) => !x.archived && ["draft", "active"].includes(x.lifecycle)).map((x) => ({ value: x.id, label: x.label }))} /><Select name="educationLevel" label="Jenjang" value={record?.educationLevel} disabled={locked} options={CLASS_GROUP_EDUCATION_LEVELS.map((x) => ({ value: x, label: x }))} /><Field name="grade" label="Tingkat" type="number" value={record?.grade} disabled={locked} /><Field name="groupName" label="Nama kelompok" value={record?.groupName} /><Field name="code" label="Kode (opsional)" value={record?.code ?? undefined} /><Field name="capacity" label="Kapasitas (opsional)" type="number" value={record?.capacity ?? undefined} /><Select name="primaryLocationId" label="Lokasi utama (opsional)" value={record?.primaryLocationId ?? ""} options={references.locations.filter((x) => !x.archived).map((x) => ({ value: x.id, label: x.name }))} /><Button className="rounded-full sm:col-span-2">Simpan</Button></form>; }
function GroupAction({ domain, record, operation, label }: { domain: string; record: ClassGroup; operation: string; label: string }) { return <form action={manageClassGroupAction.bind(null, domain)} className="rounded-lg border p-4"><input type="hidden" name="id" value={record.id} /><input type="hidden" name="expectedVersion" value={record.version} /><input type="hidden" name="operation" value={operation} /><Field name="reason" label="Alasan" /><Button variant="outline" className="mt-3 rounded-full px-4">{label}</Button></form>; }
function Field({ name, label, type = "text", value, disabled }: { name: string; label: string; type?: string; value?: string | number; disabled?: boolean }) { return <Label className="flex flex-col gap-1.5"><span className="text-sm font-medium">{label}</span><Input required={!label.includes("opsional")} name={name} type={type} defaultValue={value} disabled={disabled} />{disabled ? <input type="hidden" name={name} value={value} /> : null}</Label>; }
function Select({ name, label, value, options, disabled }: { name: string; label: string; value?: string; options: { value: string; label: string }[]; disabled?: boolean }) { return <Label className="block flex flex-col gap-1.5"><span className="text-sm font-medium">{label}</span><UISelect required name={name} defaultValue={value || undefined} disabled={disabled}><SelectTrigger><SelectValue placeholder="Pilih" /></SelectTrigger><SelectContent>{options.map((x) => <SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></UISelect>{disabled ? <input type="hidden" name={name} value={value} /> : null}</Label>; }
function Item({ label, value }: { label: string; value: string }) { return <div><dt className="text-sm text-muted-foreground">{label}</dt><dd>{value}</dd></div>; }
