CREATE TABLE `extracurricular` (`id` varchar(36) NOT NULL,`tenant_id` varchar(36) NOT NULL,`name` varchar(150) NOT NULL,`normalized_name` varchar(150) NOT NULL,`code` varchar(30) NOT NULL,`normalized_code` varchar(30) NOT NULL,`description` text,`default_location_id` varchar(36),`archived` boolean NOT NULL DEFAULT false,`archived_at` timestamp(3),`archive_reason` varchar(1000),`version` int NOT NULL DEFAULT 1,`created_at` timestamp(3) NOT NULL,`updated_at` timestamp(3) NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY `extracurricular_tenant_id_unique` (`tenant_id`,`id`),UNIQUE KEY `extracurricular_tenant_code_unique` (`tenant_id`,`normalized_code`),CONSTRAINT `extracurricular_tenant_fkey` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`),CONSTRAINT `extracurricular_location_fkey` FOREIGN KEY (`tenant_id`,`default_location_id`) REFERENCES `location` (`tenant_id`,`id`),CONSTRAINT `extracurricular_version_check` CHECK (`version`>0));
--> statement-breakpoint
CREATE INDEX `extracurricular_tenant_archive_name_idx` ON `extracurricular` (`tenant_id`,`archived`,`normalized_name`);
--> statement-breakpoint
CREATE TABLE `activity_group` (`id` varchar(36) NOT NULL,`tenant_id` varchar(36) NOT NULL,`extracurricular_id` varchar(36) NOT NULL,`academic_year_id` varchar(36) NOT NULL,`name` varchar(150) NOT NULL,`start_date` date NOT NULL,`end_date` date NOT NULL,`capacity` int NOT NULL,`location_id` varchar(36),`schedule_text` varchar(500) NOT NULL,`lifecycle` enum('planned','active','completed','cancelled') NOT NULL DEFAULT 'planned',`version` int NOT NULL DEFAULT 1,`created_at` timestamp(3) NOT NULL,`updated_at` timestamp(3) NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY `activity_group_tenant_id_unique` (`tenant_id`,`id`),CONSTRAINT `activity_group_extracurricular_fkey` FOREIGN KEY (`tenant_id`,`extracurricular_id`) REFERENCES `extracurricular` (`tenant_id`,`id`),CONSTRAINT `activity_group_year_fkey` FOREIGN KEY (`tenant_id`,`academic_year_id`) REFERENCES `academic_year` (`tenant_id`,`id`),CONSTRAINT `activity_group_location_fkey` FOREIGN KEY (`tenant_id`,`location_id`) REFERENCES `location` (`tenant_id`,`id`),CONSTRAINT `activity_group_range_check` CHECK (`end_date`>=`start_date`),CONSTRAINT `activity_group_capacity_check` CHECK (`capacity`>0));
--> statement-breakpoint
CREATE INDEX `activity_group_history_idx` ON `activity_group` (`tenant_id`,`extracurricular_id`,`academic_year_id`,`start_date`);
--> statement-breakpoint
CREATE TABLE `activity_advisor` (`id` varchar(36) NOT NULL,`tenant_id` varchar(36) NOT NULL,`group_id` varchar(36) NOT NULL,`advisor_kind` enum('teacher','staff') NOT NULL,`advisor_id` varchar(36) NOT NULL,`started_at` date NOT NULL,`ended_at` date,`reason` varchar(1000) NOT NULL,`created_by_user_id` varchar(36) NOT NULL,`created_at` timestamp(3) NOT NULL,PRIMARY KEY (`id`),CONSTRAINT `activity_advisor_group_fkey` FOREIGN KEY (`tenant_id`,`group_id`) REFERENCES `activity_group` (`tenant_id`,`id`),CONSTRAINT `activity_advisor_actor_fkey` FOREIGN KEY (`tenant_id`,`created_by_user_id`) REFERENCES `user` (`tenant_id`,`id`),CONSTRAINT `activity_advisor_range_check` CHECK (`ended_at` IS NULL OR `ended_at`>=`started_at`));
--> statement-breakpoint
CREATE INDEX `activity_advisor_history_idx` ON `activity_advisor` (`tenant_id`,`group_id`,`advisor_id`,`started_at`);
--> statement-breakpoint
CREATE TABLE `activity_participant` (`id` varchar(36) NOT NULL,`tenant_id` varchar(36) NOT NULL,`group_id` varchar(36) NOT NULL,`student_id` varchar(36) NOT NULL,`started_at` date NOT NULL,`ended_at` date,`reason` varchar(1000) NOT NULL,`created_by_user_id` varchar(36) NOT NULL,`created_at` timestamp(3) NOT NULL,PRIMARY KEY (`id`),CONSTRAINT `activity_participant_group_fkey` FOREIGN KEY (`tenant_id`,`group_id`) REFERENCES `activity_group` (`tenant_id`,`id`),CONSTRAINT `activity_participant_student_fkey` FOREIGN KEY (`tenant_id`,`student_id`) REFERENCES `student_profile` (`tenant_id`,`id`),CONSTRAINT `activity_participant_actor_fkey` FOREIGN KEY (`tenant_id`,`created_by_user_id`) REFERENCES `user` (`tenant_id`,`id`),CONSTRAINT `activity_participant_range_check` CHECK (`ended_at` IS NULL OR `ended_at`>=`started_at`));
--> statement-breakpoint
CREATE INDEX `activity_participant_capacity_idx` ON `activity_participant` (`tenant_id`,`group_id`,`started_at`,`ended_at`);
--> statement-breakpoint
CREATE TABLE `activity_event` (`id` varchar(36) NOT NULL,`tenant_id` varchar(36) NOT NULL,`extracurricular_id` varchar(36) NOT NULL,`group_id` varchar(36),`relationship_id` varchar(36),`actor_user_id` varchar(36) NOT NULL,`operation` varchar(50) NOT NULL,`effective_date` date,`reason` varchar(1000) NOT NULL,`occurred_at` timestamp(3) NOT NULL,PRIMARY KEY (`id`),CONSTRAINT `activity_event_extracurricular_fkey` FOREIGN KEY (`tenant_id`,`extracurricular_id`) REFERENCES `extracurricular` (`tenant_id`,`id`),CONSTRAINT `activity_event_group_fkey` FOREIGN KEY (`tenant_id`,`group_id`) REFERENCES `activity_group` (`tenant_id`,`id`),CONSTRAINT `activity_event_actor_fkey` FOREIGN KEY (`tenant_id`,`actor_user_id`) REFERENCES `user` (`tenant_id`,`id`));
--> statement-breakpoint
CREATE INDEX `activity_event_history_idx` ON `activity_event` (`tenant_id`,`extracurricular_id`,`occurred_at`);
