import { assignHeadmasterAction } from "@/app/(tenant)/[domain]/(authenticated)/master/profil/actions";
import type { HeadmasterAssignmentView, HeadmasterTeacher } from "@/lib/headmaster-assignment";

const messages: Record<string, string> = { saved: "Kepala Sekolah tersimpan.", "invalid-input": "Tanggal efektif dan alasan wajib valid.", "invalid-teacher": "Pilih Guru aktif yang belum diarsipkan dari sekolah ini.", overlap: "Tanggal efektif bertumpang tindih dengan riwayat Kepala Sekolah.", conflict: "Penugasan berubah bersamaan. Muat ulang lalu coba lagi.", "read-only": "Profil ini hanya dapat dibaca." };

export function HeadmasterHistory({ domain, current, history, teachers, readOnly, result }: { domain: string; current: HeadmasterAssignmentView | null; history: readonly HeadmasterAssignmentView[]; teachers: readonly HeadmasterTeacher[]; readOnly: boolean; result?: string }) {
  return <section className="rounded-xl border bg-card p-5" aria-labelledby="headmaster-title">
    <div><h2 id="headmaster-title" className="text-xl font-semibold">Kepala Sekolah</h2><p className="mt-1 text-sm text-muted-foreground">Penugasan menggunakan Guru aktif dan mempertahankan riwayat berdasarkan tanggal efektif.</p></div>
    {result && messages[result] ? <p role={result === "saved" ? "status" : "alert"} className="mt-4 rounded-lg border p-3 text-sm">{messages[result]}</p> : null}
    <div className="mt-5 grid gap-6 lg:grid-cols-2">
      <div><h3 className="font-semibold">Kepala Sekolah saat ini</h3>{current ? <dl className="mt-3 grid gap-2 text-sm"><div><dt className="text-muted-foreground">Nama Guru</dt><dd className="font-medium">{current.teacherName}</dd></div><div><dt className="text-muted-foreground">Mulai menjabat</dt><dd>{current.startedAt}</dd></div><div><dt className="text-muted-foreground">Alasan</dt><dd>{current.reason}</dd></div></dl> : <p className="mt-3 text-sm text-muted-foreground">Belum ada Kepala Sekolah aktif.</p>}</div>
      <div><h3 className="font-semibold">Riwayat sebelumnya</h3><ol className="mt-3 space-y-2">{history.filter((item) => item.endedAt !== null).map((item) => <li key={item.id} className="rounded border p-3 text-sm"><span className="font-medium">{item.teacherName}</span><br />{item.startedAt}–{item.endedAt}<br /><span className="text-muted-foreground">{item.reason}</span></li>)}</ol>{history.every((item) => item.endedAt === null) ? <p className="mt-3 text-sm text-muted-foreground">Belum ada riwayat sebelumnya.</p> : null}</div>
    </div>
    {!readOnly ? <form action={assignHeadmasterAction.bind(null, domain)} className="mt-6 grid gap-3 border-t pt-5 sm:grid-cols-2"><label className="block"><span className="text-sm font-medium">Guru aktif</span><select required name="teacherId" defaultValue="" className="mt-1 h-11 w-full border bg-background px-3"><option value="" disabled>Pilih Guru</option>{teachers.map((teacher) => <option key={teacher.id} value={teacher.id}>{teacher.name}</option>)}</select></label><label className="block"><span className="text-sm font-medium">Tanggal efektif</span><input required type="date" name="effectiveDate" className="mt-1 h-11 w-full border bg-background px-3" /></label><label className="block sm:col-span-2"><span className="text-sm font-medium">Alasan</span><textarea required name="reason" maxLength={1000} className="mt-1 min-h-24 w-full border bg-background p-3" /></label><button className="min-h-11 rounded-full bg-primary px-4 text-primary-foreground sm:col-span-2 sm:justify-self-start">{current ? "Ganti Kepala Sekolah" : "Tetapkan Kepala Sekolah"}</button></form> : null}
  </section>;
}
