import { MasterDataFormDialog } from "@/components/master-data/master-data-form-dialog";
import { archiveAcademicYearAction, createAcademicYearAction, transitionAcademicYearAction } from "@/app/(tenant)/[domain]/(authenticated)/master/tahun-ajaran/actions";
import { MasterDataWorkspace } from "@/components/master-data/master-data-workspace";
import { createAcademicYearService } from "@/lib/academic-year";
import { academicYearStore } from "@/lib/academic-year-data";
import { normalizeMasterDataQuery, type MasterDataSearchParams } from "@/lib/master-data-workspace";
import { enforceMasterDataAccess } from "@/lib/tenant-master-data-route-access";

const lifecycleLabels = { draft: "Draft", active: "Aktif", closed: "Ditutup", cancelled: "Dibatalkan" } as const;
const semesterLabels = { pending: "Belum Aktif", active: "Aktif", completed: "Selesai" } as const;
export default async function AcademicYearsPage({ params, searchParams }: { params: Promise<{ domain: string }>; searchParams: Promise<MasterDataSearchParams & { result?: string }> }) {
  const [{ domain }, raw] = await Promise.all([params, searchParams]);
  const principal = await enforceMasterDataAccess(domain, "read");
  const service = createAcademicYearService({ store: academicYearStore });
  const years = await service.list(principal);
  const query = normalizeMasterDataQuery(raw, { filters: {}, sorts: ["name-desc", "name-asc"] });
  const filtered = years.filter((year) => (query.archive === "all" || year.archived === (query.archive === "archived")) && year.label.toLocaleLowerCase("id-ID").includes(query.search.toLocaleLowerCase("id-ID"))).sort((a, b) => query.sort === "name-asc" ? a.startDate.localeCompare(b.startDate) : b.startDate.localeCompare(a.startDate));
  const selected = years.find((year) => year.id === query.selected && year.tenantId === principal.tenantId);
  const pageItems = filtered.slice((query.page - 1) * query.pageSize, query.page * query.pageSize);
  const basePath = `/${domain}/master/tahun-ajaran`;
  const writable = principal.capabilities.write;
  const effectiveDate = new Date().toISOString().slice(0, 10);
  const detail = selected ? <div className="space-y-5"><dl className="grid gap-3 sm:grid-cols-2"><div><dt className="text-sm text-muted-foreground">Lifecycle</dt><dd>{lifecycleLabels[selected.lifecycle]}</dd></div><div><dt className="text-sm text-muted-foreground">Arsip</dt><dd>{selected.archived ? "Diarsipkan" : "Aktif"}</dd></div><div><dt className="text-sm text-muted-foreground">Rentang</dt><dd>{selected.startDate} – {selected.endDate}</dd></div><div><dt className="text-sm text-muted-foreground">Semester aktif</dt><dd>{selected.semesters.find((semester) => semester.status === "active")?.kind === "odd" ? "Ganjil" : selected.semesters.some((semester) => semester.status === "active") ? "Genap" : "Tidak ada"}</dd></div></dl><div className="grid gap-3 sm:grid-cols-2">{selected.semesters.map((semester) => <section className="rounded-lg border p-3" key={semester.id}><h3 className="font-medium">Semester {semester.kind === "odd" ? "Ganjil" : "Genap"}</h3><p className="text-sm">{semester.startDate} – {semester.endDate}</p><p className="text-sm">Status: {semesterLabels[semester.status]}</p></section>)}</div>{writable ? <div className="flex flex-wrap gap-2">{!selected.archived && selected.lifecycle === "draft" ? <><ActionForm domain={domain} id={selected.id} action="activate" label="Aktifkan" effectiveDate={effectiveDate} /><ActionForm domain={domain} id={selected.id} action="cancel" label="Batalkan" effectiveDate={effectiveDate} /></> : null}{!selected.archived && selected.lifecycle === "active" && selected.semesters[0].status === "active" ? <ActionForm domain={domain} id={selected.id} action="start-even" label="Mulai Semester Genap" effectiveDate={effectiveDate} /> : null}{!selected.archived && selected.lifecycle === "active" && selected.semesters[1].status === "active" ? <ActionForm domain={domain} id={selected.id} action="close" label="Tutup Tahun Ajaran" effectiveDate={effectiveDate} /> : null}{["closed", "cancelled"].includes(selected.lifecycle) ? <ArchiveForm domain={domain} id={selected.id} operation={selected.archived ? "reactivate" : "archive"} label={selected.archived ? "Aktifkan kembali arsip" : "Arsipkan"} effectiveDate={effectiveDate} /> : null}</div> : <p className="text-sm text-muted-foreground">Workspace ini hanya-baca.</p>}</div> : undefined;
  return <div className="space-y-6 p-4 md:p-6">{raw.result ? <p role="status" className="rounded-lg border p-3">{raw.result === "saved" ? "Perubahan Tahun Ajaran tersimpan." : `Perubahan ditolak: ${raw.result}.`}</p> : null}<MasterDataWorkspace title="Tahun Ajaran" description="Kelola periode dan lifecycle secara eksplisit; tanggal kalender tidak pernah mengubah status otomatis." basePath={basePath} query={query} items={pageItems.map((year) => ({ id: year.id, title: year.label, description: `${year.startDate} – ${year.endDate}`, lifecycle: lifecycleLabels[year.lifecycle], archived: year.archived }))} total={filtered.length} detail={detail}>{writable ? <MasterDataFormDialog title="Buat Tahun Ajaran"><form action={createAcademicYearAction.bind(null, domain)} className="mt-4 grid gap-3 sm:grid-cols-2"><Field name="label" label="Label" type="text" /><Field name="startDate" label="Mulai Tahun Ajaran" /><Field name="endDate" label="Selesai Tahun Ajaran" /><Field name="oddStartDate" label="Mulai Semester Ganjil" /><Field name="oddEndDate" label="Selesai Semester Ganjil" /><Field name="evenStartDate" label="Mulai Semester Genap" /><Field name="evenEndDate" label="Selesai Semester Genap" /><button className="rounded-full bg-primary px-4 py-2 text-primary-foreground sm:col-span-2">Simpan Draft</button></form></MasterDataFormDialog> : null}</MasterDataWorkspace></div>;
}
function Field({ name, label, type = "date" }: { name: string; label: string; type?: string }) { return <label><span className="text-sm font-medium">{label}</span><input required name={name} type={type} className="mt-1 h-10 w-full border bg-background px-3" /></label>; }
function ActionForm({ domain, id, action, label, effectiveDate }: { domain: string; id: string; action: string; label: string; effectiveDate: string }) { return <form action={transitionAcademicYearAction.bind(null, domain)} className="flex gap-2"><input type="hidden" name="id" value={id} /><input type="hidden" name="action" value={action} /><input aria-label="Tanggal efektif" name="effectiveDate" type="date" defaultValue={effectiveDate} required className="border px-2" /><button className="rounded-full border px-3 py-2">{label}</button></form>; }
function ArchiveForm({ domain, id, operation, label, effectiveDate }: { domain: string; id: string; operation: string; label: string; effectiveDate: string }) { return <form action={archiveAcademicYearAction.bind(null, domain)} className="flex gap-2"><input type="hidden" name="id" value={id} /><input type="hidden" name="operation" value={operation} /><input aria-label="Tanggal efektif arsip" name="effectiveDate" type="date" defaultValue={effectiveDate} required className="border px-2" /><button className="rounded-full border px-3 py-2">{label}</button></form>; }
