import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test, { after } from "node:test";
import mysql from "mysql2/promise";
import { closeDatabasePool } from "@/db";
import { createClassMembershipService } from "@/lib/class-membership";
import { classMembershipStore } from "@/lib/class-membership-data";
import type { MasterDataPrincipal } from "@/lib/tenant-master-data-access";
const url = process.env.DATABASE_URL, mysqlTest = url ? test : test.skip;
after(() => closeDatabasePool());
mysqlTest("real MySQL serializes concurrent membership and Wali Kelas claims", async () => {
 const c = await mysql.createConnection(url!), id = () => randomUUID(), x = { tenant:id(), admin:id(), provider:id(), binding:id(), app:id(), year:id(), sem1:id(), sem2:id(), g1:id(), g2:id(), sp1:id(), sp2:id(), sp3:id(), student:id(), t1:id(), t2:id() }, npsn=String(Math.floor(10_000_000+Math.random()*90_000_000));
 try {
  await c.execute("INSERT INTO `user` (`id`,`name`,`email`,`email_verified`,`created_at`,`updated_at`) VALUES (?, 'Admin', ?, false,NOW(3),NOW(3)),(?, 'Provider', ?, false,NOW(3),NOW(3))",[x.admin,`${x.admin}@test.invalid`,x.provider,`${x.provider}@test.invalid`]); await c.execute("INSERT INTO provider_admin (user_id,created_at) VALUES (?,NOW(3))",[x.provider]); await c.execute("INSERT INTO applicant_school_binding (id,user_id,canonical_npsn,created_at) VALUES (?,?,?,NOW(3))",[x.binding,x.admin,npsn]); await c.execute("INSERT INTO simas_application (id,school_name,npsn,education_level,address,contact_name,contact_position,contact_email,contact_whatsapp,status,submitted_at,owner_user_id,binding_id,attempt_number,idempotency_key,payload_hash) VALUES (?,'Uji',?,'SMA','A','K','O',?,'0812','pending',NOW(3),?,?,1,?,REPEAT('a',64))",[x.app,npsn,`${x.app}@test.invalid`,x.admin,x.binding,id()]); await c.execute("INSERT INTO tenant (id,name,domain,npsn,source_application_id,approved_at,operational_status,created_at,updated_at) VALUES (?,'Uji',?,?,?,NOW(3),'active',NOW(3),NOW(3))",[x.tenant,`rel-${id()}`,npsn,x.app]); await c.execute("UPDATE simas_application SET status='approved',decided_at=NOW(3),decided_by_provider_admin_id=?,approved_tenant_id=? WHERE id=?",[x.provider,x.tenant,x.app]); await c.execute("UPDATE user SET tenant_id=?,tenant_role='school-admin' WHERE id=?",[x.tenant,x.admin]);
  await c.execute("INSERT INTO academic_year (id,tenant_id,label,start_date,end_date,lifecycle,archived,version,created_at,updated_at) VALUES (?,?,'2026/27','2026-07-01','2027-06-30','active',false,1,NOW(3),NOW(3))",[x.year,x.tenant]); await c.execute("INSERT INTO academic_semester (id,tenant_id,academic_year_id,kind,start_date,end_date,status) VALUES (?,?,?,'odd','2026-07-01','2026-12-31','active'),(?,?,?,'even','2027-01-01','2027-06-30','pending')",[x.sem1,x.tenant,x.year,x.sem2,x.tenant,x.year]); for (const [gid,name] of [[x.g1,"A"],[x.g2,"B"]]) await c.execute("INSERT INTO class_group (id,tenant_id,academic_year_id,education_level,grade,group_name,normalized_group_name,lifecycle,archived,version,created_at,updated_at) VALUES (?,?,?,'SMA',10,?,?,'active',false,1,NOW(3),NOW(3))",[gid,x.tenant,x.year,name,name.toLowerCase()]);
  for (const [pid,name] of [[x.sp1,"Siswa"],[x.sp2,"Guru 1"],[x.sp3,"Guru 2"]]) await c.execute("INSERT INTO school_person (id,tenant_id,full_name,normalized_name,birth_place,normalized_birth_place,birth_date,gender,street,archived,version,created_at,updated_at) VALUES (?,?,?,?, 'Palu','palu','2000-01-01','female','A',false,1,NOW(3),NOW(3))",[pid,x.tenant,name,name.toLowerCase()]); await c.execute("INSERT INTO student_profile (id,tenant_id,person_id,nis,normalized_nis,entry_date,status,archived,version,created_at,updated_at) VALUES (?,?,?,'001','001','2026-07-01','active',false,1,NOW(3),NOW(3))",[x.student,x.tenant,x.sp1]); for (const [tid,pid,no] of [[x.t1,x.sp2,"G1"],[x.t2,x.sp3,"G2"]]) await c.execute("INSERT INTO teacher_profile (id,tenant_id,person_id,teacher_number,normalized_teacher_number,employment_type,service_start_date,status,archived,version,created_at,updated_at) VALUES (?,?,?,?,?,'civil-servant','2020-01-01','active',false,1,NOW(3),NOW(3))",[tid,x.tenant,pid,no,no.toLowerCase()]);
  const p:MasterDataPrincipal={userId:x.admin,tenantId:x.tenant,role:"school-admin",capabilities:{read:true,write:true,downloadTemplate:true}}, s=createClassMembershipService({store:classMembershipStore}); const members=await Promise.all([s.addMembership(p,{studentId:x.student,classGroupId:x.g1,effectiveDate:"2026-07-01",reason:"A"}),s.addMembership(p,{studentId:x.student,classGroupId:x.g2,effectiveDate:"2026-07-01",reason:"B"})]); assert.equal(members.filter(v=>v.ok).length,1); assert.equal(members.filter(v=>!v.ok&&v.code==="active-membership-exists").length,1); const homes=await Promise.all([s.assignHomeroom(p,{teacherId:x.t1,classGroupId:x.g1,effectiveDate:"2026-07-01",reason:"A"}),s.assignHomeroom(p,{teacherId:x.t2,classGroupId:x.g1,effectiveDate:"2026-07-01",reason:"B"})]); assert.equal(homes.filter(v=>v.ok).length,2); const [counts]=await c.query<mysql.RowDataPacket[]>("SELECT (SELECT COUNT(*) FROM class_membership WHERE tenant_id=? AND ended_at IS NULL AND planned=false) memberships,(SELECT COUNT(*) FROM homeroom_assignment WHERE tenant_id=? AND class_group_id=? AND ended_at IS NULL) homerooms,(SELECT COUNT(*) FROM homeroom_assignment WHERE tenant_id=? AND class_group_id=? ) homeroom_history",[x.tenant,x.tenant,x.g1,x.tenant,x.g1]); assert.deepEqual({...counts[0]},{memberships:1,homerooms:1,homeroom_history:2});
 } finally { await c.execute("SET FOREIGN_KEY_CHECKS=0"); for(const table of ["class_relationship_event","homeroom_assignment","class_membership","teacher_profile","student_profile","school_person","class_group","academic_semester","academic_year"]) await c.execute(`DELETE FROM \`${table}\` WHERE tenant_id=?`,[x.tenant]); await c.execute("UPDATE user SET tenant_id=NULL,tenant_role=NULL WHERE id=?",[x.admin]); await c.execute("DELETE FROM tenant WHERE id=?",[x.tenant]); await c.execute("DELETE FROM simas_application WHERE id=?",[x.app]); await c.execute("DELETE FROM applicant_school_binding WHERE id=?",[x.binding]); await c.execute("DELETE FROM provider_admin WHERE user_id=?",[x.provider]); await c.execute("DELETE FROM user WHERE id IN (?,?)",[x.admin,x.provider]); await c.execute("SET FOREIGN_KEY_CHECKS=1"); await c.end(); }
});
