import assert from "node:assert/strict";
import test from "node:test";
import { createClassMembershipService, type ClassMembership, type ClassMembershipStore, type HomeroomAssignment, type RelationshipReferenceData } from "@/lib/class-membership";
import type { MasterDataPrincipal } from "@/lib/tenant-master-data-access";

const principal: MasterDataPrincipal = { userId: "admin-1", tenantId: "tenant-1", role: "school-admin", capabilities: { read: true, write: true, downloadTemplate: true } };
function fixture() {
  const memberships: ClassMembership[] = [], homerooms: HomeroomAssignment[] = [], events: unknown[] = [];
  const references: RelationshipReferenceData = {
    students: [{ id: "student-1", tenantId: "tenant-1", name: "Aisyah", active: true, archived: false }, { id: "student-other", tenantId: "tenant-2", name: "Lain", active: true, archived: false }],
    teachers: [{ id: "teacher-1", tenantId: "tenant-1", name: "Ibu Sari", active: true, archived: false }, { id: "teacher-2", tenantId: "tenant-1", name: "Pak Budi", active: true, archived: false }],
    groups: [{ id: "group-active", tenantId: "tenant-1", academicYearId: "year-active", name: "10 A", lifecycle: "active", archived: false }, { id: "group-transfer", tenantId: "tenant-1", academicYearId: "year-active", name: "10 B", lifecycle: "active", archived: false }, { id: "group-draft", tenantId: "tenant-1", academicYearId: "year-draft", name: "11 A", lifecycle: "draft", archived: false }],
    years: [{ id: "year-active", tenantId: "tenant-1", lifecycle: "active", archived: false }, { id: "year-draft", tenantId: "tenant-1", lifecycle: "draft", archived: false }],
  };
  const store: ClassMembershipStore = { listMemberships: async (tenantId) => memberships.filter((x) => x.tenantId === tenantId), listHomerooms: async (tenantId) => homerooms.filter((x) => x.tenantId === tenantId), references: async () => references, async transaction(tenantId, work) { const m = structuredClone(memberships), h = structuredClone(homerooms), e = structuredClone(events); try { return await work({ listMemberships: async () => memberships.filter((x) => x.tenantId === tenantId), listHomerooms: async () => homerooms.filter((x) => x.tenantId === tenantId), references: async () => references, appendMembership: async (x) => { memberships.push(structuredClone(x)); }, closeMembership: async (id, endedAt) => { const i = memberships.findIndex((x) => x.tenantId === tenantId && x.id === id && x.endedAt === null); if (i < 0) return false; memberships[i] = { ...memberships[i], endedAt }; return true; }, appendHomeroom: async (x) => { homerooms.push(structuredClone(x)); }, closeHomeroom: async (id, endedAt) => { const i = homerooms.findIndex((x) => x.tenantId === tenantId && x.id === id && x.endedAt === null); if (i < 0) return false; homerooms[i] = { ...homerooms[i], endedAt }; return true; }, appendEvent: async (x) => { events.push(structuredClone(x)); } }); } catch (error) { memberships.splice(0, memberships.length, ...m); homerooms.splice(0, homerooms.length, ...h); events.splice(0, events.length, ...e); throw error; } } };
  return { store, memberships, homerooms, events };
}
function service(store: ClassMembershipStore) { let n = 0; return createClassMembershipService({ store, id: () => `id-${++n}`, now: () => new Date("2026-07-01T00:00:00Z") }); }

test("adds one active membership and one planned Draft-year membership without closing current", async () => { const f = fixture(), s = service(f.store); assert.equal((await s.addMembership(principal, { studentId: "student-1", classGroupId: "group-active", effectiveDate: "2026-07-01", reason: "Penempatan awal" })).ok, true); assert.equal((await s.addMembership(principal, { studentId: "student-1", classGroupId: "group-draft", effectiveDate: "2027-07-01", reason: "Rencana tahun depan" })).ok, true); assert.deepEqual(f.memberships.map((x) => [x.planned, x.endedAt]), [[false, null], [true, null]]); assert.deepEqual(await s.addMembership(principal, { studentId: "student-1", classGroupId: "group-transfer", effectiveDate: "2026-08-01", reason: "Duplikat" }), { ok: false, code: "active-membership-exists" }); });

test("transfers atomically at one effective date and preserves both history rows", async () => { const f = fixture(), s = service(f.store); await s.addMembership(principal, { studentId: "student-1", classGroupId: "group-active", effectiveDate: "2026-07-01", reason: "Awal" }); const moved = await s.transfer(principal, { studentId: "student-1", toClassGroupId: "group-transfer", effectiveDate: "2026-08-15", reason: "Pindah Rombel" }); assert.equal(moved.ok, true); assert.equal(f.memberships[0].endedAt, "2026-08-15"); assert.equal(f.memberships[1].startedAt, "2026-08-15"); assert.equal(f.memberships.length, 2); assert.equal(f.events.length, 2); });

test("never promotes automatically and rejects cross-Tenant or inactive profiles", async () => { const f = fixture(), s = service(f.store); assert.deepEqual(await s.addMembership(principal, { studentId: "student-other", classGroupId: "group-active", effectiveDate: "2026-07-01", reason: "Tidak sah" }), { ok: false, code: "invalid-student" }); assert.equal(f.memberships.length, 0); assert.equal("promote" in s, false); });

test("assigns and replaces Wali Kelas while limiting teacher to one Rombel per year", async () => { const f = fixture(), s = service(f.store); assert.equal((await s.assignHomeroom(principal, { teacherId: "teacher-1", classGroupId: "group-active", effectiveDate: "2026-07-01", reason: "Penugasan" })).ok, true); assert.deepEqual(await s.assignHomeroom(principal, { teacherId: "teacher-1", classGroupId: "group-transfer", effectiveDate: "2026-07-01", reason: "Ganda" }), { ok: false, code: "teacher-year-conflict" }); assert.equal((await s.assignHomeroom(principal, { teacherId: "teacher-2", classGroupId: "group-active", effectiveDate: "2026-08-01", reason: "Penggantian" })).ok, true); assert.equal(f.homerooms[0].endedAt, "2026-08-01"); assert.equal(f.homerooms[1].teacherId, "teacher-2"); assert.equal(f.events.length, 2); });
