import type { MasterDataPrincipal } from "@/lib/tenant-master-data-access";

export const CLASS_GROUP_LIFECYCLES = ["draft", "active", "closed", "cancelled"] as const;
export const CLASS_GROUP_EDUCATION_LEVELS = ["SD", "SMP", "SMA", "SMK"] as const;
export type ClassGroupLifecycle = (typeof CLASS_GROUP_LIFECYCLES)[number];
export type ClassGroupEducationLevel = (typeof CLASS_GROUP_EDUCATION_LEVELS)[number];
export type ClassGroup = Readonly<{ id: string; tenantId: string; academicYearId: string; educationLevel: ClassGroupEducationLevel; grade: number; groupName: string; normalizedGroupName: string; code: string | null; normalizedCode: string | null; capacity: number | null; primaryLocationId: string | null; lifecycle: ClassGroupLifecycle; archived: boolean; archivedAt: Date | null; archiveReason: string | null; version: number; createdAt: Date; updatedAt: Date }>;
export type ClassGroupReferenceData = Readonly<{ academicYears: readonly Readonly<{ id: string; tenantId: string; label: string; lifecycle: "draft" | "active" | "closed" | "cancelled"; archived: boolean }>[]; locations: readonly Readonly<{ id: string; tenantId: string; name: string; archived: boolean }>[] }>;
export type ClassGroupBlocker = Readonly<{ id: string; tenantId: string; classGroupId: string; label: string; active: boolean }>;
export type ClassGroupHistory = Readonly<{ id: string; tenantId: string; classGroupId: string; actorUserId: string; operation: string; fromVersion: number; toVersion: number; reason: string; occurredAt: Date }>;
export interface ClassGroupTransaction { list(): Promise<ClassGroup[]>; references(): Promise<ClassGroupReferenceData>; blockers(id: string): Promise<ClassGroupBlocker[]>; save(group: ClassGroup, expectedVersion: number): Promise<boolean>; appendHistory(event: ClassGroupHistory): Promise<void> }
export interface ClassGroupStore { list(tenantId: string): Promise<ClassGroup[]>; references(tenantId: string): Promise<ClassGroupReferenceData>; transaction<T>(tenantId: string, work: (transaction: ClassGroupTransaction) => Promise<T>): Promise<T> }
export type ClassGroupInput = Readonly<{ academicYearId: string; educationLevel: ClassGroupEducationLevel; grade: number; groupName: string; code?: string | null; capacity?: number | null; primaryLocationId?: string | null }>;
type FailureCode = "invalid-input" | "invalid-academic-year" | "invalid-location" | "duplicate-name" | "duplicate-code" | "not-found" | "conflict" | "archived" | "immutable-academic-context" | "invalid-transition" | "not-terminal" | "relationship-blocked" | "not-archived";
const failure = (code: FailureCode) => ({ ok: false, code } as const);
const normalize = (value: string) => value.trim().replace(/\s+/g, " ").toLocaleLowerCase("id-ID");
function validGrade(level: ClassGroupEducationLevel, grade: number) { return Number.isInteger(grade) && (level === "SD" ? grade >= 1 && grade <= 6 : level === "SMP" ? grade >= 7 && grade <= 9 : grade >= 10 && grade <= 12); }
function prepare(input: ClassGroupInput) {
  const groupName = input.groupName.trim().replace(/\s+/g, " "), code = input.code?.trim().replace(/\s+/g, " ") || null, capacity = input.capacity ?? null, primaryLocationId = input.primaryLocationId || null;
  if (!input.academicYearId || !CLASS_GROUP_EDUCATION_LEVELS.includes(input.educationLevel) || !validGrade(input.educationLevel, input.grade) || !groupName || groupName.length > 100 || (code?.length ?? 0) > 30 || (capacity !== null && (!Number.isInteger(capacity) || capacity < 1 || capacity > 999))) return null;
  return { academicYearId: input.academicYearId, educationLevel: input.educationLevel, grade: input.grade, groupName, normalizedGroupName: normalize(groupName), code, normalizedCode: code ? normalize(code) : null, capacity, primaryLocationId };
}
function validateReferences(tenantId: string, value: ReturnType<typeof prepare> & {}, references: ClassGroupReferenceData) {
  const year = references.academicYears.find((item) => item.id === value.academicYearId && item.tenantId === tenantId && !item.archived && ["draft", "active"].includes(item.lifecycle));
  if (!year) return "invalid-academic-year" as const;
  if (value.primaryLocationId && !references.locations.some((item) => item.id === value.primaryLocationId && item.tenantId === tenantId && !item.archived)) return "invalid-location" as const;
}
function validateLocation(tenantId: string, locationId: string | null, references: ClassGroupReferenceData) { return locationId && !references.locations.some((item) => item.id === locationId && item.tenantId === tenantId && !item.archived) ? "invalid-location" as const : undefined; }
function duplicate(value: ReturnType<typeof prepare> & {}, all: ClassGroup[], exclude?: string) { if (all.some((item) => item.id !== exclude && item.academicYearId === value.academicYearId && item.normalizedGroupName === value.normalizedGroupName)) return "duplicate-name" as const; if (value.normalizedCode && all.some((item) => item.id !== exclude && item.normalizedCode === value.normalizedCode)) return "duplicate-code" as const; }

export function createClassGroupService(dependencies: { store: ClassGroupStore; id?: () => string; now?: () => Date }) {
  const id = dependencies.id ?? (() => crypto.randomUUID()), now = dependencies.now ?? (() => new Date());
  return {
    list(principal: MasterDataPrincipal) { return dependencies.store.list(principal.tenantId); },
    references(principal: MasterDataPrincipal) { return dependencies.store.references(principal.tenantId); },
    create(principal: MasterDataPrincipal, input: ClassGroupInput) {
      const value = prepare(input); if (!value) return Promise.resolve(failure("invalid-input"));
      return dependencies.store.transaction(principal.tenantId, async (tx) => { const all = await tx.list(), referenceFailure = validateReferences(principal.tenantId, value, await tx.references()), duplicateFailure = duplicate(value, all); if (referenceFailure) return failure(referenceFailure); if (duplicateFailure) return failure(duplicateFailure); const timestamp = now(); const record: ClassGroup = { id: id(), tenantId: principal.tenantId, ...value, lifecycle: "draft", archived: false, archivedAt: null, archiveReason: null, version: 1, createdAt: timestamp, updatedAt: timestamp }; if (!await tx.save(record, 0)) return failure("conflict"); await tx.appendHistory({ id: id(), tenantId: principal.tenantId, classGroupId: record.id, actorUserId: principal.userId, operation: "created", fromVersion: 0, toVersion: 1, reason: "Rombongan Belajar dibuat", occurredAt: timestamp }); return { ok: true, record } as const; });
    },
    edit(principal: MasterDataPrincipal, classGroupId: string, input: ClassGroupInput, expectedVersion: number) {
      const value = prepare(input); if (!value) return Promise.resolve(failure("invalid-input"));
      return dependencies.store.transaction(principal.tenantId, async (tx) => { const all = await tx.list(), current = all.find((item) => item.id === classGroupId); if (!current) return failure("not-found"); if (current.version !== expectedVersion) return failure("conflict"); if (current.archived) return failure("archived"); if (current.lifecycle !== "draft" && (current.academicYearId !== value.academicYearId || current.educationLevel !== value.educationLevel || current.grade !== value.grade)) return failure("immutable-academic-context"); const references = await tx.references(), referenceFailure = current.lifecycle === "draft" ? validateReferences(principal.tenantId, value, references) : validateLocation(principal.tenantId, value.primaryLocationId, references), duplicateFailure = duplicate(value, all, current.id); if (referenceFailure) return failure(referenceFailure); if (duplicateFailure) return failure(duplicateFailure); const record = { ...current, ...value, version: current.version + 1, updatedAt: now() }; if (!await tx.save(record, expectedVersion)) return failure("conflict"); await tx.appendHistory({ id: id(), tenantId: principal.tenantId, classGroupId, actorUserId: principal.userId, operation: "edited", fromVersion: expectedVersion, toVersion: record.version, reason: "Data Rombongan Belajar diubah", occurredAt: record.updatedAt }); return { ok: true, record } as const; });
    },
    transition(principal: MasterDataPrincipal, classGroupId: string, action: "activate" | "close" | "cancel", input: { expectedVersion: number; reason: string }) { return dependencies.store.transaction(principal.tenantId, async (tx) => { const current = (await tx.list()).find((item) => item.id === classGroupId); if (!current) return failure("not-found"); if (current.version !== input.expectedVersion) return failure("conflict"); if (current.archived || !input.reason.trim()) return failure("invalid-input"); const lifecycle: ClassGroupLifecycle | null = action === "activate" && current.lifecycle === "draft" ? "active" : action === "close" && current.lifecycle === "active" ? "closed" : action === "cancel" && current.lifecycle === "draft" ? "cancelled" : null; if (!lifecycle) return failure("invalid-transition"); const record = { ...current, lifecycle, version: current.version + 1, updatedAt: now() }; if (!await tx.save(record, input.expectedVersion)) return failure("conflict"); await tx.appendHistory({ id: id(), tenantId: principal.tenantId, classGroupId, actorUserId: principal.userId, operation: action, fromVersion: current.version, toVersion: record.version, reason: input.reason.trim(), occurredAt: record.updatedAt }); return { ok: true, record } as const; }); },
    archive(principal: MasterDataPrincipal, classGroupId: string, input: { expectedVersion: number; reason: string }) { return dependencies.store.transaction(principal.tenantId, async (tx) => { const current = (await tx.list()).find((item) => item.id === classGroupId); if (!current) return failure("not-found"); if (current.version !== input.expectedVersion) return failure("conflict"); if (!input.reason.trim()) return failure("invalid-input"); if (!(["closed", "cancelled"] as ClassGroupLifecycle[]).includes(current.lifecycle)) return failure("not-terminal"); const blockers = await tx.blockers(classGroupId); if (blockers.length) return { ok: false, code: "relationship-blocked", blockers } as const; const timestamp = now(), record = { ...current, archived: true, archivedAt: timestamp, archiveReason: input.reason.trim(), version: current.version + 1, updatedAt: timestamp }; if (!await tx.save(record, input.expectedVersion)) return failure("conflict"); await tx.appendHistory({ id: id(), tenantId: principal.tenantId, classGroupId, actorUserId: principal.userId, operation: "archived", fromVersion: current.version, toVersion: record.version, reason: input.reason.trim(), occurredAt: timestamp }); return { ok: true, record } as const; }); },
    reactivate(principal: MasterDataPrincipal, classGroupId: string, input: { expectedVersion: number; reason: string }) { return dependencies.store.transaction(principal.tenantId, async (tx) => { const all = await tx.list(), current = all.find((item) => item.id === classGroupId); if (!current) return failure("not-found"); if (current.version !== input.expectedVersion) return failure("conflict"); if (!current.archived) return failure("not-archived"); if (!input.reason.trim()) return failure("invalid-input"); const locationFailure = validateLocation(principal.tenantId, current.primaryLocationId, await tx.references()); if (locationFailure) return failure(locationFailure); const duplicateFailure = duplicate(current, all, current.id); if (duplicateFailure) return failure(duplicateFailure); const timestamp = now(), record = { ...current, archived: false, archivedAt: null, archiveReason: null, version: current.version + 1, updatedAt: timestamp }; if (!await tx.save(record, input.expectedVersion)) return failure("conflict"); await tx.appendHistory({ id: id(), tenantId: principal.tenantId, classGroupId, actorUserId: principal.userId, operation: "reactivated", fromVersion: current.version, toVersion: record.version, reason: input.reason.trim(), occurredAt: timestamp }); return { ok: true, record } as const; }); },
  };
}
