import type { MasterDataPrincipal } from "@/lib/tenant-master-data-access";

export type ClassMembership = Readonly<{ id: string; tenantId: string; studentId: string; classGroupId: string; academicYearId: string; planned: boolean; startedAt: string; endedAt: string | null; reason: string; createdByUserId: string; createdAt: Date }>;
export type HomeroomAssignment = Readonly<{ id: string; tenantId: string; teacherId: string; classGroupId: string; academicYearId: string; startedAt: string; endedAt: string | null; reason: string; createdByUserId: string; createdAt: Date }>;
export type RelationshipReferenceData = Readonly<{ students: readonly { id: string; tenantId: string; name: string; active: boolean; archived: boolean }[]; teachers: readonly { id: string; tenantId: string; name: string; active: boolean; archived: boolean }[]; groups: readonly { id: string; tenantId: string; academicYearId: string; name: string; lifecycle: "draft" | "active" | "closed" | "cancelled"; archived: boolean }[]; years: readonly { id: string; tenantId: string; lifecycle: "draft" | "active" | "closed" | "cancelled"; archived: boolean }[] }>;
export type RelationshipEvent = Readonly<{ id: string; tenantId: string; kind: "membership" | "homeroom"; relationshipId: string; actorUserId: string; operation: "opened" | "transferred" | "assigned" | "replaced"; effectiveDate: string; reason: string; occurredAt: Date }>;
export interface ClassMembershipTransaction { listMemberships(): Promise<ClassMembership[]>; listHomerooms(): Promise<HomeroomAssignment[]>; references(): Promise<RelationshipReferenceData>; appendMembership(value: ClassMembership): Promise<void>; closeMembership(id: string, endedAt: string): Promise<boolean>; appendHomeroom(value: HomeroomAssignment): Promise<void>; closeHomeroom(id: string, endedAt: string): Promise<boolean>; appendEvent(value: RelationshipEvent): Promise<void> }
export interface ClassMembershipStore { listMemberships(tenantId: string): Promise<ClassMembership[]>; listHomerooms(tenantId: string): Promise<HomeroomAssignment[]>; references(tenantId: string): Promise<RelationshipReferenceData>; transaction<T>(tenantId: string, work: (transaction: ClassMembershipTransaction) => Promise<T>): Promise<T> }
type FailureCode = "invalid-input" | "invalid-student" | "invalid-teacher" | "invalid-class-group" | "active-membership-exists" | "planned-membership-exists" | "no-active-membership" | "same-class-group" | "class-group-occupied" | "teacher-year-conflict" | "conflict";
const failure = (code: FailureCode) => ({ ok: false, code } as const);
const validDate = (value: string) => { if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return false; const date = new Date(`${value}T00:00:00Z`); return !Number.isNaN(date.valueOf()) && date.toISOString().slice(0, 10) === value; };

export function createClassMembershipService(dependencies: { store: ClassMembershipStore; id?: () => string; now?: () => Date }) {
  const id = dependencies.id ?? (() => crypto.randomUUID()), now = dependencies.now ?? (() => new Date());
  const event = (tenantId: string, actorUserId: string, kind: RelationshipEvent["kind"], relationshipId: string, operation: RelationshipEvent["operation"], effectiveDate: string, reason: string): RelationshipEvent => ({ id: id(), tenantId, actorUserId, kind, relationshipId, operation, effectiveDate, reason, occurredAt: now() });
  return {
    listMemberships: (principal: MasterDataPrincipal) => dependencies.store.listMemberships(principal.tenantId),
    listHomerooms: (principal: MasterDataPrincipal) => dependencies.store.listHomerooms(principal.tenantId),
    references: (principal: MasterDataPrincipal) => dependencies.store.references(principal.tenantId),
    addMembership(principal: MasterDataPrincipal, input: { studentId: string; classGroupId: string; effectiveDate: string; reason: string }) { return dependencies.store.transaction(principal.tenantId, async (tx) => {
      const reason = input.reason.trim(); if (!reason || !validDate(input.effectiveDate)) return failure("invalid-input");
      const refs = await tx.references(), student = refs.students.find((x) => x.id === input.studentId && x.tenantId === principal.tenantId && x.active && !x.archived), group = refs.groups.find((x) => x.id === input.classGroupId && x.tenantId === principal.tenantId && !x.archived && ["draft", "active"].includes(x.lifecycle));
      if (!student) return failure("invalid-student"); if (!group) return failure("invalid-class-group"); const year = refs.years.find((x) => x.id === group.academicYearId && x.tenantId === principal.tenantId && !x.archived); if (!year || year.lifecycle !== group.lifecycle) return failure("invalid-class-group");
      const planned = year.lifecycle === "draft", current = (await tx.listMemberships()).filter((x) => x.studentId === student.id && x.endedAt === null); if (current.some((x) => x.planned === planned)) return failure(planned ? "planned-membership-exists" : "active-membership-exists");
      const record: ClassMembership = { id: id(), tenantId: principal.tenantId, studentId: student.id, classGroupId: group.id, academicYearId: group.academicYearId, planned, startedAt: input.effectiveDate, endedAt: null, reason, createdByUserId: principal.userId, createdAt: now() }; await tx.appendMembership(record); await tx.appendEvent(event(principal.tenantId, principal.userId, "membership", record.id, "opened", input.effectiveDate, reason)); return { ok: true, record } as const;
    }); },
    transfer(principal: MasterDataPrincipal, input: { studentId: string; toClassGroupId: string; effectiveDate: string; reason: string }) { return dependencies.store.transaction(principal.tenantId, async (tx) => {
      const reason = input.reason.trim(); if (!reason || !validDate(input.effectiveDate)) return failure("invalid-input"); const refs = await tx.references(), student = refs.students.find((x) => x.id === input.studentId && x.tenantId === principal.tenantId && x.active && !x.archived), group = refs.groups.find((x) => x.id === input.toClassGroupId && x.tenantId === principal.tenantId && x.lifecycle === "active" && !x.archived); if (!student) return failure("invalid-student"); if (!group) return failure("invalid-class-group"); const old = (await tx.listMemberships()).find((x) => x.studentId === student.id && !x.planned && x.endedAt === null); if (!old) return failure("no-active-membership"); if (old.classGroupId === group.id) return failure("same-class-group"); if (input.effectiveDate < old.startedAt) return failure("invalid-input"); if (!await tx.closeMembership(old.id, input.effectiveDate)) return failure("conflict"); const record: ClassMembership = { id: id(), tenantId: principal.tenantId, studentId: student.id, classGroupId: group.id, academicYearId: group.academicYearId, planned: false, startedAt: input.effectiveDate, endedAt: null, reason, createdByUserId: principal.userId, createdAt: now() }; await tx.appendMembership(record); await tx.appendEvent(event(principal.tenantId, principal.userId, "membership", record.id, "transferred", input.effectiveDate, reason)); return { ok: true, record } as const;
    }); },
    assignHomeroom(principal: MasterDataPrincipal, input: { teacherId: string; classGroupId: string; effectiveDate: string; reason: string }) { return dependencies.store.transaction(principal.tenantId, async (tx) => {
      const reason = input.reason.trim(); if (!reason || !validDate(input.effectiveDate)) return failure("invalid-input"); const refs = await tx.references(), teacher = refs.teachers.find((x) => x.id === input.teacherId && x.tenantId === principal.tenantId && x.active && !x.archived), group = refs.groups.find((x) => x.id === input.classGroupId && x.tenantId === principal.tenantId && ["draft", "active"].includes(x.lifecycle) && !x.archived); if (!teacher) return failure("invalid-teacher"); if (!group) return failure("invalid-class-group"); const all = await tx.listHomerooms(), existing = all.find((x) => x.classGroupId === group.id && x.endedAt === null); if (all.some((x) => x.teacherId === teacher.id && x.academicYearId === group.academicYearId && x.endedAt === null && x.classGroupId !== group.id)) return failure("teacher-year-conflict"); if (existing?.teacherId === teacher.id) return failure("class-group-occupied"); if (existing && (!validDate(input.effectiveDate) || input.effectiveDate < existing.startedAt || !await tx.closeHomeroom(existing.id, input.effectiveDate))) return failure("conflict"); const record: HomeroomAssignment = { id: id(), tenantId: principal.tenantId, teacherId: teacher.id, classGroupId: group.id, academicYearId: group.academicYearId, startedAt: input.effectiveDate, endedAt: null, reason, createdByUserId: principal.userId, createdAt: now() }; await tx.appendHomeroom(record); await tx.appendEvent(event(principal.tenantId, principal.userId, "homeroom", record.id, existing ? "replaced" : "assigned", input.effectiveDate, reason)); return { ok: true, record } as const;
    }); },
  };
}
