import assert from "node:assert/strict";
import test from "node:test";
import { createExtracurricularService, type ExtracurricularState, type ExtracurricularStore } from "@/lib/extracurricular";
import type { MasterDataPrincipal } from "@/lib/tenant-master-data-access";

const principal: MasterDataPrincipal={userId:"admin-1",tenantId:"tenant-1",role:"school-admin",capabilities:{read:true,write:true,downloadTemplate:true}};
function fixture(){const state:ExtracurricularState={extracurriculars:[],groups:[],advisors:[],participants:[],years:[{id:"year-draft",tenantId:"tenant-1",label:"2026/2027",startDate:"2026-08-01",endDate:"2027-07-31",lifecycle:"draft",archived:false},{id:"year-active",tenantId:"tenant-1",label:"2025/2026",startDate:"2025-08-01",endDate:"2026-07-31",lifecycle:"active",archived:false}],people:[{id:"teacher-1",tenantId:"tenant-1",name:"Bu Rani",kind:"teacher",active:true,archived:false},{id:"staff-1",tenantId:"tenant-1",name:"Pak Budi",kind:"staff",active:true,archived:false},{id:"student-1",tenantId:"tenant-1",name:"Ayu",kind:"student",active:true,archived:false},{id:"student-2",tenantId:"tenant-1",name:"Bima",kind:"student",active:true,archived:false},{id:"foreign",tenantId:"tenant-2",name:"Asing",kind:"student",active:true,archived:false}],locations:[{id:"field",tenantId:"tenant-1",name:"Lapangan",archived:false}],events:[]};let n=0;const store:ExtracurricularStore={state:async tenantId=>{const copy=structuredClone(state);copy.extracurriculars=copy.extracurriculars.filter(x=>x.tenantId===tenantId);copy.groups=copy.groups.filter(x=>x.tenantId===tenantId);copy.advisors=copy.advisors.filter(x=>x.tenantId===tenantId);copy.participants=copy.participants.filter(x=>x.tenantId===tenantId);copy.years=copy.years.filter(x=>x.tenantId===tenantId);copy.people=copy.people.filter(x=>x.tenantId===tenantId);copy.locations=copy.locations.filter(x=>x.tenantId===tenantId);copy.events=copy.events.filter(x=>x.tenantId===tenantId);return copy},transaction:async(_tenantId,work)=>work(state)};return{state,service:createExtracurricularService({store,id:()=>`id-${++n}`,now:()=>new Date("2026-07-20T00:00:00Z")})}}
const activity={name:"Futsal",code:"futsal",description:"Latihan futsal",defaultLocationId:"field"};
const group={extracurricularId:"",academicYearId:"year-draft",name:"Futsal Putra",startDate:"2026-08-01",endDate:"2027-06-30",capacity:1,locationId:"field",scheduleText:"Jumat 15.00"};

test("creates Tenant-owned stable identities and keeps codes reserved after archive",async()=>{const f=fixture(),created=await f.service.createExtracurricular(principal,{...activity,defaultLocationId:null});assert.equal(created.ok,true);if(!created.ok)return;assert.equal(created.record.code,"FUTSAL");assert.equal((await f.service.list({...principal,tenantId:"tenant-2"})).extracurriculars.length,0);assert.equal((await f.service.archiveExtracurricular(principal,created.record.id,{expectedVersion:1,reason:"Tidak dipakai"})).ok,true);assert.deepEqual(await f.service.createExtracurricular(principal,{...activity,name:"Futsal Baru"}),{ok:false,code:"duplicate-code"})});

test("groups are contained by Tahun Ajaran and future planning requires Draft lifecycle",async()=>{const f=fixture(),activityResult=await f.service.createExtracurricular(principal,activity);if(!activityResult.ok)return;assert.deepEqual(await f.service.createGroup(principal,{...group,extracurricularId:activityResult.record.id,startDate:"2026-07-31"}),{ok:false,code:"outside-academic-year"});assert.deepEqual(await f.service.createGroup(principal,{...group,extracurricularId:activityResult.record.id,academicYearId:"year-active",startDate:"2026-07-21",endDate:"2026-07-30"}),{ok:false,code:"future-date-not-allowed"});const created=await f.service.createGroup(principal,{...group,extracurricularId:activityResult.record.id});assert.equal(created.ok,true);if(!created.ok)return;assert.equal((await f.service.transitionGroup(principal,created.record.id,"activate",{expectedVersion:1,reason:"Mulai latihan"})).ok,true)});

test("only active Tenant-local Guru/Staf advise and active Siswa participate with effective history",async()=>{const f=fixture(),activityResult=await f.service.createExtracurricular(principal,activity);if(!activityResult.ok)return;const groupResult=await f.service.createGroup(principal,{...group,extracurricularId:activityResult.record.id});if(!groupResult.ok)return;assert.deepEqual(await f.service.assignAdvisor(principal,{groupId:groupResult.record.id,advisorKind:"teacher",advisorId:"foreign",startDate:"2026-08-01",endDate:null,reason:"Tunjuk"}),{ok:false,code:"invalid-advisor"});const advisor=await f.service.assignAdvisor(principal,{groupId:groupResult.record.id,advisorKind:"staff",advisorId:"staff-1",startDate:"2026-08-01",endDate:null,reason:"Tunjuk"});assert.equal(advisor.ok,true);assert.deepEqual(await f.service.enrollParticipant(principal,{groupId:groupResult.record.id,studentId:"foreign",startDate:"2026-08-01",endDate:null,reason:"Daftar"}),{ok:false,code:"invalid-student"});const enrolled=await f.service.enrollParticipant(principal,{groupId:groupResult.record.id,studentId:"student-1",startDate:"2026-08-01",endDate:null,reason:"Daftar"});assert.equal(enrolled.ok,true);assert.deepEqual(await f.service.enrollParticipant(principal,{groupId:groupResult.record.id,studentId:"student-2",startDate:"2026-08-01",endDate:null,reason:"Daftar"}),{ok:false,code:"capacity-reached"});if(advisor.ok)assert.equal((await f.service.endAdvisor(principal,advisor.record.id,{effectiveDate:"2027-01-01",reason:"Ganti"})).ok,true);if(enrolled.ok)assert.equal((await f.service.endParticipant(principal,enrolled.record.id,{effectiveDate:"2027-01-02",reason:"Keluar"})).ok,true);assert.equal(f.state.advisors.length,1);assert.equal(f.state.participants.length,1)});

test("archive enumerates group, advisor, participant, and location blockers without cascade",async()=>{const f=fixture(),activityResult=await f.service.createExtracurricular(principal,activity);if(!activityResult.ok)return;const groupResult=await f.service.createGroup(principal,{...group,extracurricularId:activityResult.record.id});if(!groupResult.ok)return;await f.service.assignAdvisor(principal,{groupId:groupResult.record.id,advisorKind:"teacher",advisorId:"teacher-1",startDate:"2026-08-01",endDate:null,reason:"Tunjuk"});await f.service.enrollParticipant(principal,{groupId:groupResult.record.id,studentId:"student-1",startDate:"2026-08-01",endDate:null,reason:"Daftar"});const blocked=await f.service.archiveExtracurricular(principal,activityResult.record.id,{expectedVersion:1,reason:"Arsip"});assert.equal(blocked.ok,false);if(!blocked.ok&&"blockers" in blocked)assert.match(blocked.blockers.join(" "),/Kelompok Kegiatan.*Pembina.*Peserta.*Lokasi/);assert.equal(f.state.groups.length,1);assert.equal(f.state.advisors[0]?.endedAt,null);assert.equal(f.state.participants[0]?.endedAt,null)});
