import type { MasterDataPrincipal } from "@/lib/tenant-master-data-access";
export const ASSET_TRACKING_MODES=["grouped","individual"] as const; export type AssetTrackingMode=(typeof ASSET_TRACKING_MODES)[number];
export const ASSET_CONDITIONS=["good","damaged","maintenance","lost"] as const; export type AssetCondition=(typeof ASSET_CONDITIONS)[number];
export type InventoryAsset=Readonly<{id:string;tenantId:string;inventoryCode:string;normalizedInventoryCode:string;name:string;normalizedName:string;category:string;trackingMode:AssetTrackingMode;condition:AssetCondition;quantity:number;locationId:string|null;acquisitionDate:string|null;acquisitionCost:number|null;acquisitionSource:string|null;archived:boolean;archivedAt:Date|null;archiveReason:string|null;version:number;createdAt:Date;updatedAt:Date}>;
export type InventorySnapshot=Readonly<{quantity:number;condition:AssetCondition;locationId:string|null}>;
export type InventoryHistory=Readonly<{id:string;tenantId:string;assetId:string;actorUserId:string;operation:string;before:InventorySnapshot|null;after:InventorySnapshot;reason:string;fromVersion:number;toVersion:number;occurredAt:Date}>;
export type InventoryAssetInput=Readonly<{inventoryCode:string;name:string;category:string;trackingMode:AssetTrackingMode;condition:AssetCondition;quantity:number;locationId?:string|null;acquisitionDate?:string|null;acquisitionCost?:number|null;acquisitionSource?:string|null}>;
type LocationRef={id:string;tenantId:string;archived:boolean};
export interface InventoryAssetTransaction{list():Promise<InventoryAsset[]>;location(id:string):Promise<LocationRef|null>;blockers(id:string):Promise<string[]>;save(record:InventoryAsset,expectedVersion:number):Promise<boolean>;appendHistory(event:InventoryHistory):Promise<void>}
export interface InventoryAssetStore{list(tenantId:string):Promise<InventoryAsset[]>;history(tenantId:string,assetId:string):Promise<InventoryHistory[]>;transaction<T>(tenantId:string,work:(tx:InventoryAssetTransaction)=>Promise<T>):Promise<T>}
type Failure="invalid-input"|"invalid-quantity"|"invalid-location"|"duplicate-code"|"not-found"|"conflict"|"archived"|"not-archived"|"invalid-reason"|"tracking-mode-locked";
const fail=(code:Failure)=>({ok:false,code} as const),clean=(v:string)=>v.trim().replace(/\s+/g," "),normalize=(v:string)=>clean(v).toLocaleLowerCase("id-ID"),snapshot=(x:InventoryAsset):InventorySnapshot=>({quantity:x.quantity,condition:x.condition,locationId:x.locationId});
function prepare(input:InventoryAssetInput){const inventoryCode=clean(input.inventoryCode).toLocaleUpperCase("id-ID"),name=clean(input.name),category=clean(input.category),locationId=input.locationId||null,acquisitionDate=input.acquisitionDate||null,acquisitionCost=input.acquisitionCost??null,acquisitionSource=input.acquisitionSource?clean(input.acquisitionSource):null;if(!inventoryCode||inventoryCode.length>50||!name||name.length>150||!category||category.length>100||!ASSET_TRACKING_MODES.includes(input.trackingMode)||!ASSET_CONDITIONS.includes(input.condition)||(acquisitionCost!==null&&(!Number.isInteger(acquisitionCost)||acquisitionCost<0))||(acquisitionSource?.length??0)>150)return null;if(!Number.isInteger(input.quantity)||input.quantity<0||(input.trackingMode==="individual"&&input.quantity!==1))return "invalid-quantity" as const;return{inventoryCode,normalizedInventoryCode:normalize(inventoryCode),name,normalizedName:normalize(name),category,trackingMode:input.trackingMode,condition:input.condition,quantity:input.quantity,locationId,acquisitionDate,acquisitionCost,acquisitionSource};}
export function createInventoryAssetService(deps:{store:InventoryAssetStore;id?:()=>string;now?:()=>Date}){const id=deps.id??(()=>crypto.randomUUID()),now=deps.now??(()=>new Date());const validLocation=async(tx:InventoryAssetTransaction,locationId:string|null)=>{if(!locationId)return true;const found=await tx.location(locationId);return Boolean(found&&!found.archived);};return{
list:(p:MasterDataPrincipal)=>deps.store.list(p.tenantId),history:(p:MasterDataPrincipal,assetId:string)=>deps.store.history(p.tenantId,assetId),
create(p:MasterDataPrincipal,input:InventoryAssetInput){const value=prepare(input);if(!value)return Promise.resolve(fail("invalid-input"));if(value==="invalid-quantity")return Promise.resolve(fail(value));return deps.store.transaction(p.tenantId,async tx=>{const all=await tx.list();if(all.some(x=>x.normalizedInventoryCode===value.normalizedInventoryCode))return fail("duplicate-code");if(!await validLocation(tx,value.locationId))return fail("invalid-location");const timestamp=now(),record:InventoryAsset={id:id(),tenantId:p.tenantId,...value,archived:false,archivedAt:null,archiveReason:null,version:1,createdAt:timestamp,updatedAt:timestamp};if(!await tx.save(record,0))return fail("conflict");await tx.appendHistory({id:id(),tenantId:p.tenantId,assetId:record.id,actorUserId:p.userId,operation:"created",before:null,after:snapshot(record),reason:"Aset/Barang dibuat",fromVersion:0,toVersion:1,occurredAt:timestamp});return{ok:true,record}as const;});},
edit(p:MasterDataPrincipal,assetId:string,input:InventoryAssetInput,expectedVersion:number){const value=prepare(input);if(!value)return Promise.resolve(fail("invalid-input"));if(value==="invalid-quantity")return Promise.resolve(fail(value));return deps.store.transaction(p.tenantId,async tx=>{const all=await tx.list(),current=all.find(x=>x.id===assetId);if(!current)return fail("not-found");if(current.version!==expectedVersion)return fail("conflict");if(current.archived)return fail("archived");if(current.trackingMode!==value.trackingMode)return fail("tracking-mode-locked");if(all.some(x=>x.id!==assetId&&x.normalizedInventoryCode===value.normalizedInventoryCode))return fail("duplicate-code");if(!await validLocation(tx,value.locationId))return fail("invalid-location");const record={...current,...value,quantity:current.quantity,condition:current.condition,locationId:current.locationId,version:current.version+1,updatedAt:now()};if(!await tx.save(record,expectedVersion))return fail("conflict");return{ok:true,record}as const;});},
change(p:MasterDataPrincipal,assetId:string,input:{expectedVersion:number;quantity?:number;condition?:AssetCondition;locationId?:string|null;reason:string}){return deps.store.transaction(p.tenantId,async tx=>{const current=(await tx.list()).find(x=>x.id===assetId);if(!current)return fail("not-found");if(current.version!==input.expectedVersion)return fail("conflict");if(current.archived)return fail("archived");const reason=clean(input.reason);if(!reason)return fail("invalid-reason");const quantity=input.quantity??current.quantity,condition=input.condition??current.condition,locationId=input.locationId===undefined?current.locationId:input.locationId;if(!Number.isInteger(quantity)||quantity<0||(current.trackingMode==="individual"&&quantity!==1))return fail("invalid-quantity");if(!ASSET_CONDITIONS.includes(condition)||!await validLocation(tx,locationId))return fail("invalid-location");const record={...current,quantity,condition,locationId,version:current.version+1,updatedAt:now()};if(!await tx.save(record,current.version))return fail("conflict");await tx.appendHistory({id:id(),tenantId:p.tenantId,assetId,actorUserId:p.userId,operation:"inventory-changed",before:snapshot(current),after:snapshot(record),reason,fromVersion:current.version,toVersion:record.version,occurredAt:record.updatedAt});return{ok:true,record}as const;});},
archive(p:MasterDataPrincipal,assetId:string,input:{expectedVersion:number;reason:string}){return deps.store.transaction(p.tenantId,async tx=>{const current=(await tx.list()).find(x=>x.id===assetId);if(!current)return fail("not-found");if(current.version!==input.expectedVersion)return fail("conflict");const reason=clean(input.reason);if(!reason)return fail("invalid-reason");const blockers=await tx.blockers(assetId);if(blockers.length)return{ok:false,code:"relationship-blocked",blockers}as const;const timestamp=now(),record={...current,archived:true,archivedAt:timestamp,archiveReason:reason,version:current.version+1,updatedAt:timestamp};if(!await tx.save(record,current.version))return fail("conflict");await tx.appendHistory({id:id(),tenantId:p.tenantId,assetId,actorUserId:p.userId,operation:"archived",before:snapshot(current),after:snapshot(record),reason,fromVersion:current.version,toVersion:record.version,occurredAt:timestamp});return{ok:true,record}as const;});},
reactivate(p:MasterDataPrincipal,assetId:string,input:{expectedVersion:number;reason:string}){return deps.store.transaction(p.tenantId,async tx=>{const all=await tx.list(),current=all.find(x=>x.id===assetId);if(!current)return fail("not-found");if(current.version!==input.expectedVersion)return fail("conflict");if(!current.archived)return fail("not-archived");const reason=clean(input.reason);if(!reason)return fail("invalid-reason");if(all.some(x=>x.id!==assetId&&x.normalizedInventoryCode===current.normalizedInventoryCode))return fail("duplicate-code");if(!await validLocation(tx,current.locationId))return fail("invalid-location");const timestamp=now(),record={...current,archived:false,archivedAt:null,archiveReason:null,version:current.version+1,updatedAt:timestamp};if(!await tx.save(record,current.version))return fail("conflict");await tx.appendHistory({id:id(),tenantId:p.tenantId,assetId,actorUserId:p.userId,operation:"reactivated",before:snapshot(current),after:snapshot(record),reason,fromVersion:current.version,toVersion:record.version,occurredAt:timestamp});return{ok:true,record}as const;});}};}
