/* eslint-disable @typescript-eslint/no-explicit-any */
import assert from "node:assert/strict";
import test from "node:test";
import { createInventoryAssetService, type InventoryAsset, type InventoryAssetStore } from "@/lib/inventory-asset";
import type { MasterDataPrincipal } from "@/lib/tenant-master-data-access";

const principal: MasterDataPrincipal = { userId: "admin-1", tenantId: "tenant-1", role: "school-admin", capabilities: { read: true, write: true, downloadTemplate: true } };
function fixture() {
  const records: InventoryAsset[] = [], history: unknown[] = [], locations = [{ id: "room-1", tenantId: "tenant-1", archived: false }, { id: "room-old", tenantId: "tenant-1", archived: true }], blockers: string[] = [];
  const store: InventoryAssetStore = { async list(tenantId) { return structuredClone(records.filter(x => x.tenantId === tenantId)); }, async history(tenantId, assetId) { return structuredClone(history.filter((x: any) => x.tenantId === tenantId && x.assetId === assetId)) as any; }, async transaction(tenantId, work) { return work({ async list() { return structuredClone(records.filter(x => x.tenantId === tenantId)); }, async location(id) { return locations.find(x => x.tenantId === tenantId && x.id === id) ?? null; }, async blockers() { return blockers; }, async save(record, expectedVersion) { const i = records.findIndex(x => x.tenantId === tenantId && x.id === record.id); if (i < 0) { if (expectedVersion) return false; records.push(structuredClone(record)); return true; } if (records[i].version !== expectedVersion) return false; records[i] = structuredClone(record); return true; }, async appendHistory(event) { history.push(structuredClone(event)); } }); } };
  let id = 0; return { records, history, blockers, service: createInventoryAssetService({ store, id: () => `id-${++id}`, now: () => new Date("2026-07-20T00:00:00Z") }) };
}
const grouped = { inventoryCode: " inv-01 ", name: " Laptop Siswa ", category: "Elektronik", trackingMode: "grouped" as const, condition: "good" as const, quantity: 10, locationId: "room-1", acquisitionDate: "2026-01-10", acquisitionCost: 5000000, acquisitionSource: "BOS" };
test("creates grouped and individual Aset/Barang with reserved Tenant-unique codes", async () => { const f = fixture(), made = await f.service.create(principal, grouped); assert.equal(made.ok, true); if (!made.ok) return; assert.equal(made.record.inventoryCode, "INV-01"); assert.equal((await f.service.archive(principal, made.record.id, { expectedVersion: 1, reason: "Rusak" })).ok, true); assert.deepEqual(await f.service.create(principal, grouped), { ok: false, code: "duplicate-code" }); assert.deepEqual(await f.service.create(principal, { ...grouped, inventoryCode: "UNIT-1", trackingMode: "individual", quantity: 2 }), { ok: false, code: "invalid-quantity" }); assert.deepEqual(await f.service.list({ ...principal, tenantId: "tenant-2" }), []); });
test("requires active same-Tenant locations and reasons for state changes", async () => { const f = fixture(); assert.deepEqual(await f.service.create(principal, { ...grouped, locationId: "room-old" }), { ok: false, code: "invalid-location" }); const made = await f.service.create(principal, grouped); if (!made.ok) return; assert.deepEqual(await f.service.change(principal, made.record.id, { expectedVersion: 1, quantity: 9, reason: "" }), { ok: false, code: "invalid-reason" }); assert.equal(f.history.length, 1); });
test("atomically records before/after, actor and time and prevents destructive tracking changes", async () => { const f = fixture(), made = await f.service.create(principal, grouped); if (!made.ok) return; const changed = await f.service.change(principal, made.record.id, { expectedVersion: 1, quantity: 7, condition: "damaged", locationId: null, reason: "Tiga unit rusak" }); assert.equal(changed.ok, true); assert.equal(f.history.length, 2); assert.deepEqual((f.history[1] as any).before, { quantity: 10, condition: "good", locationId: "room-1" }); assert.deepEqual((f.history[1] as any).after, { quantity: 7, condition: "damaged", locationId: null }); assert.equal((f.history[1] as any).actorUserId, "admin-1"); assert.deepEqual(await f.service.edit(principal, made.record.id, { ...grouped, trackingMode: "individual", quantity: 1 }, 2), { ok: false, code: "tracking-mode-locked" }); });
test("archive blockers are explicit and reactivation revalidates location", async () => { const f = fixture(), made = await f.service.create(principal, grouped); if (!made.ok) return; f.blockers.push("Peminjaman aktif #1"); const blocked = await f.service.archive(principal, made.record.id, { expectedVersion: 1, reason: "Arsip" }); assert.deepEqual(blocked, { ok: false, code: "relationship-blocked", blockers: ["Peminjaman aktif #1"] }); f.blockers.length = 0; assert.equal((await f.service.archive(principal, made.record.id, { expectedVersion: 1, reason: "Arsip" })).ok, true); f.records[0] = { ...f.records[0], locationId: "room-old" }; assert.deepEqual(await f.service.reactivate(principal, made.record.id, { expectedVersion: 2, reason: "Aktif lagi" }), { ok: false, code: "invalid-location" }); });
