import type { MasterDataPrincipal } from "@/lib/tenant-master-data-access";
export const LOCATION_TYPES=["site","building","floor","room","outdoor","other"] as const;
export type LocationType=(typeof LOCATION_TYPES)[number];
export type Location=Readonly<{id:string;tenantId:string;name:string;normalizedName:string;code:string;normalizedCode:string;type:LocationType;capacity:number|null;description:string|null;parentId:string|null;archived:boolean;archivedAt:Date|null;archiveReason:string|null;version:number;createdAt:Date;updatedAt:Date}>;
export type LocationBlocker=Readonly<{id:string;tenantId:string;locationId:string;label:string;active:boolean}>;
export type LocationHistory=Readonly<{id:string;tenantId:string;locationId:string;actorUserId:string;operation:string;fromVersion:number;toVersion:number;reason:string;occurredAt:Date}>;
export interface LocationTransaction{list():Promise<Location[]>;references(id:string):Promise<LocationBlocker[]>;save(record:Location,expectedVersion:number):Promise<boolean>;appendHistory(event:LocationHistory):Promise<void>}
export interface LocationStore{list(tenantId:string):Promise<Location[]>;blockers?(tenantId:string,id:string):Promise<LocationBlocker[]>;transaction<T>(tenantId:string,work:(tx:LocationTransaction)=>Promise<T>):Promise<T>}
export type LocationInput=Readonly<{name:string;code:string;type:LocationType;capacity?:number|null;description?:string|null;parentId?:string|null}>;
type Failure="invalid-input"|"duplicate-code"|"invalid-parent"|"self-parent"|"hierarchy-cycle"|"not-found"|"conflict"|"archived"|"relationship-blocked"|"not-archived";
const fail=(code:Failure)=>({ok:false,code} as const), clean=(v:string)=>v.trim().replace(/\s+/g," "), normalize=(v:string)=>clean(v).toLocaleLowerCase("id-ID");
function prepare(input:LocationInput){const name=clean(input.name),code=clean(input.code).toLocaleUpperCase("id-ID"),capacity=input.capacity??null,description=input.description?clean(input.description):null,parentId=input.parentId||null;if(!name||name.length>150||!code||code.length>30||!LOCATION_TYPES.includes(input.type)||(capacity!==null&&(!Number.isInteger(capacity)||capacity<1||capacity>100000))||(description?.length??0)>2000)return null;return{name,normalizedName:normalize(name),code,normalizedCode:normalize(code),type:input.type,capacity,description,parentId};}
function validateParent(id:string,tenantId:string,parentId:string|null,all:Location[]){if(!parentId)return;if(parentId===id)return"self-parent" as const;const parent=all.find(x=>x.id===parentId&&x.tenantId===tenantId&&!x.archived);if(!parent)return"invalid-parent" as const;const seen=new Set([id]);let cursor:Location|undefined=parent;while(cursor){if(seen.has(cursor.id))return"hierarchy-cycle" as const;seen.add(cursor.id);cursor=cursor.parentId?all.find(x=>x.id===cursor!.parentId&&x.tenantId===tenantId):undefined;}}
function duplicate(code:string,all:Location[],exclude?:string){return all.some(x=>x.id!==exclude&&x.normalizedCode===code);}
export function createLocationService(deps:{store:LocationStore;id?:()=>string;now?:()=>Date}){const id=deps.id??(()=>crypto.randomUUID()),now=deps.now??(()=>new Date());return{
list:(p:MasterDataPrincipal)=>deps.store.list(p.tenantId),
async blockers(p:MasterDataPrincipal,locationId:string){const [all,references]=await Promise.all([deps.store.list(p.tenantId),deps.store.blockers?.(p.tenantId,locationId)??Promise.resolve([])]);return [...all.filter(x=>x.parentId===locationId&&!x.archived).map(x=>({id:x.id,tenantId:p.tenantId,locationId,label:`Child aktif: ${x.name}`,active:true})),...references];},
create(p:MasterDataPrincipal,input:LocationInput){const value=prepare(input);if(!value)return Promise.resolve(fail("invalid-input"));return deps.store.transaction(p.tenantId,async tx=>{const all=await tx.list();if(duplicate(value.normalizedCode,all))return fail("duplicate-code");const parentFailure=validateParent("new",p.tenantId,value.parentId,all);if(parentFailure)return fail(parentFailure);const timestamp=now(),record:Location={id:id(),tenantId:p.tenantId,...value,archived:false,archivedAt:null,archiveReason:null,version:1,createdAt:timestamp,updatedAt:timestamp};if(!await tx.save(record,0))return fail("conflict");await tx.appendHistory({id:id(),tenantId:p.tenantId,locationId:record.id,actorUserId:p.userId,operation:"created",fromVersion:0,toVersion:1,reason:"Lokasi/Ruang dibuat",occurredAt:timestamp});return{ok:true,record}as const;});},
edit(p:MasterDataPrincipal,locationId:string,input:LocationInput,expectedVersion:number){const value=prepare(input);if(!value)return Promise.resolve(fail("invalid-input"));return deps.store.transaction(p.tenantId,async tx=>{const all=await tx.list(),current=all.find(x=>x.id===locationId);if(!current)return fail("not-found");if(current.version!==expectedVersion)return fail("conflict");if(current.archived)return fail("archived");if(duplicate(value.normalizedCode,all,current.id))return fail("duplicate-code");const parentFailure=validateParent(current.id,p.tenantId,value.parentId,all);if(parentFailure)return fail(parentFailure);const record={...current,...value,version:current.version+1,updatedAt:now()};if(!await tx.save(record,expectedVersion))return fail("conflict");await tx.appendHistory({id:id(),tenantId:p.tenantId,locationId,actorUserId:p.userId,operation:"edited",fromVersion:expectedVersion,toVersion:record.version,reason:"Lokasi/Ruang diubah",occurredAt:record.updatedAt});return{ok:true,record}as const;});},
archive(p:MasterDataPrincipal,locationId:string,input:{expectedVersion:number;reason:string}){return deps.store.transaction(p.tenantId,async tx=>{const all=await tx.list(),current=all.find(x=>x.id===locationId);if(!current)return fail("not-found");if(current.version!==input.expectedVersion)return fail("conflict");const reason=clean(input.reason);if(!reason)return fail("invalid-input");const children=all.filter(x=>x.parentId===locationId&&!x.archived).map(x=>({id:x.id,tenantId:p.tenantId,locationId,label:`Child aktif: ${x.name}`,active:true})),blockers=[...children,...await tx.references(locationId)];if(blockers.length)return{ok:false,code:"relationship-blocked",blockers}as const;const timestamp=now(),record={...current,archived:true,archivedAt:timestamp,archiveReason:reason,version:current.version+1,updatedAt:timestamp};if(!await tx.save(record,input.expectedVersion))return fail("conflict");await tx.appendHistory({id:id(),tenantId:p.tenantId,locationId,actorUserId:p.userId,operation:"archived",fromVersion:current.version,toVersion:record.version,reason,occurredAt:timestamp});return{ok:true,record}as const;});},
reactivate(p:MasterDataPrincipal,locationId:string,input:{expectedVersion:number;reason:string}){return deps.store.transaction(p.tenantId,async tx=>{const all=await tx.list(),current=all.find(x=>x.id===locationId);if(!current)return fail("not-found");if(current.version!==input.expectedVersion)return fail("conflict");if(!current.archived)return fail("not-archived");const reason=clean(input.reason);if(!reason)return fail("invalid-input");if(duplicate(current.normalizedCode,all,current.id))return fail("duplicate-code");const parentFailure=validateParent(current.id,p.tenantId,current.parentId,all);if(parentFailure)return fail(parentFailure);const timestamp=now(),record={...current,archived:false,archivedAt:null,archiveReason:null,version:current.version+1,updatedAt:timestamp};if(!await tx.save(record,input.expectedVersion))return fail("conflict");await tx.appendHistory({id:id(),tenantId:p.tenantId,locationId,actorUserId:p.userId,operation:"reactivated",fromVersion:current.version,toVersion:record.version,reason,occurredAt:timestamp});return{ok:true,record}as const;});}
};}
