import assert from "node:assert/strict";
import test from "node:test";
import { createLocationService, type Location, type LocationStore } from "@/lib/location";
import type { MasterDataPrincipal } from "@/lib/tenant-master-data-access";

const principal: MasterDataPrincipal = { userId: "admin-1", tenantId: "tenant-1", role: "school-admin", capabilities: { read: true, write: true, downloadTemplate: true } };
const base = { name: "Gedung Utama", code: "GDG-01", type: "building" as const, capacity: null, description: null, parentId: null };
function fixture() {
  const records: Location[] = [], references: { id: string; tenantId: string; locationId: string; label: string; active: boolean }[] = [], history: unknown[] = [];
  const store: LocationStore = { async list(tenantId) { return structuredClone(records.filter((x) => x.tenantId === tenantId)); }, async transaction(tenantId, work) { return work({ async list() { return structuredClone(records.filter((x) => x.tenantId === tenantId)); }, async references(id) { return structuredClone(references.filter((x) => x.tenantId === tenantId && x.locationId === id && x.active)); }, async save(record, expectedVersion) { const index = records.findIndex((x) => x.tenantId === tenantId && x.id === record.id); if (index < 0) { if (expectedVersion !== 0) return false; records.push(structuredClone(record)); return true; } if (records[index].version !== expectedVersion) return false; records[index] = structuredClone(record); return true; }, async appendHistory(event) { history.push(structuredClone(event)); } }); } };
  let id = 0; return { records, references, history, service: createLocationService({ store, id: () => `id-${++id}`, now: () => new Date("2026-07-20T00:00:00Z") }) };
}
test("creates normalized Tenant-owned Lokasi/Ruang and reserves code after archive", async () => { const f = fixture(), created = await f.service.create(principal, { ...base, name: "  Gedung   Utama ", code: " gdg-01 " }); assert.equal(created.ok, true); if (!created.ok) return; assert.deepEqual({ name: created.record.name, code: created.record.code, tenant: created.record.tenantId }, { name: "Gedung Utama", code: "GDG-01", tenant: "tenant-1" }); assert.equal((await f.service.archive(principal, created.record.id, { expectedVersion: 1, reason: "Tidak dipakai" })).ok, true); assert.deepEqual(await f.service.create(principal, { ...base, name: "Gedung Baru", code: "GDG-01" }), { ok: false, code: "duplicate-code" }); assert.deepEqual(await f.service.list({ ...principal, tenantId: "tenant-2" }), []); });
test("requires a same-Tenant active parent and rejects self-parent and cycles", async () => { const f = fixture(), root = await f.service.create(principal, base); if (!root.ok) return; const child = await f.service.create(principal, { ...base, name: "Lantai 1", code: "LT-01", type: "floor", parentId: root.record.id }); if (!child.ok) return; assert.deepEqual(await f.service.edit(principal, root.record.id, { ...base, parentId: child.record.id }, 1), { ok: false, code: "hierarchy-cycle" }); assert.deepEqual(await f.service.edit(principal, child.record.id, { ...base, name: "Lantai 1", code: "LT-01", type: "floor", parentId: child.record.id }, 1), { ok: false, code: "self-parent" }); assert.deepEqual(await f.service.create({ ...principal, tenantId: "tenant-2" }, { ...base, name: "Ruang asing", code: "R-2", parentId: root.record.id }), { ok: false, code: "invalid-parent" }); });
test("rejects stale hierarchy writes and enumerates active child and reference blockers", async () => { const f = fixture(), root = await f.service.create(principal, base); if (!root.ok) return; await f.service.create(principal, { ...base, name: "Lantai 1", code: "LT-01", type: "floor", parentId: root.record.id }); f.references.push({ id: "asset-1", tenantId: principal.tenantId, locationId: root.record.id, label: "Aset Laptop aktif", active: true }); const blocked = await f.service.archive(principal, root.record.id, { expectedVersion: 1, reason: "Arsip" }); assert.equal(blocked.ok, false); if (blocked.ok || !("blockers" in blocked)) return; assert.deepEqual(blocked.blockers.map((x) => x.label), ["Child aktif: Lantai 1", "Aset Laptop aktif"]); assert.deepEqual(await f.service.edit(principal, root.record.id, { ...base, name: "Gedung A" }, 99), { ok: false, code: "conflict" }); });
test("reactivation reruns code and parent validation without restoring children or references", async () => { const f = fixture(), root = await f.service.create(principal, base); if (!root.ok) return; const child = await f.service.create(principal, { ...base, name: "Lantai 1", code: "LT-01", type: "floor", parentId: root.record.id }); if (!child.ok) return; await f.service.archive(principal, child.record.id, { expectedVersion: 1, reason: "Arsip" }); await f.service.archive(principal, root.record.id, { expectedVersion: 1, reason: "Arsip" }); assert.deepEqual(await f.service.reactivate(principal, child.record.id, { expectedVersion: 2, reason: "Aktif lagi" }), { ok: false, code: "invalid-parent" }); });
