
import { randomUUID } from "node:crypto";
import ExcelJS from "exceljs";
import mysql from "mysql2/promise";
import { buildExecutionConfirmation, type ClaimedExecutionRow, type ExecutionOutcome, type ExecutionRow, type PeopleImportExecutionStore } from "@/lib/people-import-execution";
import type { MasterDataPrincipal } from "@/lib/tenant-master-data-access";
import { validatePeopleImportValues, type PeopleImportKind } from "@/lib/people-import";

const url=process.env.DATABASE_URL; let database:mysql.Pool|undefined; const db=()=>database??=mysql.createPool({uri:url!,connectionLimit:8});
const json=<T>(value:unknown):T=>typeof value==="string"?JSON.parse(value) as T:value as T;
export const peopleImportRetentionDays=(environment:Record<string,string|undefined>=process.env)=>{const n=Number(environment.PEOPLE_IMPORT_FILE_RETENTION_DAYS);return Number.isInteger(n)&&n>0?n:null;};

export async function confirmPeopleImportExecution(principal:MasterDataPrincipal,revisionId:string,selectedRowIds:string[],retentionDays=peopleImportRetentionDays()){
 if(!principal.capabilities.write)return{ok:false,code:"read-only"}as const;if(!retentionDays)return{ok:false,code:"retention-not-configured"}as const;
 const c=await db().getConnection();try{await c.beginTransaction();const[revision]=await c.query<mysql.RowDataPacket[]>("SELECT r.id,r.batch_id,r.created_at,b.read_only_at FROM people_import_revision r JOIN people_import_batch b ON b.tenant_id=r.tenant_id AND b.id=r.batch_id WHERE r.tenant_id=? AND r.id=? FOR UPDATE",[principal.tenantId,revisionId]);if(!revision[0])return await rollback(c,"not-found");if(new Date(revision[0].read_only_at)<=new Date())return await rollback(c,"read-only");
 const[raw]=await c.query<mysql.RowDataPacket[]>("SELECT r.id,r.row_number,r.state,d.action,d.target_person_id FROM people_import_row r LEFT JOIN people_import_decision d ON d.tenant_id=r.tenant_id AND d.revision_id=r.revision_id AND d.row_id=r.id WHERE r.tenant_id=? AND r.revision_id=?",[principal.tenantId,revisionId]);const rows:ExecutionRow[]=raw.map(r=>({id:r.id,rowNumber:Number(r.row_number),state:r.state,decision:r.action?{action:r.action,targetPersonId:r.target_person_id??undefined}:null}));let confirmation;try{confirmation=buildExecutionConfirmation(revisionId,rows,selectedRowIds)}catch(error){return await rollback(c,error instanceof Error?error.message:"invalid")}
 const executionId=randomUUID();await c.execute("INSERT INTO people_import_execution (id,tenant_id,batch_id,revision_id,row_set_hash,selected_count,actor_user_id) VALUES (?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE id=id",[executionId,principal.tenantId,revision[0].batch_id,revisionId,confirmation.rowSetHash,confirmation.selectedRowIds.length,principal.userId]);const[existing]=await c.query<mysql.RowDataPacket[]>("SELECT id FROM people_import_execution WHERE tenant_id=? AND batch_id=? AND revision_id=? AND row_set_hash=?",[principal.tenantId,revision[0].batch_id,revisionId,confirmation.rowSetHash]);const id=existing[0].id as string;
 for(const row of rows.filter(r=>confirmation.selectedRowIds.includes(r.id))){const action=row.state==="rejected"?"reject":row.decision?.action==="skip"?"skip":row.decision?.action==="link"?"link":"create";await c.execute("INSERT IGNORE INTO people_import_execution_row (id,tenant_id,execution_id,revision_id,row_id,planned_action,target_person_id) VALUES (?,?,?,?,?,?,?)",[randomUUID(),principal.tenantId,id,revisionId,row.id,action,row.decision?.action==="link"?row.decision.targetPersonId:null]);}await c.commit();return{ok:true,executionId:id,confirmation}as const;}catch(error){await c.rollback();throw error}finally{c.release()}}
async function rollback(c:mysql.PoolConnection,code:string){await c.rollback();return{ok:false,code}as const}

async function insertProfile(c:mysql.PoolConnection,kind:string,tenantId:string,personId:string,profileId:string,v:Record<string,string>,actorId:string){const now=new Date();if(kind==="student"){await c.execute("INSERT INTO student_profile (id,tenant_id,person_id,nis,normalized_nis,nisn,entry_date,status,archived,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'active',false,1,?,?)",[profileId,tenantId,personId,v.nis,v.nis.toLowerCase(),v.nisn||null,v.entryDate,now,now]);await c.execute("INSERT INTO student_lifecycle_period (id,tenant_id,student_id,status,started_at,reason,created_by_user_id,created_at) VALUES (?,?,?,'active',?,'Impor awal',?,?)",[randomUUID(),tenantId,profileId,v.entryDate,actorId,now]);await c.execute("INSERT INTO student_audit (id,tenant_id,person_id,student_id,actor_user_id,operation,from_person_version,to_person_version,from_student_version,to_student_version,lifecycle_after,occurred_at) VALUES (?,?,?,?,?, ?,0,1,0,1,?,?)",[randomUUID(),tenantId,personId,profileId,actorId,"created-student",JSON.stringify({status:"active",startedAt:v.entryDate}),now]);}
 else if(kind==="teacher"){await c.execute("INSERT INTO teacher_profile (id,tenant_id,person_id,teacher_number,normalized_teacher_number,nuptk,employment_type,service_start_date,status,archived,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,'active',false,1,?,?)",[profileId,tenantId,personId,v.teacherNumber,v.teacherNumber.toLowerCase(),v.nuptk||null,v.employmentType,v.serviceStartDate,now,now]);await c.execute("INSERT INTO teacher_service_period (id,tenant_id,teacher_id,status,started_at,reason,created_by_user_id,created_at) VALUES (?,?,?,'active',?,'Impor awal',?,?)",[randomUUID(),tenantId,profileId,v.serviceStartDate,actorId,now]);await c.execute("INSERT INTO teacher_audit (id,tenant_id,person_id,teacher_id,actor_user_id,operation,from_person_version,to_person_version,from_teacher_version,to_teacher_version,lifecycle_after,occurred_at) VALUES (?,?,?,?,?,'created-teacher',0,1,0,1,?,?)",[randomUUID(),tenantId,personId,profileId,actorId,JSON.stringify({status:"active",startedAt:v.serviceStartDate}),now]);}
 else{await c.execute("INSERT INTO staff_profile (id,tenant_id,person_id,staff_number,normalized_staff_number,position,employment_type,service_start_date,status,archived,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?, 'active',false,1,?,?)",[profileId,tenantId,personId,v.staffNumber,v.staffNumber.toLowerCase(),v.position,v.employmentType,v.serviceStartDate,now,now]);await c.execute("INSERT INTO staff_service_period (id,tenant_id,staff_id,status,started_at,reason,created_by_user_id,created_at) VALUES (?,?,?,'active',?,'Impor awal',?,?)",[randomUUID(),tenantId,profileId,v.serviceStartDate,actorId,now]);await c.execute("INSERT INTO staff_position_assignment (id,tenant_id,staff_id,position,started_at,created_by_user_id,created_at) VALUES (?,?,?,?,?,?,?)",[randomUUID(),tenantId,profileId,v.position,v.serviceStartDate,actorId,now]);await c.execute("INSERT INTO staff_audit (id,tenant_id,person_id,staff_id,actor_user_id,operation,from_person_version,to_person_version,from_staff_version,to_staff_version,lifecycle_after,occurred_at) VALUES (?,?,?,?,?,'created-staff',0,1,0,1,?,?)",[randomUUID(),tenantId,personId,profileId,actorId,JSON.stringify({status:"active",startedAt:v.serviceStartDate}),now]);}}

export const peopleImportExecutionStore:PeopleImportExecutionStore={
 async checkEmergencyStop(){return false},
 async claimNext(workerId){const c=await db().getConnection();try{await c.beginTransaction();const[r]=await c.query<mysql.RowDataPacket[]>("SELECT er.execution_id,er.tenant_id,er.revision_id,er.row_id,e.actor_user_id FROM people_import_execution_row er JOIN people_import_execution e ON e.tenant_id=er.tenant_id AND e.id=er.execution_id LEFT JOIN people_import_control ctl ON ctl.tenant_id=er.tenant_id WHERE er.outcome IS NULL AND er.claimed_at IS NULL AND COALESCE(ctl.emergency_stop,false)=false ORDER BY e.created_at,er.id LIMIT 1 FOR UPDATE SKIP LOCKED");if(!r[0]){await c.rollback();return null}await c.execute("UPDATE people_import_execution_row SET claimed_by=?,claimed_at=NOW(3) WHERE tenant_id=? AND execution_id=? AND row_id=? AND claimed_at IS NULL",[workerId,r[0].tenant_id,r[0].execution_id,r[0].row_id]);await c.execute("UPDATE people_import_execution SET status='processing' WHERE tenant_id=? AND id=? AND status='queued'",[r[0].tenant_id,r[0].execution_id]);await c.commit();return{executionId:r[0].execution_id,tenantId:r[0].tenant_id,revisionId:r[0].revision_id,rowId:r[0].row_id,actorId:r[0].actor_user_id}as ClaimedExecutionRow}catch(e){await c.rollback();throw e}finally{c.release()}},
 async executeRow(claim){
  const c=await db().getConnection();
  try{
   await c.beginTransaction();
   const[r]=await c.query<mysql.RowDataPacket[]>("SELECT er.*,e.batch_id,e.actor_user_id,pr.entity_kind,source_row.values_json,source_row.state,t.operational_status,t.trial_ends_at,t.settings,u.tenant_role,u.tenant_id user_tenant FROM people_import_execution_row er JOIN people_import_execution e ON e.tenant_id=er.tenant_id AND e.id=er.execution_id JOIN people_import_revision pr ON pr.tenant_id=er.tenant_id AND pr.id=er.revision_id JOIN people_import_row source_row ON source_row.tenant_id=er.tenant_id AND source_row.id=er.row_id JOIN tenant t ON t.id=er.tenant_id JOIN user u ON u.id=e.actor_user_id WHERE er.tenant_id=? AND er.execution_id=? AND er.row_id=? FOR UPDATE",[claim.tenantId,claim.executionId,claim.rowId]);
   const x=r[0];if(!x||x.outcome){await c.rollback();return}
   const settings=json<{features?:Record<string,unknown>}>(x.settings??{});
   if(x.operational_status!=="active"||(x.trial_ends_at&&new Date(x.trial_ends_at)<=new Date())||x.tenant_role!=="school-admin"||x.user_tenant!==x.tenant_id||settings.features?.masterDataWrite!==true||settings.features?.masterDataImportExecution!==true)throw new Error("authority-revoked");
   if(x.planned_action==="skip"||x.planned_action==="reject"){await c.execute("UPDATE people_import_execution_row SET outcome=?,completed_at=NOW(3) WHERE id=?",[x.planned_action==="skip"?"skipped":"rejected",x.id]);await finish(c,x);await c.commit();return}
   const[s]=await c.query<mysql.RowDataPacket[]>("SELECT id FROM people_import_success WHERE tenant_id=? AND batch_id=? AND revision_id=? AND row_id=?",[x.tenant_id,x.batch_id,x.revision_id,x.row_id]);
   if(s[0]){await c.execute("UPDATE people_import_execution_row SET outcome='already-committed',completed_at=NOW(3) WHERE id=?",[x.id]);await finish(c,x);await c.commit();return}
   const validated=validatePeopleImportValues(x.entity_kind as PeopleImportKind,json<Record<string,string>>(x.values_json));
   if(validated.findings.length)throw new Error("row-invalid");
   const v=validated.values,kind=x.entity_kind as PeopleImportKind,profileTable=kind==="student"?"student_profile":kind==="teacher"?"teacher_profile":"staff_profile",numberColumn=kind==="student"?"normalized_nis":kind==="teacher"?"normalized_teacher_number":"normalized_staff_number",numberValue=(kind==="student"?v.nis:kind==="teacher"?v.teacherNumber:v.staffNumber).toLocaleLowerCase("id-ID"),secondaryColumn=kind==="student"?"nisn":kind==="teacher"?"nuptk":null,secondaryValue=kind==="student"?v.nisn:kind==="teacher"?v.nuptk:null;
   const[duplicates]=await c.query<mysql.RowDataPacket[]>(`SELECT id FROM ${profileTable} WHERE tenant_id=? AND (${numberColumn}=?${secondaryColumn&&secondaryValue?` OR ${secondaryColumn}=?`:""}) FOR UPDATE`,secondaryColumn&&secondaryValue?[x.tenant_id,numberValue,secondaryValue]:[x.tenant_id,numberValue]);
   if(duplicates.length)throw new Error("profile-identifier-conflict");
   const[exactPeople]=await c.query<mysql.RowDataPacket[]>(`SELECT DISTINCT p.id FROM school_person p LEFT JOIN ${profileTable} profile ON profile.tenant_id=p.tenant_id AND profile.person_id=p.id WHERE p.tenant_id=? AND (${[v.nik?"p.nik=?":null,v.nip?"p.nip=?":null,`profile.${numberColumn}=?`,secondaryColumn&&secondaryValue?`profile.${secondaryColumn}=?`:null].filter(Boolean).join(" OR ")}) FOR UPDATE`,[x.tenant_id,...[v.nik,v.nip,numberValue,secondaryColumn&&secondaryValue?secondaryValue:null].filter((value):value is string=>Boolean(value))]);
   const[similar]=await c.query<mysql.RowDataPacket[]>("SELECT id FROM school_person WHERE tenant_id=? AND archived=false AND normalized_name=? AND normalized_birth_place=? AND birth_date=? AND gender=? FOR UPDATE",[x.tenant_id,v.fullName.toLocaleLowerCase("id-ID"),v.birthPlace.toLocaleLowerCase("id-ID"),v.birthDate,v.gender]);
   const personId=x.planned_action==="link"?String(x.target_person_id??""):randomUUID();
   if(x.planned_action==="link"){
    const[p]=await c.query<mysql.RowDataPacket[]>(`SELECT p.id,p.archived,profile.id profile_id FROM school_person p LEFT JOIN ${profileTable} profile ON profile.tenant_id=p.tenant_id AND profile.person_id=p.id WHERE p.tenant_id=? AND p.id=? FOR UPDATE`,[x.tenant_id,personId]),target=p[0];
    if(!target||target.archived||target.profile_id||exactPeople.length>1||exactPeople.length===1&&exactPeople[0].id!==personId||!similar.some(row=>row.id===personId))throw new Error("match-ineligible");
   }else{
    if(exactPeople.length)throw new Error("match-decision-required");
    if(x.state!=="warning"&&similar.length)throw new Error("match-decision-required");
    await c.execute("INSERT INTO school_person (id,tenant_id,full_name,normalized_name,birth_place,normalized_birth_place,birth_date,gender,nik,nip,street,archived,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,false,1,NOW(3),NOW(3))",[personId,x.tenant_id,v.fullName,v.fullName.toLocaleLowerCase("id-ID"),v.birthPlace,v.birthPlace.toLocaleLowerCase("id-ID"),v.birthDate,v.gender,v.nik||null,v.nip||null,v.street]);
   }
   const profileId=randomUUID();await insertProfile(c,kind,x.tenant_id,personId,profileId,v,x.actor_user_id);const outcome:ExecutionOutcome=x.planned_action==="link"?"linked":"created";
   await c.execute("INSERT INTO people_import_success (id,tenant_id,batch_id,revision_id,row_id,execution_id,outcome,person_id,profile_id) VALUES (?,?,?,?,?,?,?,?,?)",[randomUUID(),x.tenant_id,x.batch_id,x.revision_id,x.row_id,x.execution_id,outcome,personId,profileId]);
   await c.execute("INSERT INTO people_import_audit (id,tenant_id,execution_id,row_id,actor_user_id,outcome,person_id,profile_id,occurred_at) VALUES (?,?,?,?,?,?,?,?,NOW(3))",[randomUUID(),x.tenant_id,x.execution_id,x.row_id,x.actor_user_id,outcome,personId,profileId]);
   await c.execute("UPDATE people_import_execution_row SET outcome=?,record_id=?,completed_at=NOW(3) WHERE id=?",[outcome,profileId,x.id]);await finish(c,x);await c.commit();
  }catch(e){await c.rollback();throw e}finally{c.release()}
 },
 async recordFailure(claim,error){const code=error instanceof Error?error.message:"execution-failed";await db().execute("UPDATE people_import_execution_row SET outcome='failed',error_code=?,completed_at=NOW(3) WHERE tenant_id=? AND execution_id=? AND row_id=? AND outcome IS NULL",[code.slice(0,100),claim.tenantId,claim.executionId,claim.rowId]);await updateExecutionStatus(claim.tenantId,claim.executionId)},
};
async function finish(c:mysql.PoolConnection,x:mysql.RowDataPacket){const[n]=await c.query<mysql.RowDataPacket[]>("SELECT COUNT(*) pending FROM people_import_execution_row WHERE tenant_id=? AND execution_id=? AND outcome IS NULL",[x.tenant_id,x.execution_id]);if(Number(n[0].pending)===0){const[f]=await c.query<mysql.RowDataPacket[]>("SELECT COUNT(*) failed FROM people_import_execution_row WHERE tenant_id=? AND execution_id=? AND outcome='failed'",[x.tenant_id,x.execution_id]);await c.execute("UPDATE people_import_execution SET status=?,completed_at=NOW(3) WHERE tenant_id=? AND id=?",[Number(f[0].failed)?"partially_completed":"completed",x.tenant_id,x.execution_id])}}
async function updateExecutionStatus(tenantId:string,executionId:string){const c=await db().getConnection();try{await c.beginTransaction();await finish(c,{tenant_id:tenantId,execution_id:executionId}as mysql.RowDataPacket);await c.commit()}catch(e){await c.rollback();throw e}finally{c.release()}}
export async function setPeopleImportEmergencyStop(tenantId:string,stopped:boolean){await db().execute("INSERT INTO people_import_control (tenant_id,emergency_stop) VALUES (?,?) ON DUPLICATE KEY UPDATE emergency_stop=VALUES(emergency_stop),updated_at=NOW(3)",[tenantId,stopped])}
export async function getPeopleImportExecution(tenantId:string,executionId:string){const[e]=await db().query<mysql.RowDataPacket[]>("SELECT * FROM people_import_execution WHERE tenant_id=? AND id=?",[tenantId,executionId]);if(!e[0])return null;const[rows]=await db().query<mysql.RowDataPacket[]>("SELECT er.outcome,er.error_code,r.row_number FROM people_import_execution_row er JOIN people_import_row r ON r.tenant_id=er.tenant_id AND r.id=er.row_id WHERE er.tenant_id=? AND er.execution_id=? ORDER BY r.row_number",[tenantId,executionId]);const counts={created:0,linked:0,skipped:0,rejected:0,failed:0,"already-committed":0};for(const row of rows)if(row.outcome)counts[row.outcome as keyof typeof counts]++;return{status:e[0].status,counts,rows:rows.map(r=>({rowNumber:Number(r.row_number),outcome:r.outcome,errorCode:r.error_code}))}}
export async function buildPeopleImportResultWorkbook(tenantId:string,executionId:string){const result=await getPeopleImportExecution(tenantId,executionId);if(!result)return null;const wb=new ExcelJS.Workbook(),summary=wb.addWorksheet("Ringkasan"),details=wb.addWorksheet("Hasil");summary.addRows([["Outcome","Jumlah"],...Object.entries(result.counts)]);details.addRows([["Row","Outcome","Kode error"],...result.rows.map(r=>[r.rowNumber,r.outcome,r.errorCode??""])]);return new Uint8Array(await wb.xlsx.writeBuffer())}
export async function closePeopleImportExecutionPool(){if(database){await database.end();database=undefined}}
