import { and, asc, eq, sql } from "drizzle-orm";
import { db } from "@/db";
import { schoolPerson, staffAudit, staffPositionAssignment, staffServicePeriod, staffProfile, staffRelationship, tenant, user } from "@/db/schema";
import type { SchoolPerson, StaffMasterDataStore, StaffRecord } from "@/lib/staff-master-data";

async function listWith(executor: Pick<typeof db, "select">, tenantId: string): Promise<StaffRecord[]> {
  const [rows, blockers, periods, assignments] = await Promise.all([executor.select({ person: schoolPerson, staff: staffProfile, accountEnabled: user.emailVerified }).from(staffProfile).innerJoin(schoolPerson, and(eq(schoolPerson.tenantId, staffProfile.tenantId), eq(schoolPerson.id, staffProfile.personId))).leftJoin(user, and(eq(user.tenantId, tenantId), eq(user.id, schoolPerson.accountUserId))).where(eq(staffProfile.tenantId, tenantId)).orderBy(asc(schoolPerson.normalizedName), asc(staffProfile.id)), executor.select().from(staffRelationship).where(and(eq(staffRelationship.tenantId, tenantId), eq(staffRelationship.active, true))), executor.select().from(staffServicePeriod).where(eq(staffServicePeriod.tenantId, tenantId)).orderBy(asc(staffServicePeriod.startedAt), asc(staffServicePeriod.id)), executor.select().from(staffPositionAssignment).where(eq(staffPositionAssignment.tenantId, tenantId)).orderBy(asc(staffPositionAssignment.startedAt), asc(staffPositionAssignment.id))]);
  return rows.map(({ person, staff, accountEnabled }) => { const positionAssignments = assignments.filter((item) => item.staffId === staff.id); return { person: { ...person, accountActive: Boolean(accountEnabled) }, staff, workUnit: positionAssignments.find((item) => item.endedAt === null)?.workUnit ?? null, positionAssignments, servicePeriods: periods.filter((item) => item.staffId === staff.id), archiveBlockers: blockers.filter((item) => item.staffId === staff.id) }; });
}
async function peopleWith(executor: Pick<typeof db, "select">, tenantId: string): Promise<SchoolPerson[]> { const rows = await executor.select({ person: schoolPerson, accountEnabled: user.emailVerified }).from(schoolPerson).leftJoin(user, and(eq(user.tenantId, tenantId), eq(user.id, schoolPerson.accountUserId))).where(eq(schoolPerson.tenantId, tenantId)); return rows.map(({ person, accountEnabled }) => ({ ...person, accountActive: Boolean(accountEnabled) })); }
export const staffMasterDataStore: StaffMasterDataStore = {
  list: (tenantId) => listWith(db, tenantId),
  async listAvailablePeople(tenantId) { const people = await peopleWith(db, tenantId), staffMembers = await db.select({ personId: staffProfile.personId }).from(staffProfile).where(eq(staffProfile.tenantId, tenantId)), profiled = new Set(staffMembers.map((item) => item.personId)); return people.filter((person) => !person.archived && !profiled.has(person.id)); },
  transaction(tenantId, work) { return db.transaction(async (tx) => { await tx.execute(sql`SELECT ${tenant.id} FROM ${tenant} WHERE ${tenant.id} = ${tenantId} FOR UPDATE`); return work({
    listPeople: () => peopleWith(tx, tenantId),
    async listStaffMembers() { return tx.select().from(staffProfile).where(eq(staffProfile.tenantId, tenantId)); },
    async listLifecyclePeriods(staffId) { return tx.select().from(staffServicePeriod).where(and(eq(staffServicePeriod.tenantId, tenantId), eq(staffServicePeriod.staffId, staffId))).orderBy(asc(staffServicePeriod.startedAt), asc(staffServicePeriod.id)); },
    async listPositionAssignments(staffId) { return tx.select().from(staffPositionAssignment).where(and(eq(staffPositionAssignment.tenantId, tenantId), eq(staffPositionAssignment.staffId, staffId))).orderBy(asc(staffPositionAssignment.startedAt), asc(staffPositionAssignment.id)); },
    async appendPositionAssignment(value) { if (value.tenantId !== tenantId) throw new Error("Cross-Tenant position write denied"); await tx.insert(staffPositionAssignment).values(value); },
    async closePositionAssignment(id, endedAt) { const result = await tx.update(staffPositionAssignment).set({ endedAt }).where(and(eq(staffPositionAssignment.tenantId, tenantId), eq(staffPositionAssignment.id, id), sql`${staffPositionAssignment.endedAt} IS NULL`)); return result[0].affectedRows === 1; },
    async listRelationshipBlockers(staffId) { return tx.select().from(staffRelationship).where(and(eq(staffRelationship.tenantId, tenantId), eq(staffRelationship.staffId, staffId), eq(staffRelationship.active, true))); },
    async appendLifecyclePeriod(value) { if (value.tenantId !== tenantId) throw new Error("Cross-Tenant lifecycle write denied"); await tx.insert(staffServicePeriod).values(value); },
    async closeLifecyclePeriod(id, endedAt) { const result = await tx.update(staffServicePeriod).set({ endedAt }).where(and(eq(staffServicePeriod.tenantId, tenantId), eq(staffServicePeriod.id, id), sql`${staffServicePeriod.endedAt} IS NULL`)); return result[0].affectedRows === 1; },
    async savePerson(value, expectedVersion) { if (value.tenantId !== tenantId) throw new Error("Cross-Tenant person write denied"); const { accountActive, ...persisted } = value; void accountActive; if (expectedVersion === null) { await tx.insert(schoolPerson).values(persisted); return true; } const result = await tx.update(schoolPerson).set(persisted).where(and(eq(schoolPerson.tenantId, tenantId), eq(schoolPerson.id, value.id), eq(schoolPerson.version, expectedVersion))); return result[0].affectedRows === 1; },
    async saveStaff(value, expectedVersion) { if (value.tenantId !== tenantId) throw new Error("Cross-Tenant staff write denied"); if (expectedVersion === null) { await tx.insert(staffProfile).values(value); return true; } const result = await tx.update(staffProfile).set(value).where(and(eq(staffProfile.tenantId, tenantId), eq(staffProfile.id, value.id), eq(staffProfile.version, expectedVersion))); return result[0].affectedRows === 1; },
    async appendAudit(value) { if (value.tenantId !== tenantId) throw new Error("Cross-Tenant audit write denied"); const [actor] = await tx.select({ id: user.id }).from(user).where(and(eq(user.id, value.actorUserId), eq(user.tenantId, tenantId))).limit(1); if (!actor) throw new Error("Staff audit actor is not a Tenant member"); await tx.insert(staffAudit).values(value); },
  }); }); },
};
