import type { MasterDataPrincipal } from "@/lib/tenant-master-data-access";

export const STAFF_STATUSES = ["active", "leave", "ended"] as const;
export const STAFF_EMPLOYMENT_TYPES = ["civil-servant", "government-contract", "foundation-permanent", "foundation-contract", "honorary", "other"] as const;
export const STAFF_POSITIONS = ["administration", "finance", "library", "laboratory", "security", "cleaning", "other"] as const;
export const SCHOOL_PERSON_RELIGIONS = ["islam", "protestant", "catholic", "hindu", "buddhist", "confucian", "belief", "other"] as const;
export type StaffStatus = (typeof STAFF_STATUSES)[number];
export type StaffEmploymentType = (typeof STAFF_EMPLOYMENT_TYPES)[number];
export type StaffPosition = (typeof STAFF_POSITIONS)[number];
export type Gender = "male" | "female";
export type SchoolPerson = Readonly<{ id: string; tenantId: string; fullName: string; normalizedName: string; preferredName: string | null; birthPlace: string; normalizedBirthPlace: string; birthDate: string; gender: Gender; nik: string | null; nip: string | null; religion: string | null; street: string; village: string | null; district: string | null; city: string | null; province: string | null; postalCode: string | null; phone: string | null; email: string | null; accountUserId: string | null; accountActive: boolean; archived: boolean; version: number; createdAt: Date; updatedAt: Date }>;
export type StaffProfile = Readonly<{ id: string; tenantId: string; personId: string; staffNumber: string; normalizedStaffNumber: string; position: StaffPosition; positionOther: string | null; employmentType: StaffEmploymentType; employmentTypeOther: string | null; serviceStartDate: string; status: StaffStatus; archived: boolean; archivedAt?: Date | null; archiveReason?: string | null; version: number; createdAt: Date; updatedAt: Date }>;
export type StaffPositionAssignment = Readonly<{ id: string; tenantId: string; staffId: string; position: StaffPosition; positionOther: string | null; workUnit: string | null; notes: string | null; startedAt: string; endedAt: string | null; createdByUserId: string; createdAt: Date }>;
export type StaffLifecyclePeriod = Readonly<{ id: string; tenantId: string; staffId: string; status: StaffStatus; startedAt: string; endedAt: string | null; reason: string; notes: string | null; corrected: boolean; createdByUserId: string; createdAt: Date }>;
export type StaffRelationshipBlocker = Readonly<{ id: string; tenantId: string; staffId: string; kind: string; label: string; active: boolean }>;
export type StaffRecord = Readonly<{ person: SchoolPerson; staff: StaffProfile; workUnit: string | null; positionAssignments?: readonly StaffPositionAssignment[]; servicePeriods?: readonly StaffLifecyclePeriod[]; archiveBlockers?: readonly StaffRelationshipBlocker[] }>;
export type StaffAudit = Readonly<{ id: string; tenantId: string; personId: string; staffId: string | null; actorUserId: string; operation: "created-person" | "created-staff" | "attached-staff" | "edited" | "status-transitioned" | "service-corrected" | "archive-denied" | "archived" | "reactivated"; fromPersonVersion: number; toPersonVersion: number; fromStaffVersion: number; toStaffVersion: number; sensitiveBefore: { nik: string | null; nip: string | null; staffNumber: string | null; position: string | null } | null; sensitiveAfter: { nik: string | null; nip: string | null; staffNumber: string | null; position: string | null } | null; lifecycleBefore?: { status: StaffStatus; effectiveDate: string } | null; lifecycleAfter?: { status: StaffStatus; effectiveDate: string } | null; reason?: string | null; occurredAt: Date }>;
export interface StaffTransaction { listPeople(): Promise<SchoolPerson[]>; listStaffMembers(): Promise<StaffProfile[]>; listLifecyclePeriods(staffId: string): Promise<StaffLifecyclePeriod[]>; listPositionAssignments(staffId: string): Promise<StaffPositionAssignment[]>; appendPositionAssignment(value: StaffPositionAssignment): Promise<void>; closePositionAssignment(id: string, endedAt: string): Promise<boolean>; listRelationshipBlockers(staffId: string): Promise<StaffRelationshipBlocker[]>; appendLifecyclePeriod(value: StaffLifecyclePeriod): Promise<void>; closeLifecyclePeriod(id: string, endedAt: string): Promise<boolean>; savePerson(value: SchoolPerson, expectedVersion: number | null): Promise<boolean>; saveStaff(value: StaffProfile, expectedVersion: number | null): Promise<boolean>; appendAudit(value: StaffAudit): Promise<void> }
export interface StaffMasterDataStore { list(tenantId: string): Promise<StaffRecord[]>; listAvailablePeople(tenantId: string): Promise<SchoolPerson[]>; transaction<T>(tenantId: string, work: (transaction: StaffTransaction) => Promise<T>): Promise<T> }
export type StaffInput = Readonly<{ fullName: string; preferredName?: string; birthPlace: string; birthDate: string; gender: string; nik?: string; nip?: string; religion?: string; street: string; village?: string; district?: string; city?: string; province?: string; postalCode?: string; phone?: string; email?: string; staffNumber: string; position: string; positionOther?: string; employmentType: string; employmentTypeOther?: string; serviceStartDate: string; assignmentStatus: string; workUnit?: string; notes?: string; positionEffectiveDate?: string; existingPersonId?: string; confirmDistinct?: boolean }>;
type FailureCode = "read-only" | "invalid-input" | "duplicate-nik" | "duplicate-nip" | "duplicate-staffNumber" | "duplicate-position" | "identifier-conflict" | "link-required" | "duplicate-profile" | "possible-duplicate" | "not-found" | "conflict" | "archived" | "invalid-transition" | "invalid-effective-date" | "future-transition" | "service-correction-required" | "active-status" | "relationship-blocked" | "not-archived";
const failure = (code: FailureCode, extra?: object) => ({ ok: false, code, ...extra } as const);
const collapse = (value: string | undefined) => (value ?? "").trim().replace(/\s+/g, " ");
const optional = (value: string | undefined) => collapse(value) || null;
const digits = (value: string | undefined) => collapse(value).replace(/[^0-9]/g, "") || null;
const normalizePhone = (value: string | undefined) => { const raw = collapse(value); if (!raw) return null; const prefix = raw.startsWith("+") ? "+" : ""; return prefix + raw.replace(/\D/g, ""); };
const validDate = (value: string) => /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(Date.parse(`${value}T00:00:00Z`));
function normalized(input: StaffInput, today: string) {
  const fullName = collapse(input.fullName), preferredName = optional(input.preferredName), birthPlace = collapse(input.birthPlace), birthDate = collapse(input.birthDate), street = collapse(input.street), nik = digits(input.nik), nip = digits(input.nip), staffNumber = collapse(input.staffNumber), normalizedStaffNumber = staffNumber.toLocaleLowerCase("id-ID"), position = collapse(input.position), positionOther = optional(input.positionOther), phone = normalizePhone(input.phone), email = optional(input.email)?.toLocaleLowerCase("id-ID") ?? null, religion = optional(input.religion), serviceStartDate = collapse(input.serviceStartDate), employmentType = collapse(input.employmentType), employmentTypeOther = optional(input.employmentTypeOther), assignmentStatus = collapse(input.assignmentStatus), workUnit = optional(input.workUnit), notes = optional(input.notes);
  if (fullName.length < 2 || fullName.length > 150 || birthPlace.length < 2 || birthPlace.length > 100 || !["male", "female"].includes(input.gender) || religion && !SCHOOL_PERSON_RELIGIONS.includes(religion as (typeof SCHOOL_PERSON_RELIGIONS)[number]) || !street || !validDate(birthDate) || birthDate > today || !validDate(serviceStartDate) || !staffNumber || !STAFF_POSITIONS.includes(position as StaffPosition) || position === "other" && !positionOther || !STAFF_EMPLOYMENT_TYPES.includes(employmentType as StaffEmploymentType) || employmentType === "other" && !employmentTypeOther || !STAFF_STATUSES.includes(assignmentStatus as StaffStatus) || nik && nik.length !== 16 || nip && nip.length !== 18 || email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) || phone && !/^\+?\d{7,15}$/.test(phone)) return null;
  return { person: { fullName, normalizedName: fullName.toLocaleLowerCase("id-ID"), preferredName, birthPlace, normalizedBirthPlace: birthPlace.toLocaleLowerCase("id-ID"), birthDate, gender: input.gender as Gender, nik, nip, religion: optional(input.religion), street, village: optional(input.village), district: optional(input.district), city: optional(input.city), province: optional(input.province), postalCode: optional(input.postalCode), phone, email }, staff: { staffNumber, normalizedStaffNumber, position: position as StaffPosition, positionOther, employmentType: employmentType as StaffEmploymentType, employmentTypeOther, serviceStartDate, status: assignmentStatus as StaffStatus }, assignment: { position: position as StaffPosition, positionOther, workUnit, notes } };
}
const compatible = (person: SchoolPerson, value: NonNullable<ReturnType<typeof normalized>>["person"]) => person.normalizedName === value.normalizedName && person.birthDate === value.birthDate && person.normalizedBirthPlace === value.normalizedBirthPlace;
const sensitive = (person: SchoolPerson, staff?: StaffProfile | null) => ({ nik: person.nik, nip: person.nip, staffNumber: staff?.staffNumber ?? null, position: staff?.position ?? null });
export function createStaffMasterDataService(dependencies: { store: StaffMasterDataStore; id?: () => string; now?: () => Date }) {
  const id = dependencies.id ?? (() => crypto.randomUUID()), now = dependencies.now ?? (() => new Date());
  return {
    list(principal: MasterDataPrincipal) { return dependencies.store.list(principal.tenantId); },
    listAvailablePeople(principal: MasterDataPrincipal) { return dependencies.store.listAvailablePeople(principal.tenantId); },
    create(principal: MasterDataPrincipal, input: StaffInput) {
      if (!principal.capabilities.write) return Promise.resolve(failure("read-only"));
      const timestamp = now(), value = normalized(input, timestamp.toISOString().slice(0, 10)); if (!value) return Promise.resolve(failure("invalid-input"));
      return dependencies.store.transaction(principal.tenantId, async (tx) => {
        const people = await tx.listPeople(), staffMembers = await tx.listStaffMembers();
        if (staffMembers.some((item) => item.normalizedStaffNumber === value.staff.normalizedStaffNumber)) return failure("duplicate-staffNumber");

        const identifiers = people.filter((item) => value.person.nik && item.nik === value.person.nik || value.person.nip && item.nip === value.person.nip);
        if (identifiers.some((item) => !compatible(item, value.person))) return failure("identifier-conflict");
        const candidate = input.existingPersonId ? people.find((item) => item.id === input.existingPersonId) : identifiers[0];
        if (input.existingPersonId && (!candidate || !compatible(candidate, value.person))) return failure("not-found");
        if (!input.existingPersonId && candidate) return failure("link-required", { candidatePersonIds: [candidate.id] });
        if (candidate && staffMembers.some((item) => item.personId === candidate.id)) return failure("duplicate-profile");
        const similar = people.filter((item) => compatible(item, value.person) || value.person.email && item.email === value.person.email || value.person.phone && item.phone === value.person.phone);
        if (!candidate && similar.length && !input.confirmDistinct) return failure("possible-duplicate", { candidatePersonIds: similar.map((item) => item.id) });
        const person: SchoolPerson = candidate ?? { id: id(), tenantId: principal.tenantId, ...value.person, accountUserId: null, accountActive: false, archived: false, version: 1, createdAt: timestamp, updatedAt: timestamp };
        if (person.archived) return failure("archived");
        const staff: StaffProfile = { id: id(), tenantId: principal.tenantId, personId: person.id, ...value.staff, archived: false, version: 1, createdAt: timestamp, updatedAt: timestamp };
        if (!candidate && !await tx.savePerson(person, null)) return failure("conflict");
        if (!await tx.saveStaff(staff, null)) return failure("conflict");
        await tx.appendLifecyclePeriod({ id: id(), tenantId: principal.tenantId, staffId: staff.id, status: staff.status, startedAt: staff.serviceStartDate, endedAt: null, reason: "Penerimaan Staf", notes: null, corrected: false, createdByUserId: principal.userId, createdAt: timestamp });
        await tx.appendPositionAssignment({ id: id(), tenantId: principal.tenantId, staffId: staff.id, ...value.assignment, startedAt: staff.serviceStartDate, endedAt: null, createdByUserId: principal.userId, createdAt: timestamp });
        if (!candidate) await tx.appendAudit({ id: id(), tenantId: principal.tenantId, personId: person.id, staffId: null, actorUserId: principal.userId, operation: "created-person", fromPersonVersion: 0, toPersonVersion: 1, fromStaffVersion: 0, toStaffVersion: 0, sensitiveBefore: null, sensitiveAfter: sensitive(person), occurredAt: timestamp });
        await tx.appendAudit({ id: id(), tenantId: principal.tenantId, personId: person.id, staffId: staff.id, actorUserId: principal.userId, operation: candidate ? "attached-staff" : "created-staff", fromPersonVersion: person.version, toPersonVersion: person.version, fromStaffVersion: 0, toStaffVersion: 1, sensitiveBefore: null, sensitiveAfter: sensitive(person, staff), occurredAt: timestamp });
        return { ok: true, record: { person, staff, workUnit: null } } as const;
      });
    },
    async transition(principal: MasterDataPrincipal, staffId: string, input: { toStatus: StaffStatus; effectiveDate: string; reason: string; notes?: string; expectedVersion: number }) {
      if (!principal.capabilities.write) return failure("read-only"); const timestamp = now(), today = timestamp.toISOString().slice(0, 10), reason = collapse(input.reason), notes = optional(input.notes);
      if (!validDate(input.effectiveDate) || !reason || input.expectedVersion < 1) return failure("invalid-input"); if (input.effectiveDate > today) return failure("future-transition");
      return dependencies.store.transaction(principal.tenantId, async (tx) => {
        const staffMembers = await tx.listStaffMembers(), staff = staffMembers.find((item) => item.id === staffId); if (!staff) return failure("not-found"); if (staff.archived) return failure("archived"); if (staff.version !== input.expectedVersion) return failure("conflict"); if (input.effectiveDate < staff.serviceStartDate) return failure("invalid-effective-date");
        const allowed: readonly StaffStatus[] = staff.status === "active" ? ["leave", "ended"] : staff.status === "leave" ? ["active", "ended"] : ["active"]; if (!allowed.includes(input.toStatus)) return failure("invalid-transition");
        const periods = await tx.listLifecyclePeriods(staffId), current = periods.find((item) => item.endedAt === null); if (!current || input.effectiveDate < current.startedAt) return failure("invalid-effective-date");
        const person = (await tx.listPeople()).find((item) => item.id === staff.personId); if (!person) return failure("not-found"); if (!await tx.closeLifecyclePeriod(current.id, input.effectiveDate)) return failure("conflict");
        const updated = { ...staff, status: input.toStatus, version: staff.version + 1, updatedAt: timestamp }; if (!await tx.saveStaff(updated, staff.version)) return failure("conflict");
        await tx.appendLifecyclePeriod({ id: id(), tenantId: principal.tenantId, staffId, status: input.toStatus, startedAt: input.effectiveDate, endedAt: null, reason, notes, corrected: false, createdByUserId: principal.userId, createdAt: timestamp });
        await tx.appendAudit({ id: id(), tenantId: principal.tenantId, personId: person.id, staffId, actorUserId: principal.userId, operation: "status-transitioned", fromPersonVersion: person.version, toPersonVersion: person.version, fromStaffVersion: staff.version, toStaffVersion: updated.version, sensitiveBefore: null, sensitiveAfter: null, lifecycleBefore: { status: staff.status, effectiveDate: current.startedAt }, lifecycleAfter: { status: input.toStatus, effectiveDate: input.effectiveDate }, reason, occurredAt: timestamp }); return { ok: true, record: updated } as const;
      });
    },
    async correctService(principal: MasterDataPrincipal, staffId: string, input: { toStatus: Exclude<StaffStatus, "ended">; effectiveDate: string; reason: string; notes?: string; expectedVersion: number }) {
      if (!principal.capabilities.write) return failure("read-only"); const timestamp = now(), reason = collapse(input.reason); if (!reason || !validDate(input.effectiveDate) || input.effectiveDate > timestamp.toISOString().slice(0, 10)) return failure("invalid-input");
      return dependencies.store.transaction(principal.tenantId, async (tx) => { const staff = (await tx.listStaffMembers()).find((item) => item.id === staffId); if (!staff) return failure("not-found"); if (staff.archived) return failure("archived"); if (staff.version !== input.expectedVersion) return failure("conflict"); if (staff.status !== "ended" || input.effectiveDate < staff.serviceStartDate) return failure("invalid-transition"); const periods = await tx.listLifecyclePeriods(staffId), current = periods.find((item) => item.endedAt === null); if (!current || current.status !== "ended" || input.effectiveDate < current.startedAt) return failure("invalid-effective-date"); const person = (await tx.listPeople()).find((item) => item.id === staff.personId); if (!person) return failure("not-found"); if (!await tx.closeLifecyclePeriod(current.id, input.effectiveDate)) return failure("conflict"); const updated = { ...staff, status: input.toStatus, version: staff.version + 1, updatedAt: timestamp }; if (!await tx.saveStaff(updated, staff.version)) return failure("conflict"); await tx.appendLifecyclePeriod({ id: id(), tenantId: principal.tenantId, staffId, status: input.toStatus, startedAt: input.effectiveDate, endedAt: null, reason, notes: optional(input.notes), corrected: true, createdByUserId: principal.userId, createdAt: timestamp }); await tx.appendAudit({ id: id(), tenantId: principal.tenantId, personId: person.id, staffId, actorUserId: principal.userId, operation: "service-corrected", fromPersonVersion: person.version, toPersonVersion: person.version, fromStaffVersion: staff.version, toStaffVersion: updated.version, sensitiveBefore: null, sensitiveAfter: null, lifecycleBefore: { status: "ended", effectiveDate: current.startedAt }, lifecycleAfter: { status: input.toStatus, effectiveDate: input.effectiveDate }, reason, occurredAt: timestamp }); return { ok: true, record: updated } as const; });
    },
    async archive(principal: MasterDataPrincipal, staffId: string, input: { reason: string; expectedVersion: number }) {
      if (!principal.capabilities.write) return failure("read-only"); const timestamp = now(), reason = collapse(input.reason); if (!reason || input.expectedVersion < 1) return failure("invalid-input"); return dependencies.store.transaction(principal.tenantId, async (tx) => { const staff = (await tx.listStaffMembers()).find((item) => item.id === staffId); if (!staff) return failure("not-found"); if (staff.version !== input.expectedVersion) return failure("conflict"); if (staff.archived) return failure("archived"); const person = (await tx.listPeople()).find((item) => item.id === staff.personId); if (!person) return failure("not-found"); if (staff.status !== "ended") { await tx.appendAudit({ id: id(), tenantId: principal.tenantId, personId: person.id, staffId, actorUserId: principal.userId, operation: "archive-denied", fromPersonVersion: person.version, toPersonVersion: person.version, fromStaffVersion: staff.version, toStaffVersion: staff.version, sensitiveBefore: null, sensitiveAfter: null, reason: "Status Staf belum Berakhir", occurredAt: timestamp }); return failure("active-status"); } const blockers = await tx.listRelationshipBlockers(staffId); if (blockers.length) { await tx.appendAudit({ id: id(), tenantId: principal.tenantId, personId: person.id, staffId, actorUserId: principal.userId, operation: "archive-denied", fromPersonVersion: person.version, toPersonVersion: person.version, fromStaffVersion: staff.version, toStaffVersion: staff.version, sensitiveBefore: null, sensitiveAfter: null, reason: blockers.map((item) => item.label).join("; "), occurredAt: timestamp }); return failure("relationship-blocked", { blockers }); } const updated = { ...staff, archived: true, archivedAt: timestamp, archiveReason: reason, version: staff.version + 1, updatedAt: timestamp }; if (!await tx.saveStaff(updated, staff.version)) return failure("conflict"); await tx.appendAudit({ id: id(), tenantId: principal.tenantId, personId: person.id, staffId, actorUserId: principal.userId, operation: "archived", fromPersonVersion: person.version, toPersonVersion: person.version, fromStaffVersion: staff.version, toStaffVersion: updated.version, sensitiveBefore: null, sensitiveAfter: null, reason, occurredAt: timestamp }); return { ok: true, record: updated, warnings: person.accountActive ? ["Akun Pengguna tertaut masih aktif."] : [] } as const; });
    },
    async reactivate(principal: MasterDataPrincipal, staffId: string, input: { reason: string; expectedVersion: number }) {
      if (!principal.capabilities.write) return failure("read-only"); const timestamp = now(), reason = collapse(input.reason); if (!reason || input.expectedVersion < 1) return failure("invalid-input"); return dependencies.store.transaction(principal.tenantId, async (tx) => { const staffMembers = await tx.listStaffMembers(), staff = staffMembers.find((item) => item.id === staffId); if (!staff) return failure("not-found"); if (staff.version !== input.expectedVersion) return failure("conflict"); if (!staff.archived) return failure("not-archived"); const people = await tx.listPeople(), person = people.find((item) => item.id === staff.personId); if (!person) return failure("not-found"); if (staffMembers.some((item) => item.id !== staff.id && item.normalizedStaffNumber === staff.normalizedStaffNumber)) return failure("duplicate-staffNumber"); if (await tx.listRelationshipBlockers(staffId).then((items) => items.length)) return failure("relationship-blocked"); const updated = { ...staff, archived: false, archivedAt: null, archiveReason: null, version: staff.version + 1, updatedAt: timestamp }; if (!await tx.saveStaff(updated, staff.version)) return failure("conflict"); await tx.appendAudit({ id: id(), tenantId: principal.tenantId, personId: person.id, staffId, actorUserId: principal.userId, operation: "reactivated", fromPersonVersion: person.version, toPersonVersion: person.version, fromStaffVersion: staff.version, toStaffVersion: updated.version, sensitiveBefore: null, sensitiveAfter: null, reason, occurredAt: timestamp }); return { ok: true, record: updated } as const; });
    },
    edit(principal: MasterDataPrincipal, staffId: string, input: StaffInput, personVersion: number, staffVersion: number) {
      if (!principal.capabilities.write) return Promise.resolve(failure("read-only")); const timestamp = now(), value = normalized(input, timestamp.toISOString().slice(0, 10)); if (!value || personVersion < 1 || staffVersion < 1) return Promise.resolve(failure("invalid-input"));
      return dependencies.store.transaction(principal.tenantId, async (tx) => {
        const people = await tx.listPeople(), staffMembers = await tx.listStaffMembers(), currentStaff = staffMembers.find((item) => item.id === staffId), currentPerson = currentStaff && people.find((item) => item.id === currentStaff.personId);
        if (!currentStaff || !currentPerson) return failure("not-found"); if (currentPerson.version !== personVersion || currentStaff.version !== staffVersion) return failure("conflict"); if (currentStaff.archived || currentPerson.archived) return failure("archived");
        if (people.some((item) => item.id !== currentPerson.id && value.person.nik && item.nik === value.person.nik)) return failure("duplicate-nik"); if (people.some((item) => item.id !== currentPerson.id && value.person.nip && item.nip === value.person.nip)) return failure("duplicate-nip"); if (staffMembers.some((item) => item.id !== currentStaff.id && item.normalizedStaffNumber === value.staff.normalizedStaffNumber)) return failure("duplicate-staffNumber");
        const person: SchoolPerson = { ...currentPerson, ...value.person, version: personVersion + 1, updatedAt: timestamp }, staff: StaffProfile = { ...currentStaff, ...value.staff, version: staffVersion + 1, updatedAt: timestamp };
        const positionChanged = currentStaff.position !== staff.position || currentStaff.positionOther !== staff.positionOther || optional(input.workUnit) !== (await tx.listPositionAssignments(staffId)).find((item) => item.endedAt === null)?.workUnit;
        if (positionChanged) { const effectiveDate = collapse(input.positionEffectiveDate); if (!validDate(effectiveDate) || effectiveDate < currentStaff.serviceStartDate || effectiveDate > timestamp.toISOString().slice(0, 10)) return failure("invalid-effective-date"); const current = (await tx.listPositionAssignments(staffId)).find((item) => item.endedAt === null); if (!current || effectiveDate < current.startedAt || !await tx.closePositionAssignment(current.id, effectiveDate)) return failure("conflict"); await tx.appendPositionAssignment({ id: id(), tenantId: principal.tenantId, staffId, ...value.assignment, startedAt: effectiveDate, endedAt: null, createdByUserId: principal.userId, createdAt: timestamp }); }
        if (!await tx.savePerson(person, personVersion) || !await tx.saveStaff(staff, staffVersion)) return failure("conflict");
        await tx.appendAudit({ id: id(), tenantId: principal.tenantId, personId: person.id, staffId: staff.id, actorUserId: principal.userId, operation: "edited", fromPersonVersion: personVersion, toPersonVersion: person.version, fromStaffVersion: staffVersion, toStaffVersion: staff.version, sensitiveBefore: sensitive(currentPerson, currentStaff), sensitiveAfter: sensitive(person, staff), occurredAt: timestamp });
        return { ok: true, record: { person, staff, workUnit: null } } as const;
      });
    },
  };
}
