import assert from "node:assert/strict";
import test from "node:test";
import { createStudentOrganizationService, type StudentOrganizationState, type StudentOrganizationStore } from "@/lib/student-organization";
import type { MasterDataPrincipal } from "@/lib/tenant-master-data-access";

const principal: MasterDataPrincipal = { userId: "admin-1", tenantId: "tenant-1", role: "school-admin", capabilities: { read: true, write: true, downloadTemplate: true } };
function fixture() {
  const state: StudentOrganizationState = { organizations: [], periods: [], memberships: [], leaderships: [], students: [{ id: "student-1", tenantId: "tenant-1", name: "Ayu", active: true, archived: false }], locations: [{ id: "location-1", tenantId: "tenant-1", name: "Ruang OSIS", archived: false }], events: [] };
  let sequence = 0;
  const store: StudentOrganizationStore = { async state(tenantId) { return structuredClone({ ...state, organizations: state.organizations.filter(x => x.tenantId === tenantId), periods: state.periods.filter(x => x.tenantId === tenantId), memberships: state.memberships.filter(x => x.tenantId === tenantId), leaderships: state.leaderships.filter(x => x.tenantId === tenantId), students: state.students.filter(x => x.tenantId === tenantId), locations: state.locations.filter(x => x.tenantId === tenantId), events: state.events.filter(x => x.tenantId === tenantId) }); }, async transaction(tenantId, work) { const result = await work(state); return result; } };
  return { state, service: createStudentOrganizationService({ store, id: () => `id-${++sequence}`, now: () => new Date("2026-07-20T00:00:00Z") }) };
}
const organizationInput = { name: "Organisasi Siswa Intra Sekolah", abbreviation: "OSIS", code: "osis", description: "Wadah siswa", foundingDate: "1990-01-01", secretariatLocationId: "location-1" };

test("creates a Tenant-owned stable organization and reserves its normalized code after archive", async () => { const f = fixture(), created = await f.service.createOrganization(principal, { ...organizationInput, secretariatLocationId: null }); assert.equal(created.ok, true); if (!created.ok) return; assert.equal(created.record.code, "OSIS"); assert.deepEqual(await f.service.list({ ...principal, tenantId: "tenant-2" }), { organizations: [], periods: [], memberships: [], leaderships: [], students: [], locations: [], events: [] }); assert.equal((await f.service.archiveOrganization(principal, created.record.id, { expectedVersion: 1, reason: "Tidak digunakan" })).ok, true); assert.deepEqual(await f.service.createOrganization(principal, { ...organizationInput, name: "OSIS Baru" }), { ok: false, code: "duplicate-code" }); });

test("validates period dates and only allows future planning in planned periods", async () => { const f = fixture(), org = await f.service.createOrganization(principal, organizationInput); if (!org.ok) return; assert.deepEqual(await f.service.createPeriod(principal, { organizationId: org.record.id, name: "2026", startDate: "2026-08-01", endDate: "2026-07-01" }), { ok: false, code: "invalid-input" }); const period = await f.service.createPeriod(principal, { organizationId: org.record.id, name: "2026/2027", startDate: "2026-08-01", endDate: "2027-07-31" }); assert.equal(period.ok, true); if (!period.ok) return; assert.equal((await f.service.addMembership(principal, { organizationId: org.record.id, studentId: "student-1", startDate: "2026-08-01", endDate: null, reason: "Bergabung" })).ok, true); assert.equal((await f.service.assignLeadership(principal, { periodId: period.record.id, studentId: "student-1", positionName: "Ketua", allowsMultipleHolders: false, startDate: "2026-08-01", endDate: null, reason: "Terpilih" })).ok, true); assert.equal((await f.service.transitionPeriod(principal, period.record.id, "activate", { expectedVersion: 1, reason: "Dilantik" })).ok, true); assert.deepEqual(await f.service.addMembership(principal, { organizationId: org.record.id, studentId: "student-1", startDate: "2027-01-01", endDate: null, reason: "Rencana" }), { ok: false, code: "future-date-not-allowed" }); });

test("leadership requires effective membership, honors position multiplicity, and ends independently", async () => { const f = fixture(), org = await f.service.createOrganization(principal, organizationInput); if (!org.ok) return; const period = await f.service.createPeriod(principal, { organizationId: org.record.id, name: "2026", startDate: "2026-01-01", endDate: "2026-12-31" }); if (!period.ok) return; assert.deepEqual(await f.service.assignLeadership(principal, { periodId: period.record.id, studentId: "student-1", positionName: "Ketua", allowsMultipleHolders: false, startDate: "2026-01-01", endDate: null, reason: "Dipilih" }), { ok: false, code: "membership-required" }); await f.service.addMembership(principal, { organizationId: org.record.id, studentId: "student-1", startDate: "2026-01-01", endDate: null, reason: "Bergabung" }); const leader = await f.service.assignLeadership(principal, { periodId: period.record.id, studentId: "student-1", positionName: "Ketua", allowsMultipleHolders: false, startDate: "2026-01-01", endDate: null, reason: "Dipilih" }); assert.equal(leader.ok, true); if (!leader.ok) return; assert.deepEqual(await f.service.assignLeadership(principal, { periodId: period.record.id, studentId: "student-1", positionName: "Ketua", allowsMultipleHolders: true, startDate: "2026-02-01", endDate: null, reason: "Duplikat" }), { ok: false, code: "position-multiplicity-conflict" }); assert.equal((await f.service.endLeadership(principal, leader.record.id, { effectiveDate: "2026-06-01", reason: "Pergantian" })).ok, true); assert.equal(f.state.memberships[0]?.endedAt, null); });

test("terminal correction is audited and archive enumerates blockers without cascading", async () => { const f = fixture(), org = await f.service.createOrganization(principal, organizationInput); if (!org.ok) return; const period = await f.service.createPeriod(principal, { organizationId: org.record.id, name: "2026", startDate: "2026-01-01", endDate: "2026-12-31" }); if (!period.ok) return; await f.service.transitionPeriod(principal, period.record.id, "activate", { expectedVersion: 1, reason: "Mulai" }); await f.service.transitionPeriod(principal, period.record.id, "complete", { expectedVersion: 2, reason: "Selesai" }); assert.deepEqual(await f.service.transitionPeriod(principal, period.record.id, "activate", { expectedVersion: 3, reason: "Salah" }), { ok: false, code: "terminal-period" }); assert.equal((await f.service.correctCompletedPeriod(principal, period.record.id, { expectedVersion: 3, startDate: "2026-01-01", endDate: "2026-11-30", reason: "Koreksi tanggal" })).ok, true); const blocked = await f.service.archiveOrganization(principal, org.record.id, { expectedVersion: 1, reason: "Arsip" }); assert.equal(blocked.ok, false); if (!blocked.ok && "blockers" in blocked) assert.match(blocked.blockers.join(" "), /Lokasi sekretariat/); assert.equal(f.state.periods.length, 1); assert.ok(f.state.events.some(x => x.operation === "period-corrected")); });
