import { and, asc, eq, sql } from "drizzle-orm";
import { db } from "@/db";
import { classGroup, classMembership, schoolPerson, studentAudit, studentLifecyclePeriod, studentProfile, studentRelationship, tenant, user } from "@/db/schema";
import type { SchoolPerson, StudentMasterDataStore, StudentRecord } from "@/lib/student-master-data";

async function listWith(executor: Pick<typeof db, "select">, tenantId: string): Promise<StudentRecord[]> {
  const [rows, blockers, memberships] = await Promise.all([executor.select({ person: schoolPerson, student: studentProfile, accountEnabled: user.emailVerified }).from(studentProfile).innerJoin(schoolPerson, and(eq(schoolPerson.tenantId, studentProfile.tenantId), eq(schoolPerson.id, studentProfile.personId))).leftJoin(user, and(eq(user.tenantId, tenantId), eq(user.id, schoolPerson.accountUserId))).where(eq(studentProfile.tenantId, tenantId)).orderBy(asc(schoolPerson.normalizedName), asc(studentProfile.id)), executor.select().from(studentRelationship).where(and(eq(studentRelationship.tenantId, tenantId), eq(studentRelationship.active, true))), executor.select({ id: classMembership.id, studentId: classMembership.studentId, classGroupId: classMembership.classGroupId, planned: classMembership.planned, groupName: classGroup.groupName, grade: classGroup.grade }).from(classMembership).innerJoin(classGroup, and(eq(classGroup.tenantId, classMembership.tenantId), eq(classGroup.id, classMembership.classGroupId))).where(and(eq(classMembership.tenantId, tenantId), sql`${classMembership.endedAt} IS NULL`))]);
  return rows.map(({ person, student, accountEnabled }) => { const current = memberships.find((item) => item.studentId === student.id && !item.planned); const membershipBlockers = memberships.filter((item) => item.studentId === student.id).map((item) => ({ id: item.id, tenantId, studentId: student.id, kind: "class-membership", label: `Rombongan Belajar ${item.grade} ${item.groupName}`, active: true })); return { person: { ...person, accountActive: Boolean(accountEnabled) }, student, classGroupName: current ? `${current.grade} ${current.groupName}` : null, archiveBlockers: [...blockers.filter((item) => item.studentId === student.id), ...membershipBlockers] }; });
}
async function peopleWith(executor: Pick<typeof db, "select">, tenantId: string): Promise<SchoolPerson[]> { const rows = await executor.select({ person: schoolPerson, accountEnabled: user.emailVerified }).from(schoolPerson).leftJoin(user, and(eq(user.tenantId, tenantId), eq(user.id, schoolPerson.accountUserId))).where(eq(schoolPerson.tenantId, tenantId)); return rows.map(({ person, accountEnabled }) => ({ ...person, accountActive: Boolean(accountEnabled) })); }
export const studentMasterDataStore: StudentMasterDataStore = {
  list: (tenantId) => listWith(db, tenantId),
  async listAvailablePeople(tenantId) { const people = await peopleWith(db, tenantId), students = await db.select({ personId: studentProfile.personId }).from(studentProfile).where(eq(studentProfile.tenantId, tenantId)), profiled = new Set(students.map((item) => item.personId)); return people.filter((person) => !person.archived && !profiled.has(person.id)); },
  transaction(tenantId, work) { return db.transaction(async (tx) => { await tx.execute(sql`SELECT ${tenant.id} FROM ${tenant} WHERE ${tenant.id} = ${tenantId} FOR UPDATE`); return work({
    listPeople: () => peopleWith(tx, tenantId),
    async listStudents() { return tx.select().from(studentProfile).where(eq(studentProfile.tenantId, tenantId)); },
    async listLifecyclePeriods(studentId) { return tx.select().from(studentLifecyclePeriod).where(and(eq(studentLifecyclePeriod.tenantId, tenantId), eq(studentLifecyclePeriod.studentId, studentId))).orderBy(asc(studentLifecyclePeriod.startedAt), asc(studentLifecyclePeriod.id)); },
    async listRelationshipBlockers(studentId) { return tx.select().from(studentRelationship).where(and(eq(studentRelationship.tenantId, tenantId), eq(studentRelationship.studentId, studentId), eq(studentRelationship.active, true))); },
    async appendLifecyclePeriod(value) { if (value.tenantId !== tenantId) throw new Error("Cross-Tenant lifecycle write denied"); await tx.insert(studentLifecyclePeriod).values(value); },
    async closeLifecyclePeriod(id, endedAt) { const result = await tx.update(studentLifecyclePeriod).set({ endedAt }).where(and(eq(studentLifecyclePeriod.tenantId, tenantId), eq(studentLifecyclePeriod.id, id), sql`${studentLifecyclePeriod.endedAt} IS NULL`)); return result[0].affectedRows === 1; },
    async savePerson(value, expectedVersion) { if (value.tenantId !== tenantId) throw new Error("Cross-Tenant person write denied"); const { accountActive, ...persisted } = value; void accountActive; if (expectedVersion === null) { await tx.insert(schoolPerson).values(persisted); return true; } const result = await tx.update(schoolPerson).set(persisted).where(and(eq(schoolPerson.tenantId, tenantId), eq(schoolPerson.id, value.id), eq(schoolPerson.version, expectedVersion))); return result[0].affectedRows === 1; },
    async saveStudent(value, expectedVersion) { if (value.tenantId !== tenantId) throw new Error("Cross-Tenant student write denied"); if (expectedVersion === null) { await tx.insert(studentProfile).values(value); return true; } const result = await tx.update(studentProfile).set(value).where(and(eq(studentProfile.tenantId, tenantId), eq(studentProfile.id, value.id), eq(studentProfile.version, expectedVersion))); return result[0].affectedRows === 1; },
    async appendAudit(value) { if (value.tenantId !== tenantId) throw new Error("Cross-Tenant audit write denied"); const [actor] = await tx.select({ id: user.id }).from(user).where(and(eq(user.id, value.actorUserId), eq(user.tenantId, tenantId))).limit(1); if (!actor) throw new Error("Student audit actor is not a Tenant member"); await tx.insert(studentAudit).values(value); },
  }); }); },
};
