import { and, asc, eq, sql } from "drizzle-orm";
import { db } from "@/db";
import { schoolPerson, teacherAudit, teacherServicePeriod, teacherProfile, teacherRelationship, tenant, user } from "@/db/schema";
import type { SchoolPerson, TeacherMasterDataStore, TeacherRecord } from "@/lib/teacher-master-data";

async function listWith(executor: Pick<typeof db, "select">, tenantId: string): Promise<TeacherRecord[]> {
  const [rows, blockers, periods] = await Promise.all([executor.select({ person: schoolPerson, teacher: teacherProfile, accountEnabled: user.emailVerified }).from(teacherProfile).innerJoin(schoolPerson, and(eq(schoolPerson.tenantId, teacherProfile.tenantId), eq(schoolPerson.id, teacherProfile.personId))).leftJoin(user, and(eq(user.tenantId, tenantId), eq(user.id, schoolPerson.accountUserId))).where(eq(teacherProfile.tenantId, tenantId)).orderBy(asc(schoolPerson.normalizedName), asc(teacherProfile.id)), executor.select().from(teacherRelationship).where(and(eq(teacherRelationship.tenantId, tenantId), eq(teacherRelationship.active, true))), executor.select().from(teacherServicePeriod).where(eq(teacherServicePeriod.tenantId, tenantId)).orderBy(asc(teacherServicePeriod.startedAt), asc(teacherServicePeriod.id))]);
  return rows.map(({ person, teacher, accountEnabled }) => ({ person: { ...person, accountActive: Boolean(accountEnabled) }, teacher, classGroupName: null, servicePeriods: periods.filter((item) => item.teacherId === teacher.id), archiveBlockers: blockers.filter((item) => item.teacherId === teacher.id) }));
}
async function peopleWith(executor: Pick<typeof db, "select">, tenantId: string): Promise<SchoolPerson[]> { const rows = await executor.select({ person: schoolPerson, accountEnabled: user.emailVerified }).from(schoolPerson).leftJoin(user, and(eq(user.tenantId, tenantId), eq(user.id, schoolPerson.accountUserId))).where(eq(schoolPerson.tenantId, tenantId)); return rows.map(({ person, accountEnabled }) => ({ ...person, accountActive: Boolean(accountEnabled) })); }
export const teacherMasterDataStore: TeacherMasterDataStore = {
  list: (tenantId) => listWith(db, tenantId),
  async listAvailablePeople(tenantId) { const people = await peopleWith(db, tenantId), teachers = await db.select({ personId: teacherProfile.personId }).from(teacherProfile).where(eq(teacherProfile.tenantId, tenantId)), profiled = new Set(teachers.map((item) => item.personId)); return people.filter((person) => !person.archived && !profiled.has(person.id)); },
  transaction(tenantId, work) { return db.transaction(async (tx) => { await tx.execute(sql`SELECT ${tenant.id} FROM ${tenant} WHERE ${tenant.id} = ${tenantId} FOR UPDATE`); return work({
    listPeople: () => peopleWith(tx, tenantId),
    async listTeachers() { return tx.select().from(teacherProfile).where(eq(teacherProfile.tenantId, tenantId)); },
    async listLifecyclePeriods(teacherId) { return tx.select().from(teacherServicePeriod).where(and(eq(teacherServicePeriod.tenantId, tenantId), eq(teacherServicePeriod.teacherId, teacherId))).orderBy(asc(teacherServicePeriod.startedAt), asc(teacherServicePeriod.id)); },
    async listRelationshipBlockers(teacherId) { return tx.select().from(teacherRelationship).where(and(eq(teacherRelationship.tenantId, tenantId), eq(teacherRelationship.teacherId, teacherId), eq(teacherRelationship.active, true))); },
    async appendLifecyclePeriod(value) { if (value.tenantId !== tenantId) throw new Error("Cross-Tenant lifecycle write denied"); await tx.insert(teacherServicePeriod).values(value); },
    async closeLifecyclePeriod(id, endedAt) { const result = await tx.update(teacherServicePeriod).set({ endedAt }).where(and(eq(teacherServicePeriod.tenantId, tenantId), eq(teacherServicePeriod.id, id), sql`${teacherServicePeriod.endedAt} IS NULL`)); return result[0].affectedRows === 1; },
    async savePerson(value, expectedVersion) { if (value.tenantId !== tenantId) throw new Error("Cross-Tenant person write denied"); const { accountActive, ...persisted } = value; void accountActive; if (expectedVersion === null) { await tx.insert(schoolPerson).values(persisted); return true; } const result = await tx.update(schoolPerson).set(persisted).where(and(eq(schoolPerson.tenantId, tenantId), eq(schoolPerson.id, value.id), eq(schoolPerson.version, expectedVersion))); return result[0].affectedRows === 1; },
    async saveTeacher(value, expectedVersion) { if (value.tenantId !== tenantId) throw new Error("Cross-Tenant teacher write denied"); if (expectedVersion === null) { await tx.insert(teacherProfile).values(value); return true; } const result = await tx.update(teacherProfile).set(value).where(and(eq(teacherProfile.tenantId, tenantId), eq(teacherProfile.id, value.id), eq(teacherProfile.version, expectedVersion))); return result[0].affectedRows === 1; },
    async appendAudit(value) { if (value.tenantId !== tenantId) throw new Error("Cross-Tenant audit write denied"); const [actor] = await tx.select({ id: user.id }).from(user).where(and(eq(user.id, value.actorUserId), eq(user.tenantId, tenantId))).limit(1); if (!actor) throw new Error("Teacher audit actor is not a Tenant member"); await tx.insert(teacherAudit).values(value); },
  }); }); },
};
