import type { MasterDataPrincipal } from "@/lib/tenant-master-data-access";

export const TEACHER_STATUSES = ["active", "leave", "ended"] as const;
export const TEACHER_EMPLOYMENT_TYPES = ["civil-servant", "government-contract", "foundation-permanent", "foundation-contract", "honorary"] as const;
export const SCHOOL_PERSON_RELIGIONS = ["islam", "protestant", "catholic", "hindu", "buddhist", "confucian", "belief", "other"] as const;
export type TeacherStatus = (typeof TEACHER_STATUSES)[number];
export type TeacherEmploymentType = (typeof TEACHER_EMPLOYMENT_TYPES)[number];
export type Gender = "male" | "female";
export type SchoolPerson = Readonly<{ id: string; tenantId: string; fullName: string; normalizedName: string; preferredName: string | null; birthPlace: string; normalizedBirthPlace: string; birthDate: string; gender: Gender; nik: string | null; nip: string | null; religion: string | null; street: string; village: string | null; district: string | null; city: string | null; province: string | null; postalCode: string | null; phone: string | null; email: string | null; accountUserId: string | null; accountActive: boolean; archived: boolean; version: number; createdAt: Date; updatedAt: Date }>;
export type TeacherProfile = Readonly<{ id: string; tenantId: string; personId: string; teacherNumber: string; normalizedTeacherNumber: string; nuptk: string | null; employmentType: TeacherEmploymentType; serviceStartDate: string; status: TeacherStatus; archived: boolean; archivedAt?: Date | null; archiveReason?: string | null; version: number; createdAt: Date; updatedAt: Date }>;
export type TeacherLifecyclePeriod = Readonly<{ id: string; tenantId: string; teacherId: string; status: TeacherStatus; startedAt: string; endedAt: string | null; reason: string; notes: string | null; corrected: boolean; createdByUserId: string; createdAt: Date }>;
export type TeacherRelationshipBlocker = Readonly<{ id: string; tenantId: string; teacherId: string; kind: string; label: string; active: boolean }>;
export type TeacherRecord = Readonly<{ person: SchoolPerson; teacher: TeacherProfile; classGroupName: string | null; servicePeriods?: readonly TeacherLifecyclePeriod[]; archiveBlockers?: readonly TeacherRelationshipBlocker[] }>;
export type TeacherAudit = Readonly<{ id: string; tenantId: string; personId: string; teacherId: string | null; actorUserId: string; operation: "created-person" | "created-teacher" | "attached-teacher" | "edited" | "status-transitioned" | "service-corrected" | "archive-denied" | "archived" | "reactivated"; fromPersonVersion: number; toPersonVersion: number; fromTeacherVersion: number; toTeacherVersion: number; sensitiveBefore: { nik: string | null; nip: string | null; teacherNumber: string | null; nuptk: string | null } | null; sensitiveAfter: { nik: string | null; nip: string | null; teacherNumber: string | null; nuptk: string | null } | null; lifecycleBefore?: { status: TeacherStatus; effectiveDate: string } | null; lifecycleAfter?: { status: TeacherStatus; effectiveDate: string } | null; reason?: string | null; occurredAt: Date }>;
export interface TeacherTransaction { listPeople(): Promise<SchoolPerson[]>; listTeachers(): Promise<TeacherProfile[]>; listLifecyclePeriods(teacherId: string): Promise<TeacherLifecyclePeriod[]>; listRelationshipBlockers(teacherId: string): Promise<TeacherRelationshipBlocker[]>; appendLifecyclePeriod(value: TeacherLifecyclePeriod): Promise<void>; closeLifecyclePeriod(id: string, endedAt: string): Promise<boolean>; savePerson(value: SchoolPerson, expectedVersion: number | null): Promise<boolean>; saveTeacher(value: TeacherProfile, expectedVersion: number | null): Promise<boolean>; appendAudit(value: TeacherAudit): Promise<void> }
export interface TeacherMasterDataStore { list(tenantId: string): Promise<TeacherRecord[]>; listAvailablePeople(tenantId: string): Promise<SchoolPerson[]>; transaction<T>(tenantId: string, work: (transaction: TeacherTransaction) => Promise<T>): Promise<T> }
export type TeacherInput = Readonly<{ fullName: string; preferredName?: string; birthPlace: string; birthDate: string; gender: string; nik?: string; nip?: string; religion?: string; street: string; village?: string; district?: string; city?: string; province?: string; postalCode?: string; phone?: string; email?: string; teacherNumber: string; nuptk?: string; employmentType: string; serviceStartDate: string; assignmentStatus: string; existingPersonId?: string; confirmDistinct?: boolean }>;
type FailureCode = "read-only" | "invalid-input" | "duplicate-nik" | "duplicate-nip" | "duplicate-teacherNumber" | "duplicate-nuptk" | "identifier-conflict" | "link-required" | "duplicate-profile" | "possible-duplicate" | "not-found" | "conflict" | "archived" | "invalid-transition" | "invalid-effective-date" | "future-transition" | "service-correction-required" | "active-status" | "relationship-blocked" | "not-archived";
const failure = (code: FailureCode, extra?: object) => ({ ok: false, code, ...extra } as const);
const collapse = (value: string | undefined) => (value ?? "").trim().replace(/\s+/g, " ");
const optional = (value: string | undefined) => collapse(value) || null;
const digits = (value: string | undefined) => collapse(value).replace(/[^0-9]/g, "") || null;
const normalizePhone = (value: string | undefined) => { const raw = collapse(value); if (!raw) return null; const prefix = raw.startsWith("+") ? "+" : ""; return prefix + raw.replace(/\D/g, ""); };
const validDate = (value: string) => /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(Date.parse(`${value}T00:00:00Z`));
function normalized(input: TeacherInput, today: string) {
  const fullName = collapse(input.fullName), preferredName = optional(input.preferredName), birthPlace = collapse(input.birthPlace), birthDate = collapse(input.birthDate), street = collapse(input.street), nik = digits(input.nik), nip = digits(input.nip), teacherNumber = collapse(input.teacherNumber), normalizedTeacherNumber = teacherNumber.toLocaleLowerCase("id-ID"), nuptk = digits(input.nuptk), phone = normalizePhone(input.phone), email = optional(input.email)?.toLocaleLowerCase("id-ID") ?? null, religion = optional(input.religion), serviceStartDate = collapse(input.serviceStartDate), employmentType = collapse(input.employmentType), assignmentStatus = collapse(input.assignmentStatus);
  if (fullName.length < 2 || fullName.length > 150 || birthPlace.length < 2 || birthPlace.length > 100 || !["male", "female"].includes(input.gender) || religion && !SCHOOL_PERSON_RELIGIONS.includes(religion as (typeof SCHOOL_PERSON_RELIGIONS)[number]) || !street || !validDate(birthDate) || birthDate > today || !validDate(serviceStartDate) || !teacherNumber || !TEACHER_EMPLOYMENT_TYPES.includes(employmentType as TeacherEmploymentType) || !TEACHER_STATUSES.includes(assignmentStatus as TeacherStatus) || nik && nik.length !== 16 || nip && nip.length !== 18 || nuptk && nuptk.length !== 16 || email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) || phone && !/^\+?\d{7,15}$/.test(phone)) return null;
  return { person: { fullName, normalizedName: fullName.toLocaleLowerCase("id-ID"), preferredName, birthPlace, normalizedBirthPlace: birthPlace.toLocaleLowerCase("id-ID"), birthDate, gender: input.gender as Gender, nik, nip, religion: optional(input.religion), street, village: optional(input.village), district: optional(input.district), city: optional(input.city), province: optional(input.province), postalCode: optional(input.postalCode), phone, email }, teacher: { teacherNumber, normalizedTeacherNumber, nuptk, employmentType: employmentType as TeacherEmploymentType, serviceStartDate, status: assignmentStatus as TeacherStatus } };
}
const compatible = (person: SchoolPerson, value: NonNullable<ReturnType<typeof normalized>>["person"]) => person.normalizedName === value.normalizedName && person.birthDate === value.birthDate && person.normalizedBirthPlace === value.normalizedBirthPlace;
const sensitive = (person: SchoolPerson, teacher?: TeacherProfile | null) => ({ nik: person.nik, nip: person.nip, teacherNumber: teacher?.teacherNumber ?? null, nuptk: teacher?.nuptk ?? null });
export function createTeacherMasterDataService(dependencies: { store: TeacherMasterDataStore; id?: () => string; now?: () => Date }) {
  const id = dependencies.id ?? (() => crypto.randomUUID()), now = dependencies.now ?? (() => new Date());
  return {
    list(principal: MasterDataPrincipal) { return dependencies.store.list(principal.tenantId); },
    listAvailablePeople(principal: MasterDataPrincipal) { return dependencies.store.listAvailablePeople(principal.tenantId); },
    create(principal: MasterDataPrincipal, input: TeacherInput) {
      if (!principal.capabilities.write) return Promise.resolve(failure("read-only"));
      const timestamp = now(), value = normalized(input, timestamp.toISOString().slice(0, 10)); if (!value) return Promise.resolve(failure("invalid-input"));
      return dependencies.store.transaction(principal.tenantId, async (tx) => {
        const people = await tx.listPeople(), teachers = await tx.listTeachers();
        if (teachers.some((item) => item.normalizedTeacherNumber === value.teacher.normalizedTeacherNumber)) return failure("duplicate-teacherNumber");
        if (value.teacher.nuptk && teachers.some((item) => item.nuptk === value.teacher.nuptk)) return failure("duplicate-nuptk");
        const identifiers = people.filter((item) => value.person.nik && item.nik === value.person.nik || value.person.nip && item.nip === value.person.nip);
        if (identifiers.some((item) => !compatible(item, value.person))) return failure("identifier-conflict");
        const candidate = input.existingPersonId ? people.find((item) => item.id === input.existingPersonId) : identifiers[0];
        if (input.existingPersonId && (!candidate || !compatible(candidate, value.person))) return failure("not-found");
        if (!input.existingPersonId && candidate) return failure("link-required", { candidatePersonIds: [candidate.id] });
        if (candidate && teachers.some((item) => item.personId === candidate.id)) return failure("duplicate-profile");
        const similar = people.filter((item) => compatible(item, value.person) || value.person.email && item.email === value.person.email || value.person.phone && item.phone === value.person.phone);
        if (!candidate && similar.length && !input.confirmDistinct) return failure("possible-duplicate", { candidatePersonIds: similar.map((item) => item.id) });
        const person: SchoolPerson = candidate ?? { id: id(), tenantId: principal.tenantId, ...value.person, accountUserId: null, accountActive: false, archived: false, version: 1, createdAt: timestamp, updatedAt: timestamp };
        if (person.archived) return failure("archived");
        const teacher: TeacherProfile = { id: id(), tenantId: principal.tenantId, personId: person.id, ...value.teacher, archived: false, version: 1, createdAt: timestamp, updatedAt: timestamp };
        if (!candidate && !await tx.savePerson(person, null)) return failure("conflict");
        if (!await tx.saveTeacher(teacher, null)) return failure("conflict");
        await tx.appendLifecyclePeriod({ id: id(), tenantId: principal.tenantId, teacherId: teacher.id, status: teacher.status, startedAt: teacher.serviceStartDate, endedAt: null, reason: "Penerimaan Guru", notes: null, corrected: false, createdByUserId: principal.userId, createdAt: timestamp });
        if (!candidate) await tx.appendAudit({ id: id(), tenantId: principal.tenantId, personId: person.id, teacherId: null, actorUserId: principal.userId, operation: "created-person", fromPersonVersion: 0, toPersonVersion: 1, fromTeacherVersion: 0, toTeacherVersion: 0, sensitiveBefore: null, sensitiveAfter: sensitive(person), occurredAt: timestamp });
        await tx.appendAudit({ id: id(), tenantId: principal.tenantId, personId: person.id, teacherId: teacher.id, actorUserId: principal.userId, operation: candidate ? "attached-teacher" : "created-teacher", fromPersonVersion: person.version, toPersonVersion: person.version, fromTeacherVersion: 0, toTeacherVersion: 1, sensitiveBefore: null, sensitiveAfter: sensitive(person, teacher), occurredAt: timestamp });
        return { ok: true, record: { person, teacher, classGroupName: null } } as const;
      });
    },
    async transition(principal: MasterDataPrincipal, teacherId: string, input: { toStatus: TeacherStatus; effectiveDate: string; reason: string; notes?: string; expectedVersion: number }) {
      if (!principal.capabilities.write) return failure("read-only"); const timestamp = now(), today = timestamp.toISOString().slice(0, 10), reason = collapse(input.reason), notes = optional(input.notes);
      if (!validDate(input.effectiveDate) || !reason || input.expectedVersion < 1) return failure("invalid-input"); if (input.effectiveDate > today) return failure("future-transition");
      return dependencies.store.transaction(principal.tenantId, async (tx) => {
        const teachers = await tx.listTeachers(), teacher = teachers.find((item) => item.id === teacherId); if (!teacher) return failure("not-found"); if (teacher.archived) return failure("archived"); if (teacher.version !== input.expectedVersion) return failure("conflict"); if (input.effectiveDate < teacher.serviceStartDate) return failure("invalid-effective-date");
        const allowed: readonly TeacherStatus[] = teacher.status === "active" ? ["leave", "ended"] : teacher.status === "leave" ? ["active", "ended"] : ["active"]; if (!allowed.includes(input.toStatus)) return failure("invalid-transition");
        const periods = await tx.listLifecyclePeriods(teacherId), current = periods.find((item) => item.endedAt === null); if (!current || input.effectiveDate < current.startedAt) return failure("invalid-effective-date");
        const person = (await tx.listPeople()).find((item) => item.id === teacher.personId); if (!person) return failure("not-found"); if (!await tx.closeLifecyclePeriod(current.id, input.effectiveDate)) return failure("conflict");
        const updated = { ...teacher, status: input.toStatus, version: teacher.version + 1, updatedAt: timestamp }; if (!await tx.saveTeacher(updated, teacher.version)) return failure("conflict");
        await tx.appendLifecyclePeriod({ id: id(), tenantId: principal.tenantId, teacherId, status: input.toStatus, startedAt: input.effectiveDate, endedAt: null, reason, notes, corrected: false, createdByUserId: principal.userId, createdAt: timestamp });
        await tx.appendAudit({ id: id(), tenantId: principal.tenantId, personId: person.id, teacherId, actorUserId: principal.userId, operation: "status-transitioned", fromPersonVersion: person.version, toPersonVersion: person.version, fromTeacherVersion: teacher.version, toTeacherVersion: updated.version, sensitiveBefore: null, sensitiveAfter: null, lifecycleBefore: { status: teacher.status, effectiveDate: current.startedAt }, lifecycleAfter: { status: input.toStatus, effectiveDate: input.effectiveDate }, reason, occurredAt: timestamp }); return { ok: true, record: updated } as const;
      });
    },
    async correctService(principal: MasterDataPrincipal, teacherId: string, input: { toStatus: Exclude<TeacherStatus, "ended">; effectiveDate: string; reason: string; notes?: string; expectedVersion: number }) {
      if (!principal.capabilities.write) return failure("read-only"); const timestamp = now(), reason = collapse(input.reason); if (!reason || !validDate(input.effectiveDate) || input.effectiveDate > timestamp.toISOString().slice(0, 10)) return failure("invalid-input");
      return dependencies.store.transaction(principal.tenantId, async (tx) => { const teacher = (await tx.listTeachers()).find((item) => item.id === teacherId); if (!teacher) return failure("not-found"); if (teacher.archived) return failure("archived"); if (teacher.version !== input.expectedVersion) return failure("conflict"); if (teacher.status !== "ended" || input.effectiveDate < teacher.serviceStartDate) return failure("invalid-transition"); const periods = await tx.listLifecyclePeriods(teacherId), current = periods.find((item) => item.endedAt === null); if (!current || current.status !== "ended" || input.effectiveDate < current.startedAt) return failure("invalid-effective-date"); const person = (await tx.listPeople()).find((item) => item.id === teacher.personId); if (!person) return failure("not-found"); if (!await tx.closeLifecyclePeriod(current.id, input.effectiveDate)) return failure("conflict"); const updated = { ...teacher, status: input.toStatus, version: teacher.version + 1, updatedAt: timestamp }; if (!await tx.saveTeacher(updated, teacher.version)) return failure("conflict"); await tx.appendLifecyclePeriod({ id: id(), tenantId: principal.tenantId, teacherId, status: input.toStatus, startedAt: input.effectiveDate, endedAt: null, reason, notes: optional(input.notes), corrected: true, createdByUserId: principal.userId, createdAt: timestamp }); await tx.appendAudit({ id: id(), tenantId: principal.tenantId, personId: person.id, teacherId, actorUserId: principal.userId, operation: "service-corrected", fromPersonVersion: person.version, toPersonVersion: person.version, fromTeacherVersion: teacher.version, toTeacherVersion: updated.version, sensitiveBefore: null, sensitiveAfter: null, lifecycleBefore: { status: "ended", effectiveDate: current.startedAt }, lifecycleAfter: { status: input.toStatus, effectiveDate: input.effectiveDate }, reason, occurredAt: timestamp }); return { ok: true, record: updated } as const; });
    },
    async archive(principal: MasterDataPrincipal, teacherId: string, input: { reason: string; expectedVersion: number }) {
      if (!principal.capabilities.write) return failure("read-only"); const timestamp = now(), reason = collapse(input.reason); if (!reason || input.expectedVersion < 1) return failure("invalid-input"); return dependencies.store.transaction(principal.tenantId, async (tx) => { const teacher = (await tx.listTeachers()).find((item) => item.id === teacherId); if (!teacher) return failure("not-found"); if (teacher.version !== input.expectedVersion) return failure("conflict"); if (teacher.archived) return failure("archived"); const person = (await tx.listPeople()).find((item) => item.id === teacher.personId); if (!person) return failure("not-found"); if (teacher.status !== "ended") { await tx.appendAudit({ id: id(), tenantId: principal.tenantId, personId: person.id, teacherId, actorUserId: principal.userId, operation: "archive-denied", fromPersonVersion: person.version, toPersonVersion: person.version, fromTeacherVersion: teacher.version, toTeacherVersion: teacher.version, sensitiveBefore: null, sensitiveAfter: null, reason: "Status Guru belum Berakhir", occurredAt: timestamp }); return failure("active-status"); } const blockers = await tx.listRelationshipBlockers(teacherId); if (blockers.length) { await tx.appendAudit({ id: id(), tenantId: principal.tenantId, personId: person.id, teacherId, actorUserId: principal.userId, operation: "archive-denied", fromPersonVersion: person.version, toPersonVersion: person.version, fromTeacherVersion: teacher.version, toTeacherVersion: teacher.version, sensitiveBefore: null, sensitiveAfter: null, reason: blockers.map((item) => item.label).join("; "), occurredAt: timestamp }); return failure("relationship-blocked", { blockers }); } const updated = { ...teacher, archived: true, archivedAt: timestamp, archiveReason: reason, version: teacher.version + 1, updatedAt: timestamp }; if (!await tx.saveTeacher(updated, teacher.version)) return failure("conflict"); await tx.appendAudit({ id: id(), tenantId: principal.tenantId, personId: person.id, teacherId, actorUserId: principal.userId, operation: "archived", fromPersonVersion: person.version, toPersonVersion: person.version, fromTeacherVersion: teacher.version, toTeacherVersion: updated.version, sensitiveBefore: null, sensitiveAfter: null, reason, occurredAt: timestamp }); return { ok: true, record: updated, warnings: person.accountActive ? ["Akun Pengguna tertaut masih aktif."] : [] } as const; });
    },
    async reactivate(principal: MasterDataPrincipal, teacherId: string, input: { reason: string; expectedVersion: number }) {
      if (!principal.capabilities.write) return failure("read-only"); const timestamp = now(), reason = collapse(input.reason); if (!reason || input.expectedVersion < 1) return failure("invalid-input"); return dependencies.store.transaction(principal.tenantId, async (tx) => { const teachers = await tx.listTeachers(), teacher = teachers.find((item) => item.id === teacherId); if (!teacher) return failure("not-found"); if (teacher.version !== input.expectedVersion) return failure("conflict"); if (!teacher.archived) return failure("not-archived"); const people = await tx.listPeople(), person = people.find((item) => item.id === teacher.personId); if (!person) return failure("not-found"); if (teachers.some((item) => item.id !== teacher.id && item.normalizedTeacherNumber === teacher.normalizedTeacherNumber)) return failure("duplicate-teacherNumber"); if (teacher.nuptk && teachers.some((item) => item.id !== teacher.id && item.nuptk === teacher.nuptk)) return failure("duplicate-nuptk"); if (await tx.listRelationshipBlockers(teacherId).then((items) => items.length)) return failure("relationship-blocked"); const reactivatedPerson = person.archived ? { ...person, archived: false, version: person.version + 1, updatedAt: timestamp } : person; if (person.archived && !await tx.savePerson(reactivatedPerson, person.version)) return failure("conflict"); const updated = { ...teacher, archived: false, archivedAt: null, archiveReason: null, version: teacher.version + 1, updatedAt: timestamp }; if (!await tx.saveTeacher(updated, teacher.version)) return failure("conflict"); await tx.appendAudit({ id: id(), tenantId: principal.tenantId, personId: person.id, teacherId, actorUserId: principal.userId, operation: "reactivated", fromPersonVersion: person.version, toPersonVersion: reactivatedPerson.version, fromTeacherVersion: teacher.version, toTeacherVersion: updated.version, sensitiveBefore: null, sensitiveAfter: null, reason, occurredAt: timestamp }); return { ok: true, record: updated } as const; });
    },
    edit(principal: MasterDataPrincipal, teacherId: string, input: TeacherInput, personVersion: number, teacherVersion: number) {
      if (!principal.capabilities.write) return Promise.resolve(failure("read-only")); const timestamp = now(), value = normalized(input, timestamp.toISOString().slice(0, 10)); if (!value || personVersion < 1 || teacherVersion < 1) return Promise.resolve(failure("invalid-input"));
      return dependencies.store.transaction(principal.tenantId, async (tx) => {
        const people = await tx.listPeople(), teachers = await tx.listTeachers(), currentTeacher = teachers.find((item) => item.id === teacherId), currentPerson = currentTeacher && people.find((item) => item.id === currentTeacher.personId);
        if (!currentTeacher || !currentPerson) return failure("not-found"); if (currentPerson.version !== personVersion || currentTeacher.version !== teacherVersion) return failure("conflict"); if (currentTeacher.archived || currentPerson.archived) return failure("archived");
        if (people.some((item) => item.id !== currentPerson.id && value.person.nik && item.nik === value.person.nik)) return failure("duplicate-nik"); if (people.some((item) => item.id !== currentPerson.id && value.person.nip && item.nip === value.person.nip)) return failure("duplicate-nip"); if (teachers.some((item) => item.id !== currentTeacher.id && item.normalizedTeacherNumber === value.teacher.normalizedTeacherNumber)) return failure("duplicate-teacherNumber"); if (teachers.some((item) => item.id !== currentTeacher.id && value.teacher.nuptk && item.nuptk === value.teacher.nuptk)) return failure("duplicate-nuptk");
        const person: SchoolPerson = { ...currentPerson, ...value.person, version: personVersion + 1, updatedAt: timestamp }, teacher: TeacherProfile = { ...currentTeacher, ...value.teacher, version: teacherVersion + 1, updatedAt: timestamp };
        if (!await tx.savePerson(person, personVersion) || !await tx.saveTeacher(teacher, teacherVersion)) return failure("conflict");
        await tx.appendAudit({ id: id(), tenantId: principal.tenantId, personId: person.id, teacherId: teacher.id, actorUserId: principal.userId, operation: "edited", fromPersonVersion: personVersion, toPersonVersion: person.version, fromTeacherVersion: teacherVersion, toTeacherVersion: teacher.version, sensitiveBefore: sensitive(currentPerson, currentTeacher), sensitiveAfter: sensitive(person, teacher), occurredAt: timestamp });
        return { ok: true, record: { person, teacher, classGroupName: null } } as const;
      });
    },
  };
}
