import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test, { after } from "node:test";
import mysql from "mysql2/promise";
import { closeDatabasePool } from "@/db";
import { createTeacherMasterDataService } from "@/lib/teacher-master-data";
import { teacherMasterDataStore } from "@/lib/teacher-master-data-data";
import type { MasterDataPrincipal } from "@/lib/tenant-master-data-access";
const url = process.env.DATABASE_URL, mysqlTest = url ? test : test.skip; after(async () => closeDatabasePool());
mysqlTest("MySQL keeps Warga Sekolah and Guru atomic, Tenant-isolated, unique, audited, and optimistic", async () => {
  const connection = await mysql.createConnection(url!); const ids = { provider: randomUUID(), tenantA: randomUUID(), tenantB: randomUUID(), adminA: randomUUID(), adminB: randomUUID(), bindingA: randomUUID(), bindingB: randomUUID(), appA: randomUUID(), appB: randomUUID() }; const npsnA = String(Math.floor(10_000_000 + Math.random() * 40_000_000)), npsnB = String(Math.floor(50_000_000 + Math.random() * 40_000_000));
  try {
    await connection.execute("INSERT INTO `user` (`id`,`name`,`email`,`email_verified`,`created_at`,`updated_at`) VALUES (?, 'Provider', ?, false, NOW(3), NOW(3)), (?, 'Admin A', ?, false, NOW(3), NOW(3)), (?, 'Admin B', ?, false, NOW(3), NOW(3))", [ids.provider, `${ids.provider}@test.invalid`, ids.adminA, `${ids.adminA}@test.invalid`, ids.adminB, `${ids.adminB}@test.invalid`]);
    await connection.execute("INSERT INTO `provider_admin` (`user_id`,`created_at`) VALUES (?, NOW(3))", [ids.provider]); await connection.execute("INSERT INTO `applicant_school_binding` (`id`,`user_id`,`canonical_npsn`,`created_at`) VALUES (?, ?, ?, NOW(3)), (?, ?, ?, NOW(3))", [ids.bindingA, ids.adminA, npsnA, ids.bindingB, ids.adminB, npsnB]);
    const appSql = "INSERT INTO `simas_application` (`id`,`school_name`,`npsn`,`education_level`,`address`,`contact_name`,`contact_position`,`contact_email`,`contact_whatsapp`,`status`,`submitted_at`,`owner_user_id`,`binding_id`,`attempt_number`,`idempotency_key`,`payload_hash`) VALUES (?, ?, ?, 'SMA', 'Alamat', 'Kontak', 'Operator', ?, '0812', 'pending', NOW(3), ?, ?, 1, ?, REPEAT('a',64))";
    await connection.execute(appSql, [ids.appA, "Sekolah A", npsnA, `${ids.appA}@test.invalid`, ids.adminA, ids.bindingA, randomUUID()]); await connection.execute(appSql, [ids.appB, "Sekolah B", npsnB, `${ids.appB}@test.invalid`, ids.adminB, ids.bindingB, randomUUID()]);
    await connection.execute("INSERT INTO `tenant` (`id`,`name`,`domain`,`npsn`,`source_application_id`,`approved_at`,`operational_status`,`created_at`,`updated_at`) VALUES (?, 'Sekolah A', ?, ?, ?, NOW(3), 'active', NOW(3), NOW(3)), (?, 'Sekolah B', ?, ?, ?, NOW(3), 'active', NOW(3), NOW(3))", [ids.tenantA, `teacher-a-${randomUUID()}`, npsnA, ids.appA, ids.tenantB, `teacher-b-${randomUUID()}`, npsnB, ids.appB]);
    for (const [app, tenantId] of [[ids.appA, ids.tenantA], [ids.appB, ids.tenantB]]) await connection.execute("UPDATE `simas_application` SET `status`='approved',`decided_at`=NOW(3),`decided_by_provider_admin_id`=?,`approved_tenant_id`=? WHERE `id`=?", [ids.provider, tenantId, app]); await connection.execute("UPDATE `user` SET `tenant_id`=?,`tenant_role`='school-admin' WHERE `id`=?", [ids.tenantA, ids.adminA]); await connection.execute("UPDATE `user` SET `tenant_id`=?,`tenant_role`='school-admin' WHERE `id`=?", [ids.tenantB, ids.adminB]);
    const p = (tenantId: string, userId: string): MasterDataPrincipal => ({ userId, tenantId, role: "school-admin", capabilities: { read: true, write: true, downloadTemplate: true } }), service = createTeacherMasterDataService({ store: teacherMasterDataStore }); const input = { fullName: "Aisyah Putri", birthPlace: "Palu", birthDate: "2012-01-01", gender: "female", nik: "0012345678901234", street: "Jalan Melati", teacherNumber: "00042", nuptk: "0012345678901234", employmentType: "civil-servant", assignmentStatus: "active", serviceStartDate: "2024-07-15" };
    const a = await service.create(p(ids.tenantA, ids.adminA), input), b = await service.create(p(ids.tenantB, ids.adminB), input); assert.equal(a.ok, true); assert.equal(b.ok, true); if (!a.ok) return;
    const moved = await service.transition(p(ids.tenantA, ids.adminA), a.record.teacher.id, { toStatus: "ended", effectiveDate: "2025-01-10", reason: "Kontrak berakhir", expectedVersion: 1 }); assert.equal(moved.ok, true);
    assert.deepEqual(await service.transition(p(ids.tenantB, ids.adminB), a.record.teacher.id, { toStatus: "active", effectiveDate: "2025-02-01", reason: "Kembali", expectedVersion: 2 }), { ok: false, code: "not-found" });
    await connection.execute("INSERT INTO `teacher_relationship` (`id`,`tenant_id`,`teacher_id`,`kind`,`label`,`active`) VALUES (?, ?, ?, 'class-membership', 'Rombongan Belajar 10A', true)", [randomUUID(), ids.tenantA, a.record.teacher.id]); const denied = await service.archive(p(ids.tenantA, ids.adminA), a.record.teacher.id, { reason: "Arsip", expectedVersion: 2 }); assert.equal(denied.ok, false); if (denied.ok) return; assert.equal(denied.code, "relationship-blocked");
    await connection.execute("UPDATE `teacher_relationship` SET `active`=false WHERE `tenant_id`=? AND `teacher_id`=?", [ids.tenantA, a.record.teacher.id]); assert.equal((await service.archive(p(ids.tenantA, ids.adminA), a.record.teacher.id, { reason: "Arsip", expectedVersion: 2 })).ok, true); assert.equal((await service.reactivate(p(ids.tenantA, ids.adminA), a.record.teacher.id, { reason: "Aktifkan kembali", expectedVersion: 3 })).ok, true);
    assert.equal((await service.transition(p(ids.tenantA, ids.adminA), a.record.teacher.id, { toStatus: "active", effectiveDate: "2025-02-01", reason: "Diterima kembali", expectedVersion: 4 })).ok, true); assert.equal((await service.transition(p(ids.tenantA, ids.adminA), a.record.teacher.id, { toStatus: "ended", effectiveDate: "2025-06-01", reason: "Berakhir", expectedVersion: 5 })).ok, true); assert.equal((await service.transition(p(ids.tenantA, ids.adminA), a.record.teacher.id, { toStatus: "active", effectiveDate: "2025-06-02", reason: "Diangkat kembali", expectedVersion: 6 })).ok, true);
    const [periods] = await connection.query<mysql.RowDataPacket[]>("SELECT `status`,`started_at`,`ended_at` FROM `teacher_service_period` WHERE `tenant_id`=? AND `teacher_id`=? ORDER BY `started_at`,`created_at`", [ids.tenantA, a.record.teacher.id]); assert.deepEqual(periods.map((row) => row.status), ["active", "ended", "active", "ended", "active"]); assert.equal(periods.at(-1)?.ended_at, null);
    assert.deepEqual(await service.create(p(ids.tenantA, ids.adminA), { ...input, nik: "9999888877776666" }), { ok: false, code: "duplicate-teacherNumber" }); assert.deepEqual(await service.edit(p(ids.tenantB, ids.adminB), a.record.teacher.id, input, 1, 1), { ok: false, code: "not-found" });
    const edited = await service.edit(p(ids.tenantA, ids.adminA), a.record.teacher.id, { ...input, teacherNumber: "00043" }, 1, 7); assert.equal(edited.ok, true); assert.deepEqual(await service.edit(p(ids.tenantA, ids.adminA), a.record.teacher.id, input, 1, 7), { ok: false, code: "conflict" });
    const [audits] = await connection.query<mysql.RowDataPacket[]>("SELECT `operation` FROM `teacher_audit` WHERE `tenant_id`=? ORDER BY `occurred_at`,`operation`", [ids.tenantA]); assert.deepEqual(new Set(audits.map((row) => row.operation)), new Set(["created-person", "created-teacher", "status-transitioned", "archive-denied", "archived", "reactivated", "edited"]));
    await assert.rejects(connection.execute("INSERT INTO `teacher_profile` (`id`,`tenant_id`,`person_id`,`teacher_number`,`normalized_teacher_number`,`employment_type`,`service_start_date`,`status`,`archived`,`version`,`created_at`,`updated_at`) VALUES (?, ?, ?, '9', '9', 'civil-servant', '2024-01-01', 'active', false, 1, NOW(3), NOW(3))", [randomUUID(), ids.tenantB, a.record.person.id]));
    const before = await connection.query<mysql.RowDataPacket[]>("SELECT COUNT(*) count FROM `school_person` WHERE `tenant_id`=?", [ids.tenantA]); await assert.rejects(teacherMasterDataStore.transaction(ids.tenantA, async (tx) => { const person = (await tx.listPeople())[0]; await tx.savePerson({ ...person, id: randomUUID(), nik: "1111222233334444" }, null); throw new Error("rollback"); })); const afterRows = await connection.query<mysql.RowDataPacket[]>("SELECT COUNT(*) count FROM `school_person` WHERE `tenant_id`=?", [ids.tenantA]); assert.equal(before[0][0].count, afterRows[0][0].count);
  } finally {
    await connection.execute("DELETE FROM `teacher_audit` WHERE `tenant_id` IN (?, ?)", [ids.tenantA, ids.tenantB]).catch(() => undefined); await connection.execute("DELETE FROM `teacher_relationship` WHERE `tenant_id` IN (?, ?)", [ids.tenantA, ids.tenantB]).catch(() => undefined); await connection.execute("DELETE FROM `teacher_service_period` WHERE `tenant_id` IN (?, ?)", [ids.tenantA, ids.tenantB]).catch(() => undefined); await connection.execute("DELETE FROM `teacher_profile` WHERE `tenant_id` IN (?, ?)", [ids.tenantA, ids.tenantB]).catch(() => undefined); await connection.execute("DELETE FROM `school_person` WHERE `tenant_id` IN (?, ?)", [ids.tenantA, ids.tenantB]).catch(() => undefined); await connection.execute("DELETE FROM `tenant` WHERE `id` IN (?, ?)", [ids.tenantA, ids.tenantB]).catch(() => undefined); await connection.execute("DELETE FROM `simas_application` WHERE `id` IN (?, ?)", [ids.appA, ids.appB]).catch(() => undefined); await connection.execute("DELETE FROM `applicant_school_binding` WHERE `id` IN (?, ?)", [ids.bindingA, ids.bindingB]).catch(() => undefined); await connection.execute("DELETE FROM `provider_admin` WHERE `user_id`=?", [ids.provider]).catch(() => undefined); await connection.execute("DELETE FROM `user` WHERE `id` IN (?, ?, ?)", [ids.provider, ids.adminA, ids.adminB]).catch(() => undefined); await connection.end();
  }
});
