"use server";
import { revalidatePath } from "next/cache";import { redirect } from "next/navigation";import { createStudentOrganizationService } from "@/lib/student-organization";import { studentOrganizationStore } from "@/lib/student-organization-data";import { enforceMasterDataAccess } from "@/lib/tenant-master-data-route-access";
const service=createStudentOrganizationService({store:studentOrganizationStore}),text=(f:FormData,n:string)=>String(f.get(n)??""),optional=(f:FormData,n:string)=>text(f,n)||null;
function finish(domain:string,result:{ok:boolean;code?:string}){revalidatePath(`/${domain}/master/organisasi`);redirect(`/${domain}/master/organisasi?result=${result.ok?"saved":result.code??"error"}`);}
export async function createOrganizationAction(domain:string,f:FormData){finish(domain,await service.createOrganization(await enforceMasterDataAccess(domain,"write"),{name:text(f,"name"),abbreviation:optional(f,"abbreviation"),code:text(f,"code"),description:optional(f,"description"),foundingDate:optional(f,"foundingDate"),secretariatLocationId:optional(f,"secretariatLocationId")}));}
export async function createPeriodAction(domain:string,f:FormData){finish(domain,await service.createPeriod(await enforceMasterDataAccess(domain,"write"),{organizationId:text(f,"organizationId"),name:text(f,"name"),startDate:text(f,"startDate"),endDate:text(f,"endDate")}));}
export async function transitionPeriodAction(domain:string,f:FormData){finish(domain,await service.transitionPeriod(await enforceMasterDataAccess(domain,"write"),text(f,"periodId"),text(f,"operation") as "activate"|"complete",{expectedVersion:Number(f.get("expectedVersion")),reason:text(f,"reason")}));}
export async function correctPeriodAction(domain:string,f:FormData){finish(domain,await service.correctCompletedPeriod(await enforceMasterDataAccess(domain,"write"),text(f,"periodId"),{expectedVersion:Number(f.get("expectedVersion")),startDate:text(f,"startDate"),endDate:text(f,"endDate"),reason:text(f,"reason")}));}
export async function addMembershipAction(domain:string,f:FormData){finish(domain,await service.addMembership(await enforceMasterDataAccess(domain,"write"),{organizationId:text(f,"organizationId"),studentId:text(f,"studentId"),startDate:text(f,"startDate"),endDate:optional(f,"endDate"),reason:text(f,"reason")}));}
export async function endMembershipAction(domain:string,f:FormData){finish(domain,await service.endMembership(await enforceMasterDataAccess(domain,"write"),text(f,"membershipId"),{effectiveDate:text(f,"effectiveDate"),reason:text(f,"reason")}));}
export async function assignLeadershipAction(domain:string,f:FormData){finish(domain,await service.assignLeadership(await enforceMasterDataAccess(domain,"write"),{periodId:text(f,"periodId"),studentId:text(f,"studentId"),positionName:text(f,"positionName"),allowsMultipleHolders:f.get("allowsMultipleHolders")==="on",startDate:text(f,"startDate"),endDate:optional(f,"endDate"),reason:text(f,"reason")}));}
export async function endLeadershipAction(domain:string,f:FormData){finish(domain,await service.endLeadership(await enforceMasterDataAccess(domain,"write"),text(f,"leadershipId"),{effectiveDate:text(f,"effectiveDate"),reason:text(f,"reason")}));}
export async function archiveOrganizationAction(domain:string,f:FormData){finish(domain,await service.archiveOrganization(await enforceMasterDataAccess(domain,"write"),text(f,"organizationId"),{expectedVersion:Number(f.get("expectedVersion")),reason:text(f,"reason")}));}
