export const TENANT_FEATURE_DOMAINS = [
  { key: "master-data", label: "Data Master" },
  { key: "master-data-import", label: "Impor Data Master" },
  { key: "academic-assessment", label: "Akademik · Penilaian" },
  { key: "admissions", label: "Pendaftaran · PPDB" },
  { key: "analytics", label: "Analitik" },
] as const;

export type TenantFeatureDomain = (typeof TENANT_FEATURE_DOMAINS)[number]["key"];

export const TENANT_FEATURES = [
  {
    key: "masterData",
    label: "Data Master",
    description: "Fitur induk untuk seluruh akses dan operasi Data Master.",
    functionalDomain: "master-data",
    routes: ["/master/**"],
  },
  {
    key: "masterDataRead",
    label: "Baca Data Master",
    description: "Mengizinkan Tenant membuka dan melihat halaman Data Master.",
    functionalDomain: "master-data",
    routes: ["/master/**"],
    requires: ["masterData"],
  },
  {
    key: "masterDataWrite",
    label: "Kelola Data Master",
    description: "Mengizinkan School Admin menambah dan mengubah Data Master.",
    functionalDomain: "master-data",
    routes: ["/master/**"],
    requires: ["masterData", "masterDataRead"],
  },
  {
    key: "masterDataImportDownload",
    label: "Unduh Template Impor",
    description: "Mengizinkan Tenant mengunduh template impor Data Master.",
    functionalDomain: "master-data-import",
    routes: ["/master/import/template/**"],
    requires: ["masterData", "masterDataRead"],
  },
  {
    key: "masterDataImportValidation",
    label: "Validasi Impor",
    description: "Mengizinkan Tenant mengunggah dan memvalidasi berkas impor.",
    functionalDomain: "master-data-import",
    routes: ["/master/import", "/master/import/upload", "/master/import/**/revision"],
    requires: ["masterData", "masterDataRead", "masterDataWrite"],
  },
  {
    key: "masterDataImportExecution",
    label: "Eksekusi Impor",
    description: "Mengizinkan Tenant menerapkan hasil impor yang telah divalidasi.",
    functionalDomain: "master-data-import",
    routes: ["/master/import/**/execution/**"],
    requires: ["masterData", "masterDataRead", "masterDataWrite", "masterDataImportValidation"],
  },
  {
    key: "ulangan",
    label: "Ulangan",
    description: "Fitur induk untuk seluruh akses dan operasi Ulangan.",
    functionalDomain: "academic-assessment",
    routes: ["/ulangan/**"],
    requires: ["masterData", "masterDataRead"],
  },
  {
    key: "ulanganRead",
    label: "Baca Ulangan",
    description: "Mengizinkan Tenant membuka dan melihat halaman Ulangan.",
    functionalDomain: "academic-assessment",
    routes: ["/ulangan/**"],
    requires: ["ulangan"],
  },
  {
    key: "ulanganWrite",
    label: "Kelola Ulangan",
    description: "Mengizinkan Tenant membuat dan mengelola sesi Ulangan.",
    functionalDomain: "academic-assessment",
    routes: ["/ulangan/**"],
    requires: ["ulangan", "ulanganRead", "masterDataWrite"],
  },
  {
    key: "ppdb",
    label: "PPDB",
    description: "Fitur induk untuk seluruh akses dan operasi PPDB.",
    functionalDomain: "admissions",
    routes: ["/ppdb/**", "/{domain}/ppdb/**"],
    requires: ["masterData", "masterDataRead"],
  },
  {
    key: "ppdbRead",
    label: "Baca PPDB",
    description: "Mengizinkan Tenant membuka dan melihat halaman pengelolaan PPDB.",
    functionalDomain: "admissions",
    routes: ["/{domain}/ppdb/**"],
    requires: ["ppdb"],
  },
  {
    key: "ppdbWrite",
    label: "Kelola PPDB",
    description: "Mengizinkan Tenant membuat sesi dan mengelola pendaftar PPDB.",
    functionalDomain: "admissions",
    routes: ["/{domain}/ppdb/**"],
    requires: ["ppdb", "ppdbRead", "masterDataWrite"],
  },
  {
    key: "ppdbPublic",
    label: "Pendaftaran PPDB Publik",
    description: "Mengizinkan calon siswa membuka, mengirim, dan memeriksa pendaftaran PPDB.",
    functionalDomain: "admissions",
    routes: ["/ppdb/{domain}/**"],
    requires: ["ppdb"],
  },
  {
    key: "advancedAnalytics",
    label: "Analitik Lanjutan",
    description: "Menampilkan komponen analitik lanjutan pada dashboard Tenant.",
    functionalDomain: "analytics",
    routes: ["/dashboard"],
  },
] as const;

export type TenantFeatureKey = (typeof TENANT_FEATURES)[number]["key"];
