"use server";
import {revalidatePath} from "next/cache";import {redirect} from "next/navigation";import {createExtracurricularService} from "@/lib/extracurricular";import {extracurricularStore} from "@/lib/extracurricular-data";import {enforceMasterDataAccess} from "@/lib/tenant-master-data-route-access";
const service=createExtracurricularService({store:extracurricularStore}),text=(f:FormData,n:string)=>String(f.get(n)??""),optional=(f:FormData,n:string)=>text(f,n)||null;function finish(domain:string,result:{ok:boolean;code?:string}){revalidatePath(`/${domain}/master/organisasi/ekstrakurikuler`);redirect(`/${domain}/master/organisasi/ekstrakurikuler?result=${result.ok?"saved":result.code??"error"}`)}
export async function createExtracurricularAction(domain:string,f:FormData){finish(domain,await service.createExtracurricular(await enforceMasterDataAccess(domain,"write"),{name:text(f,"name"),code:text(f,"code"),description:optional(f,"description"),defaultLocationId:optional(f,"defaultLocationId")}))}
export async function createGroupAction(domain:string,f:FormData){finish(domain,await service.createGroup(await enforceMasterDataAccess(domain,"write"),{extracurricularId:text(f,"extracurricularId"),academicYearId:text(f,"academicYearId"),name:text(f,"name"),startDate:text(f,"startDate"),endDate:text(f,"endDate"),capacity:Number(f.get("capacity")),locationId:optional(f,"locationId"),scheduleText:text(f,"scheduleText")}))}
export async function transitionGroupAction(domain:string,f:FormData){finish(domain,await service.transitionGroup(await enforceMasterDataAccess(domain,"write"),text(f,"groupId"),text(f,"operation") as "activate"|"complete"|"cancel",{expectedVersion:Number(f.get("expectedVersion")),reason:text(f,"reason")}))}
export async function assignAdvisorAction(domain:string,f:FormData){finish(domain,await service.assignAdvisor(await enforceMasterDataAccess(domain,"write"),{groupId:text(f,"groupId"),advisorKind:text(f,"advisorKind") as "teacher"|"staff",advisorId:text(f,"advisorId"),startDate:text(f,"startDate"),endDate:optional(f,"endDate"),reason:text(f,"reason")}))}
export async function enrollParticipantAction(domain:string,f:FormData){finish(domain,await service.enrollParticipant(await enforceMasterDataAccess(domain,"write"),{groupId:text(f,"groupId"),studentId:text(f,"studentId"),startDate:text(f,"startDate"),endDate:optional(f,"endDate"),reason:text(f,"reason")}))}
export async function endAdvisorAction(domain:string,f:FormData){finish(domain,await service.endAdvisor(await enforceMasterDataAccess(domain,"write"),text(f,"advisorId"),{effectiveDate:text(f,"effectiveDate"),reason:text(f,"reason")}))}
export async function endParticipantAction(domain:string,f:FormData){finish(domain,await service.endParticipant(await enforceMasterDataAccess(domain,"write"),text(f,"participantId"),{effectiveDate:text(f,"effectiveDate"),reason:text(f,"reason")}))}
export async function archiveExtracurricularAction(domain:string,f:FormData){finish(domain,await service.archiveExtracurricular(await enforceMasterDataAccess(domain,"write"),text(f,"extracurricularId"),{expectedVersion:Number(f.get("expectedVersion")),reason:text(f,"reason")}))}
