import { MasterDataFormDialog } from "@/components/master-data/master-data-form-dialog";

import { createLocationAction,editLocationAction,manageLocationAction } from "./actions";
import { MasterDataWorkspace } from "@/components/master-data/master-data-workspace";
import { createLocationService,LOCATION_TYPES,type Location } from "@/lib/location";import { locationStore } from "@/lib/location-data";import { queryLocations } from "@/lib/location-query";import type { MasterDataSearchParams } from "@/lib/master-data-workspace";import { enforceMasterDataAccess } from "@/lib/tenant-master-data-route-access";
const labels={site:"Area",building:"Gedung",floor:"Lantai",room:"Ruang",outdoor:"Area luar",other:"Lainnya"} as const;
export default async function SarprasPage({params,searchParams}:{params:Promise<{domain:string}>;searchParams:Promise<MasterDataSearchParams&{result?:string}>}){const[{domain},raw]=await Promise.all([params,searchParams]),principal=await enforceMasterDataAccess(domain,"read"),service=createLocationService({store:locationStore}),records=await service.list(principal),result=queryLocations(records,raw),selected=records.find(x=>x.id===result.query.selected),blockers=selected?await service.blockers(principal,selected.id):[],basePath=`/${domain}/master/sarpras`,code=typeof raw.result==="string"?raw.result:undefined;return <div className="space-y-6 p-4 md:p-6">{code?<p role={code==="saved"?"status":"alert"} className="rounded-lg border p-3">{code==="saved"?"Perubahan Lokasi/Ruang tersimpan.":code==="relationship-blocked"?"Arsip ditolak; semua blocker aktif ditampilkan pada detail.":`Perubahan ditolak: ${code}.`}</p>:null}<MasterDataWorkspace title="Sarana & Prasarana — Lokasi/Ruang" description="Kelola hierarchy Lokasi/Ruang tanpa cycle atau hidden cascade." basePath={basePath} query={result.query} total={result.total} items={result.items.map(x=>({id:x.id,title:x.name,description:`${x.code} · ${labels[x.type]}`,lifecycle:labels[x.type],archived:x.archived}))} detail={selected?<Detail domain={domain} record={selected} records={records} blockers={blockers} writable={principal.capabilities.write}/>:undefined} filters={[{name:"type",label:"Tipe",options:Object.entries(labels).map(([value,label])=>({value,label}))}]} sortOptions={[{value:"name-asc",label:"Nama A–Z"},{value:"name-desc",label:"Nama Z–A"},{value:"code-asc",label:"Kode A–Z"}]}>{principal.capabilities.write?<MasterDataFormDialog title="Buat Lokasi/Ruang"><LocationForm domain={domain} records={records}/></MasterDataFormDialog>:<p>Workspace hanya-baca.</p>}</MasterDataWorkspace></div>}
function Detail({domain,record,records,blockers,writable}:{domain:string;record:Location;records:Location[];blockers:readonly {id:string;label:string}[];writable:boolean}){const parent=records.find(x=>x.id===record.parentId),children=records.filter(x=>x.parentId===record.id);return <div className="space-y-5"><h3 className="font-semibold">Detail hierarchy</h3><dl className="grid gap-3 sm:grid-cols-2"><Item label="Nama" value={record.name}/><Item label="Kode" value={record.code}/><Item label="Tipe" value={labels[record.type]}/><Item label="Kapasitas" value={record.capacity?.toString()??"—"}/><Item label="Parent" value={parent?.name??"Akar"}/><Item label="Status arsip" value={record.archived?"Diarsipkan":"Aktif"}/></dl><section><h3 className="font-semibold">Child</h3><p>{children.length?children.map(x=>`${x.name}${x.archived?" (diarsipkan)":""}`).join(", "):"Tidak ada child."}</p></section><section><h3 className="font-semibold">Blocker archive aktif</h3>{blockers.length?<ul className="list-disc pl-5">{blockers.map(x=><li key={x.id}>{x.label}</li>)}</ul>:<p>Tidak ada blocker aktif.</p>}</section>{writable?<>{!record.archived?<><details className="rounded-lg border p-4"><summary>Edit Lokasi/Ruang</summary><LocationForm domain={domain} records={records} record={record}/></details><Action domain={domain} record={record} operation="archive" label="Arsipkan lokasi"/></>:<Action domain={domain} record={record} operation="reactivate" label="Aktifkan kembali"/>}</>:null}<p className="text-sm text-muted-foreground">Archive tidak mengarsipkan child atau references; setiap blocker aktif ditampilkan.</p></div>}
function LocationForm({domain,records,record}:{domain:string;records:Location[];record?:Location}){return <form action={(record?editLocationAction:createLocationAction).bind(null,domain)} className="mt-3 grid gap-3 sm:grid-cols-2">{record?<><input type="hidden" name="id" value={record.id}/><input type="hidden" name="expectedVersion" value={record.version}/></>:null}<Field name="name" label="Nama" value={record?.name}/><Field name="code" label="Kode" value={record?.code}/><Select name="type" label="Tipe" value={record?.type} options={LOCATION_TYPES.map(x=>({value:x,label:labels[x]}))}/><Field name="capacity" label="Kapasitas (opsional)" type="number" value={record?.capacity??undefined}/><Select name="parentId" label="Parent (opsional)" value={record?.parentId??""} options={records.filter(x=>!x.archived&&x.id!==record?.id).map(x=>({value:x.id,label:x.name}))} optional/><label className="sm:col-span-2"><span className="text-sm font-medium">Deskripsi (opsional)</span><textarea name="description" defaultValue={record?.description??""} className="mt-1 min-h-20 w-full border p-3"/></label><button className="min-h-11 rounded-full bg-primary px-4 text-primary-foreground sm:col-span-2">Simpan</button></form>}
function Action({domain,record,operation,label}:{domain:string;record:Location;operation:string;label:string}){return <form action={manageLocationAction.bind(null,domain)} className="rounded-lg border p-4"><input type="hidden" name="id" value={record.id}/><input type="hidden" name="expectedVersion" value={record.version}/><input type="hidden" name="operation" value={operation}/><Field name="reason" label="Alasan"/><button className="mt-3 min-h-11 rounded-full border px-4">{label}</button></form>}
function Field({name,label,type="text",value}:{name:string;label:string;type?:string;value?:string|number}){return <label><span className="text-sm font-medium">{label}</span><input required={!label.includes("opsional")} name={name} type={type} defaultValue={value} className="mt-1 h-11 w-full border px-3"/></label>}
function Select({name,label,value,options,optional=false}:{name:string;label:string;value?:string;options:{value:string;label:string}[];optional?:boolean}){return <label><span className="text-sm font-medium">{label}</span><select required={!optional} name={name} defaultValue={value??""} className="mt-1 h-11 w-full border px-3"><option value="">{optional?"Tanpa parent":"Pilih"}</option>{options.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label>}
function Item({label,value}:{label:string;value:string}){return <div><dt className="text-sm text-muted-foreground">{label}</dt><dd>{value}</dd></div>}
