CREATE TABLE `teaching_assignment` (
  `id` varchar(36) NOT NULL,
  `tenant_id` varchar(36) NOT NULL,
  `teacher_profile_id` varchar(36) NOT NULL,
  `subject_id` varchar(36) NOT NULL,
  `class_group_id` varchar(36) NOT NULL,
  `academic_year_id` varchar(36) NOT NULL,
  `starts_on` date NOT NULL,
  `ends_on` date DEFAULT NULL,
  `status` enum('planned','active','ended','cancelled') NOT NULL DEFAULT 'planned',
  `reason` varchar(1000) NOT NULL,
  `version` int NOT NULL DEFAULT 1,
  `created_by_user_id` varchar(36) NOT NULL,
  `created_at` timestamp(3) NOT NULL,
  `updated_at` timestamp(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `teaching_assignment_tenant_id_unique` (`tenant_id`,`id`),
  KEY `teaching_assignment_scope_idx` (`tenant_id`,`teacher_profile_id`,`subject_id`,`class_group_id`,`academic_year_id`,`status`,`starts_on`,`ends_on`),
  CONSTRAINT `teaching_assignment_teacher_fkey` FOREIGN KEY (`tenant_id`,`teacher_profile_id`) REFERENCES `teacher_profile` (`tenant_id`,`id`),
  CONSTRAINT `teaching_assignment_subject_fkey` FOREIGN KEY (`tenant_id`,`subject_id`) REFERENCES `subject` (`tenant_id`,`id`),
  CONSTRAINT `teaching_assignment_class_group_fkey` FOREIGN KEY (`tenant_id`,`class_group_id`) REFERENCES `class_group` (`tenant_id`,`id`),
  CONSTRAINT `teaching_assignment_academic_year_fkey` FOREIGN KEY (`tenant_id`,`academic_year_id`) REFERENCES `academic_year` (`tenant_id`,`id`),
  CONSTRAINT `teaching_assignment_actor_fkey` FOREIGN KEY (`tenant_id`,`created_by_user_id`) REFERENCES `user` (`tenant_id`,`id`),
  CONSTRAINT `teaching_assignment_version_check` CHECK (`version` > 0),
  CONSTRAINT `teaching_assignment_range_check` CHECK (`ends_on` IS NULL OR `ends_on` > `starts_on`)
);

CREATE TABLE `teaching_assignment_event` (
  `id` varchar(36) NOT NULL,
  `tenant_id` varchar(36) NOT NULL,
  `teaching_assignment_id` varchar(36) NOT NULL,
  `actor_user_id` varchar(36) NOT NULL,
  `operation` enum('created','planned-updated','activated','ended','cancelled','replaced') NOT NULL,
  `from_version` int NOT NULL,
  `to_version` int NOT NULL,
  `effective_on` date NOT NULL,
  `reason` varchar(1000) NOT NULL,
  `occurred_at` timestamp(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `teaching_assignment_event_scope_idx` (`tenant_id`,`teaching_assignment_id`,`occurred_at`),
  CONSTRAINT `teaching_assignment_event_assignment_fkey` FOREIGN KEY (`tenant_id`,`teaching_assignment_id`) REFERENCES `teaching_assignment` (`tenant_id`,`id`),
  CONSTRAINT `teaching_assignment_event_actor_fkey` FOREIGN KEY (`tenant_id`,`actor_user_id`) REFERENCES `user` (`tenant_id`,`id`),
  CONSTRAINT `teaching_assignment_event_version_check` CHECK (`from_version` >= 0 AND `to_version` = `from_version` + 1)
);
